-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c171.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c171
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(1590, 1600, 179), (1601, 1612, 178), (1613, 1623, 177), (1624, 1635, 176), (1636, 1647, 175), (1648, 1660, 174), (1661, 1672, 173), (1673, 1685, 172), (1686, 1697, 171), (1698, 1710, 170), (1711, 1723, 169), (1724, 1737, 168), (1738, 1750, 167), (1751, 1764, 166), (1765, 1777, 165), (1778, 1791, 164), (1792, 1806, 163), (1807, 1820, 162), (1821, 1835, 161), (1836, 1849, 160), (1850, 1864, 159), (1865, 1880, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c171
