-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c523.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c523
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(3534, 3545, 135), (3546, 3558, 134), (3559, 3571, 133), (3572, 3585, 132), (3586, 3599, 131), (3600, 3612, 130), (3613, 3627, 129), (3628, 3641, 128), (3642, 3656, 127), (3657, 3671, 126), (3672, 3686, 125), (3687, 3702, 124), (3703, 3717, 123), (3718, 3733, 122), (3734, 3750, 121), (3751, 3767, 120), (3768, 3784, 119), (3785, 3801, 118), (3802, 3819, 117), (3820, 3837, 116), (3838, 3856, 115), (3857, 3875, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c523
