-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c52.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c52
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(6720, 6776, 135), (6777, 6834, 134), (6835, 6893, 133), (6894, 6952, 132), (6953, 7012, 131), (7013, 7073, 130), (7074, 7135, 129), (7136, 7197, 128), (7198, 7260, 127), (7261, 7324, 126), (7325, 7389, 125), (7390, 7455, 124), (7456, 7521, 123), (7522, 7588, 122), (7589, 7657, 121), (7658, 7726, 120), (7727, 7796, 119), (7797, 7867, 118), (7868, 7938, 117), (7939, 8011, 116), (8012, 8085, 115), (8086, 8160, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c52
