-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c52.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c52
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(4777, 4811, 179), (4812, 4845, 178), (4846, 4880, 177), (4881, 4915, 176), (4916, 4951, 175), (4952, 4987, 174), (4988, 5024, 173), (5025, 5061, 172), (5062, 5098, 171), (5099, 5136, 170), (5137, 5174, 169), (5175, 5213, 168), (5214, 5252, 167), (5253, 5291, 166), (5292, 5331, 165), (5332, 5372, 164), (5373, 5413, 163), (5414, 5454, 162), (5455, 5496, 161), (5497, 5538, 160), (5539, 5581, 159), (5582, 5624, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c52
