-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c542.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c542
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 4870, 201), (4871, 4872, 200), (4873, 4873, 199), (4874, 4876, 198), (4877, 4878, 197), (4879, 4880, 196), (4881, 4882, 195), (4883, 4884, 194), (4885, 4886, 193), (4887, 4888, 192), (4889, 4890, 191), (4891, 4893, 190), (4894, 4895, 189), (4896, 4897, 188), (4898, 4900, 187), (4901, 4902, 186), (4903, 4904, 185), (4905, 4907, 184), (4908, 4909, 183), (4910, 4912, 182), (4913, 4915, 181), (4916, 4917, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c542
