-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c254.Data9
import Solutions.SharpCertFast.P06P0r12c254.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c254
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d9_0_okE : (d9_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2300, 2311, 158), (2312, 2324, 157), (2325, 2336, 156)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_0_k : d9_0.map (·.k) = List.range' 2304 32 := by decide +kernel
theorem d9_1_okE : (d9_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2325, 2336, 156), (2337, 2349, 155), (2350, 2362, 154), (2363, 2375, 153)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_1_k : d9_1.map (·.k) = List.range' 2336 32 := by decide +kernel
theorem d9_2_okE : (d9_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2363, 2375, 153), (2376, 2388, 152), (2389, 2402, 151)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_2_k : d9_2.map (·.k) = List.range' 2368 32 := by decide +kernel
theorem d9_3_okE : (d9_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2389, 2402, 151), (2403, 2416, 150), (2417, 2430, 149), (2431, 2444, 148)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_3_k : d9_3.map (·.k) = List.range' 2400 32 := by decide +kernel
theorem d9_4_okE : (d9_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2431, 2444, 148), (2445, 2458, 147), (2459, 2473, 146)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_4_k : d9_4.map (·.k) = List.range' 2432 32 := by decide +kernel
theorem d9_5_okE : (d9_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2459, 2473, 146), (2474, 2488, 145), (2489, 2503, 144)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_5_k : d9_5.map (·.k) = List.range' 2464 32 := by decide +kernel
theorem d9_6_okE : (d9_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2489, 2503, 144), (2504, 2518, 143), (2519, 2534, 142)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_6_k : d9_6.map (·.k) = List.range' 2496 32 := by decide +kernel
theorem d9_7_okE : (d9_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2519, 2534, 142), (2535, 2550, 141), (2551, 2566, 140)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_7_k : d9_7.map (·.k) = List.range' 2528 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c254
