-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c254.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c254
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(3809, 3849, 91), (3850, 3890, 90), (3891, 3932, 89), (3933, 3975, 88), (3976, 4019, 87), (4020, 4064, 86), (4065, 4110, 85), (4111, 4157, 84), (4158, 4205, 83), (4206, 4254, 82), (4255, 4304, 81), (4305, 4355, 80), (4356, 4408, 79), (4409, 4461, 78), (4462, 4516, 77), (4517, 4572, 76), (4573, 4629, 75), (4630, 4687, 74), (4688, 4747, 73), (4748, 4808, 72), (4809, 4871, 71), (4872, 4934, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c254
