-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c254.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c254
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(2312, 2324, 157), (2325, 2336, 156), (2337, 2349, 155), (2350, 2362, 154), (2363, 2375, 153), (2376, 2388, 152), (2389, 2402, 151), (2403, 2416, 150), (2417, 2430, 149), (2431, 2444, 148), (2445, 2458, 147), (2459, 2473, 146), (2474, 2488, 145), (2489, 2503, 144), (2504, 2518, 143), (2519, 2534, 142), (2535, 2550, 141), (2551, 2566, 140), (2567, 2582, 139), (2583, 2599, 138), (2600, 2616, 137), (2617, 2633, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c254
