-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c412.Data12
import Solutions.SharpCertFast.P06P0r12c412.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c412
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d12_0_okE : (d12_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3067, 3075, 155), (3076, 3085, 154), (3086, 3095, 153), (3096, 3105, 152)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_0_k : d12_0.map (·.k) = List.range' 3072 32 := by decide +kernel
theorem d12_1_okE : (d12_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3096, 3105, 152), (3106, 3115, 151), (3116, 3125, 150), (3126, 3135, 149)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_1_k : d12_1.map (·.k) = List.range' 3104 32 := by decide +kernel
theorem d12_2_okE : (d12_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3136, 3146, 148), (3147, 3157, 147), (3158, 3168, 146)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_2_k : d12_2.map (·.k) = List.range' 3136 32 := by decide +kernel
theorem d12_3_okE : (d12_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3158, 3168, 146), (3169, 3179, 145), (3180, 3190, 144), (3191, 3202, 143)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_3_k : d12_3.map (·.k) = List.range' 3168 32 := by decide +kernel
theorem d12_4_okE : (d12_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3191, 3202, 143), (3203, 3214, 142), (3215, 3226, 141), (3227, 3238, 140)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_4_k : d12_4.map (·.k) = List.range' 3200 32 := by decide +kernel
theorem d12_5_okE : (d12_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3227, 3238, 140), (3239, 3250, 139), (3251, 3263, 138)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_5_k : d12_5.map (·.k) = List.range' 3232 32 := by decide +kernel
theorem d12_6_okE : (d12_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3264, 3276, 137), (3277, 3289, 136), (3290, 3302, 135)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_6_k : d12_6.map (·.k) = List.range' 3264 32 := by decide +kernel
theorem d12_7_okE : (d12_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3290, 3302, 135), (3303, 3316, 134), (3317, 3330, 133)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_7_k : d12_7.map (·.k) = List.range' 3296 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c412
