-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c412.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c412
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(3290, 3302, 135), (3303, 3316, 134), (3317, 3330, 133), (3331, 3344, 132), (3345, 3358, 131), (3359, 3372, 130), (3373, 3387, 129), (3388, 3402, 128), (3403, 3418, 127), (3419, 3433, 126), (3434, 3449, 125), (3450, 3466, 124), (3467, 3482, 123), (3483, 3499, 122), (3500, 3516, 121), (3517, 3534, 120), (3535, 3552, 119), (3553, 3570, 118), (3571, 3589, 117), (3590, 3608, 116), (3609, 3627, 115), (3628, 3647, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c412
