-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c144.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c144
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(14470, 14618, 47), (14619, 14769, 46), (14770, 14922, 45), (14923, 15076, 44), (15077, 15232, 43), (15233, 15390, 42), (15391, 15549, 41), (15550, 15709, 40), (15710, 15870, 39), (15871, 16032, 38), (16033, 16195, 37), (16196, 16348, 36), (16349, 16382, 35), (16383, 16383, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c144
