-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c340.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c340
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(2458, 2466, 179), (2467, 2475, 178), (2476, 2484, 177), (2485, 2493, 176), (2494, 2503, 175), (2504, 2512, 174), (2513, 2522, 173), (2523, 2532, 172), (2533, 2542, 171), (2543, 2552, 170), (2553, 2562, 169), (2563, 2572, 168), (2573, 2583, 167), (2584, 2593, 166), (2594, 2604, 165), (2605, 2615, 164), (2616, 2626, 163), (2627, 2637, 162), (2638, 2649, 161), (2650, 2660, 160), (2661, 2672, 159), (2673, 2684, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c340
