-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c766.Data21
import Solutions.SharpCertFast.P06P0r12c766.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c766
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d21_0_okE : (d21_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5363, 5381, 90), (5382, 5400, 89), (5401, 5420, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_0_k : d21_0.map (·.k) = List.range' 5376 32 := by decide +kernel
theorem d21_1_okE : (d21_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5401, 5420, 88), (5421, 5440, 87)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_1_k : d21_1.map (·.k) = List.range' 5408 32 := by decide +kernel
theorem d21_2_okE : (d21_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5421, 5440, 87), (5441, 5461, 86), (5462, 5482, 85)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_2_k : d21_2.map (·.k) = List.range' 5440 32 := by decide +kernel
theorem d21_3_okE : (d21_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5462, 5482, 85), (5483, 5504, 84)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_3_k : d21_3.map (·.k) = List.range' 5472 32 := by decide +kernel
theorem d21_4_okE : (d21_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5483, 5504, 84), (5505, 5526, 83), (5527, 5549, 82)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_4_k : d21_4.map (·.k) = List.range' 5504 32 := by decide +kernel
theorem d21_5_okE : (d21_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5527, 5549, 82), (5550, 5573, 81)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_5_k : d21_5.map (·.k) = List.range' 5536 32 := by decide +kernel
theorem d21_6_okE : (d21_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5550, 5573, 81), (5574, 5597, 80), (5598, 5622, 79)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_6_k : d21_6.map (·.k) = List.range' 5568 32 := by decide +kernel
theorem d21_7_okE : (d21_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5598, 5622, 79), (5623, 5648, 78)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_7_k : d21_7.map (·.k) = List.range' 5600 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c766
