-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c640.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c640
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6802, 6868, 47), (6869, 6935, 46), (6936, 7005, 45), (7006, 7075, 44), (7076, 7147, 43), (7148, 7220, 42), (7221, 7294, 41), (7295, 7370, 40), (7371, 7447, 39), (7448, 7525, 38), (7526, 7603, 37), (7604, 7683, 36), (7684, 7763, 35), (7764, 7844, 34), (7845, 7926, 33), (7927, 8007, 32), (8008, 8089, 31), (8090, 8168, 30), (8169, 8190, 29), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c640
