-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c649.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c649
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(6192, 6192, 160), (6193, 6194, 159), (6195, 6196, 158), (6197, 6198, 157), (6199, 6200, 156), (6201, 6202, 155), (6203, 6204, 154), (6205, 6206, 153), (6207, 6208, 152), (6209, 6210, 151), (6211, 6212, 150), (6213, 6215, 149), (6216, 6217, 148), (6218, 6219, 147), (6220, 6222, 146), (6223, 6224, 145), (6225, 6226, 144), (6227, 6229, 143), (6230, 6231, 142), (6232, 6234, 141), (6235, 6237, 140), (6238, 6239, 139)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c649
