-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c887.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c887
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(4604, 4607, 157), (4608, 4611, 156), (4612, 4616, 155), (4617, 4620, 154), (4621, 4624, 153), (4625, 4629, 152), (4630, 4633, 151), (4634, 4638, 150), (4639, 4643, 149), (4644, 4648, 148), (4649, 4653, 147), (4654, 4658, 146), (4659, 4663, 145), (4664, 4668, 144), (4669, 4673, 143), (4674, 4679, 142), (4680, 4684, 141), (4685, 4690, 140), (4691, 4695, 139), (4696, 4701, 138), (4702, 4707, 137), (4708, 4713, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c887
