-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c95.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c95
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(7342, 7423, 47), (7424, 7506, 46), (7507, 7590, 45), (7591, 7674, 44), (7675, 7760, 43), (7761, 7845, 42), (7846, 7932, 41), (7933, 8018, 40), (8019, 8105, 39), (8106, 8181, 38), (8182, 8190, 37), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c95
