-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c565.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c565
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(4395, 4411, 113), (4412, 4427, 112), (4428, 4444, 111), (4445, 4461, 110), (4462, 4479, 109), (4480, 4496, 108), (4497, 4515, 107), (4516, 4533, 106), (4534, 4553, 105), (4554, 4572, 104), (4573, 4592, 103), (4593, 4612, 102), (4613, 4633, 101), (4634, 4654, 100), (4655, 4676, 99), (4677, 4698, 98), (4699, 4721, 97), (4722, 4744, 96), (4745, 4768, 95), (4769, 4793, 94), (4794, 4817, 93), (4818, 4843, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c565
