-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c578.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c578
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(14994, 15121, 47), (15122, 15250, 46), (15251, 15382, 45), (15383, 15516, 44), (15517, 15651, 43), (15652, 15789, 42), (15790, 15928, 41), (15929, 16068, 40), (16069, 16211, 39), (16212, 16348, 38), (16349, 16382, 37), (16383, 16383, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c578
