-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c206.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c206
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(8948, 9026, 91), (9027, 9107, 90), (9108, 9189, 89), (9190, 9272, 88), (9273, 9358, 87), (9359, 9445, 86), (9446, 9534, 85), (9535, 9624, 84), (9625, 9717, 83), (9718, 9811, 82), (9812, 9907, 81), (9908, 10005, 80), (10006, 10106, 79), (10107, 10208, 78), (10209, 10312, 77), (10313, 10418, 76), (10419, 10527, 75), (10528, 10638, 74), (10639, 10750, 73), (10751, 10866, 72), (10867, 10983, 71), (10984, 11103, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c206
