-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c677.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c677
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 9208, 201), (9209, 9216, 200), (9217, 9225, 199), (9226, 9233, 198), (9234, 9242, 197), (9243, 9251, 196), (9252, 9260, 195), (9261, 9269, 194), (9270, 9278, 193), (9279, 9288, 192), (9289, 9297, 191), (9298, 9307, 190), (9308, 9317, 189), (9318, 9327, 188), (9328, 9336, 187), (9337, 9347, 186), (9348, 9357, 185), (9358, 9367, 184), (9368, 9378, 183), (9379, 9389, 182), (9390, 9399, 181), (9400, 9410, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c677
