-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c222.Data6
import Solutions.SharpCertFast.P06P0r12c222.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c222
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d6_0_okE : (d6_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1532, 1542, 176), (1543, 1554, 175), (1555, 1566, 174), (1567, 1578, 173)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_0_k : d6_0.map (·.k) = List.range' 1536 32 := by decide +kernel
theorem d6_1_okE : (d6_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1567, 1578, 173), (1579, 1590, 172), (1591, 1603, 171)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_1_k : d6_1.map (·.k) = List.range' 1568 32 := by decide +kernel
theorem d6_2_okE : (d6_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1591, 1603, 171), (1604, 1615, 170), (1616, 1628, 169), (1629, 1641, 168)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_2_k : d6_2.map (·.k) = List.range' 1600 32 := by decide +kernel
theorem d6_3_okE : (d6_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1629, 1641, 168), (1642, 1654, 167), (1655, 1667, 166)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_3_k : d6_3.map (·.k) = List.range' 1632 32 := by decide +kernel
theorem d6_4_okE : (d6_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1655, 1667, 166), (1668, 1681, 165), (1682, 1694, 164), (1695, 1708, 163)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_4_k : d6_4.map (·.k) = List.range' 1664 32 := by decide +kernel
theorem d6_5_okE : (d6_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1695, 1708, 163), (1709, 1722, 162), (1723, 1736, 161)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_5_k : d6_5.map (·.k) = List.range' 1696 32 := by decide +kernel
theorem d6_6_okE : (d6_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1723, 1736, 161), (1737, 1751, 160), (1752, 1765, 159)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_6_k : d6_6.map (·.k) = List.range' 1728 32 := by decide +kernel
theorem d6_7_okE : (d6_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1752, 1765, 159), (1766, 1780, 158), (1781, 1795, 157)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_7_k : d6_7.map (·.k) = List.range' 1760 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c222
