-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c63.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c63
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(9140, 9232, 91), (9233, 9326, 90), (9327, 9422, 89), (9423, 9520, 88), (9521, 9619, 87), (9620, 9720, 86), (9721, 9823, 85), (9824, 9927, 84), (9928, 10034, 83), (10035, 10142, 82), (10143, 10252, 81), (10253, 10364, 80), (10365, 10477, 79), (10478, 10593, 78), (10594, 10711, 77), (10712, 10831, 76), (10832, 10953, 75), (10954, 11077, 74), (11078, 11203, 73), (11204, 11331, 72), (11332, 11461, 71), (11462, 11593, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c63
