-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c914.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c914
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(7233, 7233, 165), (7234, 7234, 164), (7235, 7236, 163), (7237, 7237, 162), (7238, 7238, 161), (7239, 7239, 160), (7240, 7241, 159), (7242, 7242, 158), (7243, 7243, 157), (7244, 7245, 156), (7246, 7246, 155), (7247, 7248, 154), (7249, 7249, 153), (7250, 7251, 152), (7252, 7252, 151), (7253, 7254, 150), (7255, 7255, 149), (7256, 7257, 148), (7258, 7259, 147), (7260, 7260, 146), (7261, 7262, 145), (7263, 7264, 144)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c914
