-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c511.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c511
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(6509, 6527, 69), (6528, 6546, 68), (6547, 6566, 67), (6567, 6587, 66), (6588, 6608, 65), (6609, 6629, 64), (6630, 6652, 63), (6653, 6675, 62), (6676, 6699, 61), (6700, 6724, 60), (6725, 6750, 59), (6751, 6776, 58), (6777, 6804, 57), (6805, 6832, 56), (6833, 6861, 55), (6862, 6892, 54), (6893, 6923, 53), (6924, 6955, 52), (6956, 6988, 51), (6989, 7023, 50), (7024, 7058, 49), (7059, 7095, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c511
