-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c527.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c527
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 3492, 201), (3493, 3497, 200), (3498, 3501, 199), (3502, 3505, 198), (3506, 3510, 197), (3511, 3514, 196), (3515, 3519, 195), (3520, 3524, 194), (3525, 3528, 193), (3529, 3533, 192), (3534, 3538, 191), (3539, 3543, 190), (3544, 3548, 189), (3549, 3553, 188), (3554, 3558, 187), (3559, 3564, 186), (3565, 3569, 185), (3570, 3574, 184), (3575, 3580, 183), (3581, 3585, 182), (3586, 3591, 181), (3592, 3597, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c527
