-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c664.Data30
import Solutions.SharpCertFast.P06P0r12c664.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c664
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d30_0_okE : (d30_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7679, 7690, 183), (7691, 7701, 182), (7702, 7712, 181)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d30_0_k : d30_0.map (·.k) = List.range' 7680 32 := by decide +kernel
theorem d30_1_okE : (d30_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7702, 7712, 181), (7713, 7724, 180), (7725, 7735, 179), (7736, 7747, 178)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d30_1_k : d30_1.map (·.k) = List.range' 7712 32 := by decide +kernel
theorem d30_2_okE : (d30_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7736, 7747, 178), (7748, 7759, 177), (7760, 7771, 176), (7772, 7784, 175)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d30_2_k : d30_2.map (·.k) = List.range' 7744 32 := by decide +kernel
theorem d30_3_okE : (d30_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7772, 7784, 175), (7785, 7796, 174), (7797, 7809, 173)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d30_3_k : d30_3.map (·.k) = List.range' 7776 32 := by decide +kernel
theorem d30_4_okE : (d30_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7797, 7809, 173), (7810, 7822, 172), (7823, 7835, 171), (7836, 7849, 170)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d30_4_k : d30_4.map (·.k) = List.range' 7808 32 := by decide +kernel
theorem d30_5_okE : (d30_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7836, 7849, 170), (7850, 7862, 169), (7863, 7876, 168)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d30_5_k : d30_5.map (·.k) = List.range' 7840 32 := by decide +kernel
theorem d30_6_okE : (d30_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7863, 7876, 168), (7877, 7890, 167), (7891, 7904, 166)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d30_6_k : d30_6.map (·.k) = List.range' 7872 32 := by decide +kernel
theorem d30_7_okE : (d30_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7891, 7904, 166), (7905, 7918, 165), (7919, 7933, 164), (7934, 7948, 163)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d30_7_k : d30_7.map (·.k) = List.range' 7904 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c664
