-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c903.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c903
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(6817, 6832, 67), (6833, 6849, 66), (6850, 6867, 65), (6868, 6885, 64), (6886, 6904, 63), (6905, 6924, 62), (6925, 6944, 61), (6945, 6964, 60), (6965, 6986, 59), (6987, 7008, 58), (7009, 7031, 57), (7032, 7055, 56), (7056, 7079, 55), (7080, 7104, 54), (7105, 7130, 53), (7131, 7157, 52), (7158, 7185, 51), (7186, 7213, 50), (7214, 7242, 49), (7243, 7273, 48), (7274, 7304, 47), (7305, 7336, 46)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c903
