-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c628.Data18
import Solutions.SharpCertFast.P06P0r12c628.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c628
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d18_0_okE : (d18_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4599, 4611, 116), (4612, 4623, 115), (4624, 4637, 114), (4638, 4650, 113)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_0_k : d18_0.map (·.k) = List.range' 4608 32 := by decide +kernel
theorem d18_1_okE : (d18_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4638, 4650, 113), (4651, 4664, 112), (4665, 4678, 111)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_1_k : d18_1.map (·.k) = List.range' 4640 32 := by decide +kernel
theorem d18_2_okE : (d18_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4665, 4678, 111), (4679, 4692, 110), (4693, 4707, 109)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_2_k : d18_2.map (·.k) = List.range' 4672 32 := by decide +kernel
theorem d18_3_okE : (d18_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4693, 4707, 109), (4708, 4721, 108), (4722, 4737, 107)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_3_k : d18_3.map (·.k) = List.range' 4704 32 := by decide +kernel
theorem d18_4_okE : (d18_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4722, 4737, 107), (4738, 4752, 106), (4753, 4768, 105)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_4_k : d18_4.map (·.k) = List.range' 4736 32 := by decide +kernel
theorem d18_5_okE : (d18_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4753, 4768, 105), (4769, 4785, 104), (4786, 4801, 103)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_5_k : d18_5.map (·.k) = List.range' 4768 32 := by decide +kernel
theorem d18_6_okE : (d18_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4786, 4801, 103), (4802, 4818, 102), (4819, 4836, 101)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_6_k : d18_6.map (·.k) = List.range' 4800 32 := by decide +kernel
theorem d18_7_okE : (d18_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4819, 4836, 101), (4837, 4854, 100), (4855, 4872, 99)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_7_k : d18_7.map (·.k) = List.range' 4832 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c628
