-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c602.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c602
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5469, 5516, 69), (5517, 5566, 68), (5567, 5617, 67), (5618, 5670, 66), (5671, 5723, 65), (5724, 5778, 64), (5779, 5834, 63), (5835, 5892, 62), (5893, 5951, 61), (5952, 6011, 60), (6012, 6072, 59), (6073, 6135, 58), (6136, 6200, 57), (6201, 6266, 56), (6267, 6333, 55), (6334, 6402, 54), (6403, 6473, 53), (6474, 6545, 52), (6546, 6618, 51), (6619, 6693, 50), (6694, 6769, 49), (6770, 6847, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c602
