-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c856.Data17
import Solutions.SharpCertFast.P06P0r12c856.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c856
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d17_0_okE : (d17_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 4431, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_0_k : d17_0.map (·.k) = List.range' 4352 32 := by decide +kernel
theorem d17_1_okE : (d17_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 4431, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_1_k : d17_1.map (·.k) = List.range' 4384 32 := by decide +kernel
theorem d17_2_okE : (d17_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 4431, 201), (4432, 4433, 200), (4434, 4436, 199), (4437, 4438, 198), (4439, 4441, 197), (4442, 4444, 196), (4445, 4447, 195)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_2_k : d17_2.map (·.k) = List.range' 4416 32 := by decide +kernel
theorem d17_3_okE : (d17_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4448, 4449, 194), (4450, 4452, 193), (4453, 4455, 192), (4456, 4458, 191), (4459, 4461, 190), (4462, 4464, 189), (4465, 4467, 188), (4468, 4470, 187), (4471, 4473, 186), (4474, 4476, 185), (4477, 4479, 184)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_3_k : d17_3.map (·.k) = List.range' 4448 32 := by decide +kernel
theorem d17_4_okE : (d17_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4480, 4483, 183), (4484, 4486, 182), (4487, 4489, 181), (4490, 4493, 180), (4494, 4496, 179), (4497, 4500, 178), (4501, 4503, 177), (4504, 4507, 176), (4508, 4511, 175)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_4_k : d17_4.map (·.k) = List.range' 4480 32 := by decide +kernel
theorem d17_5_okE : (d17_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4512, 4514, 174), (4515, 4518, 173), (4519, 4522, 172), (4523, 4526, 171), (4527, 4530, 170), (4531, 4534, 169), (4535, 4538, 168), (4539, 4542, 167), (4543, 4546, 166)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_5_k : d17_5.map (·.k) = List.range' 4512 32 := by decide +kernel
theorem d17_6_okE : (d17_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4543, 4546, 166), (4547, 4551, 165), (4552, 4555, 164), (4556, 4559, 163), (4560, 4564, 162), (4565, 4569, 161), (4570, 4573, 160), (4574, 4578, 159)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_6_k : d17_6.map (·.k) = List.range' 4544 32 := by decide +kernel
theorem d17_7_okE : (d17_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4574, 4578, 159), (4579, 4583, 158), (4584, 4588, 157), (4589, 4593, 156), (4594, 4598, 155), (4599, 4603, 154), (4604, 4608, 153)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_7_k : d17_7.map (·.k) = List.range' 4576 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c856
