-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c675.Data32
import Solutions.SharpCertFast.P06P0r12c675.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c675
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d32_0_okE : (d32_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8184, 8194, 182), (8195, 8205, 181), (8206, 8215, 180), (8216, 8227, 179)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d32_0_k : d32_0.map (·.k) = List.range' 8192 32 := by decide +kernel
theorem d32_1_okE : (d32_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8216, 8227, 179), (8228, 8238, 178), (8239, 8249, 177), (8250, 8261, 176)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d32_1_k : d32_1.map (·.k) = List.range' 8224 32 := by decide +kernel
theorem d32_2_okE : (d32_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8250, 8261, 176), (8262, 8273, 175), (8274, 8284, 174), (8285, 8297, 173)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d32_2_k : d32_2.map (·.k) = List.range' 8256 32 := by decide +kernel
theorem d32_3_okE : (d32_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8285, 8297, 173), (8298, 8309, 172), (8310, 8321, 171)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d32_3_k : d32_3.map (·.k) = List.range' 8288 32 := by decide +kernel
theorem d32_4_okE : (d32_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8310, 8321, 171), (8322, 8334, 170), (8335, 8347, 169), (8348, 8360, 168)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d32_4_k : d32_4.map (·.k) = List.range' 8320 32 := by decide +kernel
theorem d32_5_okE : (d32_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8348, 8360, 168), (8361, 8373, 167), (8374, 8386, 166)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d32_5_k : d32_5.map (·.k) = List.range' 8352 32 := by decide +kernel
theorem d32_6_okE : (d32_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8374, 8386, 166), (8387, 8400, 165), (8401, 8414, 164), (8415, 8428, 163)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d32_6_k : d32_6.map (·.k) = List.range' 8384 32 := by decide +kernel
theorem d32_7_okE : (d32_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8415, 8428, 163), (8429, 8442, 162), (8443, 8456, 161)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d32_7_k : d32_7.map (·.k) = List.range' 8416 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c675
