-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c161.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c161
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(10064, 10112, 113), (10113, 10161, 112), (10162, 10212, 111), (10213, 10263, 110), (10264, 10315, 109), (10316, 10367, 108), (10368, 10421, 107), (10422, 10475, 106), (10476, 10531, 105), (10532, 10587, 104), (10588, 10644, 103), (10645, 10702, 102), (10703, 10761, 101), (10762, 10821, 100), (10822, 10881, 99), (10882, 10943, 98), (10944, 11006, 97), (11007, 11069, 96), (11070, 11134, 95), (11135, 11200, 94), (11201, 11267, 93), (11268, 11335, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c161
