-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c24.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c24
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(6667, 6695, 157), (6696, 6725, 156), (6726, 6755, 155), (6756, 6785, 154), (6786, 6816, 153), (6817, 6847, 152), (6848, 6878, 151), (6879, 6910, 150), (6911, 6943, 149), (6944, 6976, 148), (6977, 7009, 147), (7010, 7043, 146), (7044, 7077, 145), (7078, 7112, 144), (7113, 7147, 143), (7148, 7183, 142), (7184, 7219, 141), (7220, 7256, 140), (7257, 7293, 139), (7294, 7331, 138), (7332, 7369, 137), (7370, 7408, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c24
