-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c24.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c24
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(7409, 7448, 135), (7449, 7488, 134), (7489, 7528, 133), (7529, 7570, 132), (7571, 7611, 131), (7612, 7654, 130), (7655, 7697, 129), (7698, 7741, 128), (7742, 7786, 127), (7787, 7831, 126), (7832, 7877, 125), (7878, 7923, 124), (7924, 7971, 123), (7972, 8019, 122), (8020, 8068, 121), (8069, 8117, 120), (8118, 8168, 119), (8169, 8219, 118), (8220, 8271, 117), (8272, 8324, 116), (8325, 8377, 115), (8378, 8432, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c24
