-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c381.Data15
import Solutions.SharpCertFast.P06P0r12c381.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c381
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d15_0_okE : (d15_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3825, 3854, 101), (3855, 3884, 100)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_0_k : d15_0.map (·.k) = List.range' 3840 32 := by decide +kernel
theorem d15_1_okE : (d15_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3855, 3884, 100), (3885, 3914, 99)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_1_k : d15_1.map (·.k) = List.range' 3872 32 := by decide +kernel
theorem d15_2_okE : (d15_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3885, 3914, 99), (3915, 3945, 98)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_2_k : d15_2.map (·.k) = List.range' 3904 32 := by decide +kernel
theorem d15_3_okE : (d15_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3915, 3945, 98), (3946, 3977, 97)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_3_k : d15_3.map (·.k) = List.range' 3936 32 := by decide +kernel
theorem d15_4_okE : (d15_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3946, 3977, 97), (3978, 4010, 96)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_4_k : d15_4.map (·.k) = List.range' 3968 32 := by decide +kernel
theorem d15_5_okE : (d15_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3978, 4010, 96), (4011, 4043, 95)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_5_k : d15_5.map (·.k) = List.range' 4000 32 := by decide +kernel
theorem d15_6_okE : (d15_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4011, 4043, 95), (4044, 4077, 94)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_6_k : d15_6.map (·.k) = List.range' 4032 32 := by decide +kernel
theorem d15_7_okE : (d15_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4044, 4077, 94), (4078, 4112, 93)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_7_k : d15_7.map (·.k) = List.range' 4064 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c381
