-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c380.Data9
import Solutions.SharpCertFast.P06P0r12c380.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c380
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d9_0_okE : (d9_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2439, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_0_k : d9_0.map (·.k) = List.range' 2304 32 := by decide +kernel
theorem d9_1_okE : (d9_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2439, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_1_k : d9_1.map (·.k) = List.range' 2336 32 := by decide +kernel
theorem d9_2_okE : (d9_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2439, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_2_k : d9_2.map (·.k) = List.range' 2368 32 := by decide +kernel
theorem d9_3_okE : (d9_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2439, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_3_k : d9_3.map (·.k) = List.range' 2400 32 := by decide +kernel
theorem d9_4_okE : (d9_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2439, 201), (2440, 2445, 200), (2446, 2451, 199), (2452, 2457, 198), (2458, 2463, 197)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_4_k : d9_4.map (·.k) = List.range' 2432 32 := by decide +kernel
theorem d9_5_okE : (d9_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2464, 2470, 196), (2471, 2476, 195), (2477, 2482, 194), (2483, 2489, 193), (2490, 2496, 192)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_5_k : d9_5.map (·.k) = List.range' 2464 32 := by decide +kernel
theorem d9_6_okE : (d9_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2490, 2496, 192), (2497, 2502, 191), (2503, 2509, 190), (2510, 2516, 189), (2517, 2523, 188), (2524, 2530, 187)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_6_k : d9_6.map (·.k) = List.range' 2496 32 := by decide +kernel
theorem d9_7_okE : (d9_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2524, 2530, 187), (2531, 2537, 186), (2538, 2544, 185), (2545, 2552, 184), (2553, 2559, 183)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_7_k : d9_7.map (·.k) = List.range' 2528 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c380
