-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c645.Data20
import Solutions.SharpCertFast.P06P0r12c645.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c645
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d20_0_okE : (d20_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5115, 5120, 139), (5121, 5125, 138), (5126, 5131, 137), (5132, 5138, 136), (5139, 5144, 135), (5145, 5150, 134), (5151, 5157, 133)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_0_k : d20_0.map (·.k) = List.range' 5120 32 := by decide +kernel
theorem d20_1_okE : (d20_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5151, 5157, 133), (5158, 5163, 132), (5164, 5170, 131), (5171, 5177, 130), (5178, 5184, 129)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_1_k : d20_1.map (·.k) = List.range' 5152 32 := by decide +kernel
theorem d20_2_okE : (d20_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5178, 5184, 129), (5185, 5191, 128), (5192, 5198, 127), (5199, 5206, 126), (5207, 5213, 125), (5214, 5221, 124)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_2_k : d20_2.map (·.k) = List.range' 5184 32 := by decide +kernel
theorem d20_3_okE : (d20_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5214, 5221, 124), (5222, 5229, 123), (5230, 5237, 122), (5238, 5246, 121), (5247, 5254, 120)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_3_k : d20_3.map (·.k) = List.range' 5216 32 := by decide +kernel
theorem d20_4_okE : (d20_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5247, 5254, 120), (5255, 5263, 119), (5264, 5271, 118), (5272, 5280, 117)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_4_k : d20_4.map (·.k) = List.range' 5248 32 := by decide +kernel
theorem d20_5_okE : (d20_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5272, 5280, 117), (5281, 5290, 116), (5291, 5299, 115), (5300, 5309, 114), (5310, 5318, 113)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_5_k : d20_5.map (·.k) = List.range' 5280 32 := by decide +kernel
theorem d20_6_okE : (d20_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5310, 5318, 113), (5319, 5328, 112), (5329, 5339, 111), (5340, 5349, 110)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_6_k : d20_6.map (·.k) = List.range' 5312 32 := by decide +kernel
theorem d20_7_okE : (d20_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5340, 5349, 110), (5350, 5360, 109), (5361, 5371, 108), (5372, 5382, 107)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_7_k : d20_7.map (·.k) = List.range' 5344 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c645
