-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c199.Data9
import Solutions.SharpCertFast.P06P0r12c199.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c199
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d9_0_okE : (d9_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2294, 2305, 157), (2306, 2318, 156), (2319, 2331, 155), (2332, 2345, 154)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_0_k : d9_0.map (·.k) = List.range' 2304 32 := by decide +kernel
theorem d9_1_okE : (d9_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2332, 2345, 154), (2346, 2358, 153), (2359, 2372, 152)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_1_k : d9_1.map (·.k) = List.range' 2336 32 := by decide +kernel
theorem d9_2_okE : (d9_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2359, 2372, 152), (2373, 2386, 151), (2387, 2400, 150)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_2_k : d9_2.map (·.k) = List.range' 2368 32 := by decide +kernel
theorem d9_3_okE : (d9_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2387, 2400, 150), (2401, 2414, 149), (2415, 2428, 148), (2429, 2443, 147)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_3_k : d9_3.map (·.k) = List.range' 2400 32 := by decide +kernel
theorem d9_4_okE : (d9_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2429, 2443, 147), (2444, 2458, 146), (2459, 2473, 145)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_4_k : d9_4.map (·.k) = List.range' 2432 32 := by decide +kernel
theorem d9_5_okE : (d9_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2459, 2473, 145), (2474, 2489, 144), (2490, 2505, 143)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_5_k : d9_5.map (·.k) = List.range' 2464 32 := by decide +kernel
theorem d9_6_okE : (d9_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2490, 2505, 143), (2506, 2521, 142), (2522, 2537, 141)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_6_k : d9_6.map (·.k) = List.range' 2496 32 := by decide +kernel
theorem d9_7_okE : (d9_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2522, 2537, 141), (2538, 2553, 140), (2554, 2570, 139)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_7_k : d9_7.map (·.k) = List.range' 2528 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c199
