-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c74.Data14
import Solutions.SharpCertFast.P06P0r12c74.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c74
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d14_0_okE : (d14_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3580, 3599, 131), (3600, 3619, 130)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_0_k : d14_0.map (·.k) = List.range' 3584 32 := by decide +kernel
theorem d14_1_okE : (d14_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3600, 3619, 130), (3620, 3640, 129), (3641, 3661, 128)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_1_k : d14_1.map (·.k) = List.range' 3616 32 := by decide +kernel
theorem d14_2_okE : (d14_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3641, 3661, 128), (3662, 3682, 127)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_2_k : d14_2.map (·.k) = List.range' 3648 32 := by decide +kernel
theorem d14_3_okE : (d14_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3662, 3682, 127), (3683, 3704, 126), (3705, 3726, 125)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_3_k : d14_3.map (·.k) = List.range' 3680 32 := by decide +kernel
theorem d14_4_okE : (d14_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3705, 3726, 125), (3727, 3748, 124)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_4_k : d14_4.map (·.k) = List.range' 3712 32 := by decide +kernel
theorem d14_5_okE : (d14_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3727, 3748, 124), (3749, 3771, 123), (3772, 3794, 122)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_5_k : d14_5.map (·.k) = List.range' 3744 32 := by decide +kernel
theorem d14_6_okE : (d14_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3772, 3794, 122), (3795, 3817, 121)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_6_k : d14_6.map (·.k) = List.range' 3776 32 := by decide +kernel
theorem d14_7_okE : (d14_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3795, 3817, 121), (3818, 3841, 120)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_7_k : d14_7.map (·.k) = List.range' 3808 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c74
