-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c481.Data11
import Solutions.SharpCertFast.P06P0r12c481.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c481
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d11_0_okE : (d11_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2814, 2819, 191), (2820, 2825, 190), (2826, 2831, 189), (2832, 2838, 188), (2839, 2844, 187), (2845, 2851, 186)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_0_k : d11_0.map (·.k) = List.range' 2816 32 := by decide +kernel
theorem d11_1_okE : (d11_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2845, 2851, 186), (2852, 2857, 185), (2858, 2864, 184), (2865, 2871, 183), (2872, 2878, 182), (2879, 2885, 181)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_1_k : d11_1.map (·.k) = List.range' 2848 32 := by decide +kernel
theorem d11_2_okE : (d11_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2879, 2885, 181), (2886, 2892, 180), (2893, 2899, 179), (2900, 2906, 178), (2907, 2914, 177)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_2_k : d11_2.map (·.k) = List.range' 2880 32 := by decide +kernel
theorem d11_3_okE : (d11_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2907, 2914, 177), (2915, 2921, 176), (2922, 2929, 175), (2930, 2936, 174), (2937, 2944, 173)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_3_k : d11_3.map (·.k) = List.range' 2912 32 := by decide +kernel
theorem d11_4_okE : (d11_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2937, 2944, 173), (2945, 2952, 172), (2953, 2960, 171), (2961, 2968, 170), (2969, 2977, 169)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_4_k : d11_4.map (·.k) = List.range' 2944 32 := by decide +kernel
theorem d11_5_okE : (d11_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2969, 2977, 169), (2978, 2985, 168), (2986, 2994, 167), (2995, 3002, 166), (3003, 3011, 165)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_5_k : d11_5.map (·.k) = List.range' 2976 32 := by decide +kernel
theorem d11_6_okE : (d11_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3003, 3011, 165), (3012, 3020, 164), (3021, 3029, 163), (3030, 3038, 162), (3039, 3048, 161)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_6_k : d11_6.map (·.k) = List.range' 3008 32 := by decide +kernel
theorem d11_7_okE : (d11_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3039, 3048, 161), (3049, 3057, 160), (3058, 3067, 159), (3068, 3076, 158)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_7_k : d11_7.map (·.k) = List.range' 3040 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c481
