-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c694.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c694
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(9282, 9292, 179), (9293, 9304, 178), (9305, 9316, 177), (9317, 9328, 176), (9329, 9340, 175), (9341, 9352, 174), (9353, 9365, 173), (9366, 9377, 172), (9378, 9390, 171), (9391, 9403, 170), (9404, 9417, 169), (9418, 9430, 168), (9431, 9444, 167), (9445, 9457, 166), (9458, 9471, 165), (9472, 9486, 164), (9487, 9500, 163), (9501, 9515, 162), (9516, 9530, 161), (9531, 9545, 160), (9546, 9560, 159), (9561, 9576, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c694
