-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c761.Data18
import Solutions.SharpCertFast.P06P0r12c761.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c761
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d18_0_okE : (d18_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4602, 4613, 122), (4614, 4624, 121), (4625, 4636, 120), (4637, 4648, 119)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_0_k : d18_0.map (·.k) = List.range' 4608 32 := by decide +kernel
theorem d18_1_okE : (d18_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4637, 4648, 119), (4649, 4661, 118), (4662, 4673, 117)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_1_k : d18_1.map (·.k) = List.range' 4640 32 := by decide +kernel
theorem d18_2_okE : (d18_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4662, 4673, 117), (4674, 4686, 116), (4687, 4699, 115), (4700, 4713, 114)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_2_k : d18_2.map (·.k) = List.range' 4672 32 := by decide +kernel
theorem d18_3_okE : (d18_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4700, 4713, 114), (4714, 4726, 113), (4727, 4740, 112)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_3_k : d18_3.map (·.k) = List.range' 4704 32 := by decide +kernel
theorem d18_4_okE : (d18_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4727, 4740, 112), (4741, 4755, 111), (4756, 4769, 110)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_4_k : d18_4.map (·.k) = List.range' 4736 32 := by decide +kernel
theorem d18_5_okE : (d18_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4756, 4769, 110), (4770, 4784, 109), (4785, 4799, 108)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_5_k : d18_5.map (·.k) = List.range' 4768 32 := by decide +kernel
theorem d18_6_okE : (d18_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4800, 4815, 107), (4816, 4831, 106)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_6_k : d18_6.map (·.k) = List.range' 4800 32 := by decide +kernel
theorem d18_7_okE : (d18_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4832, 4847, 105), (4848, 4864, 104)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_7_k : d18_7.map (·.k) = List.range' 4832 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c761
