-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c492.Data14
import Solutions.SharpCertFast.P06P0r12c492.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c492
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d14_0_okE : (d14_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3577, 3593, 123), (3594, 3610, 122), (3611, 3628, 121)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_0_k : d14_0.map (·.k) = List.range' 3584 32 := by decide +kernel
theorem d14_1_okE : (d14_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3611, 3628, 121), (3629, 3646, 120), (3647, 3664, 119)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_1_k : d14_1.map (·.k) = List.range' 3616 32 := by decide +kernel
theorem d14_2_okE : (d14_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3647, 3664, 119), (3665, 3682, 118)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_2_k : d14_2.map (·.k) = List.range' 3648 32 := by decide +kernel
theorem d14_3_okE : (d14_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3665, 3682, 118), (3683, 3701, 117), (3702, 3720, 116)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_3_k : d14_3.map (·.k) = List.range' 3680 32 := by decide +kernel
theorem d14_4_okE : (d14_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3702, 3720, 116), (3721, 3740, 115), (3741, 3760, 114)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_4_k : d14_4.map (·.k) = List.range' 3712 32 := by decide +kernel
theorem d14_5_okE : (d14_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3741, 3760, 114), (3761, 3781, 113)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_5_k : d14_5.map (·.k) = List.range' 3744 32 := by decide +kernel
theorem d14_6_okE : (d14_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3761, 3781, 113), (3782, 3801, 112), (3802, 3823, 111)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_6_k : d14_6.map (·.k) = List.range' 3776 32 := by decide +kernel
theorem d14_7_okE : (d14_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3802, 3823, 111), (3824, 3844, 110)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_7_k : d14_7.map (·.k) = List.range' 3808 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c492
