-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c378.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c378
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 5703, 201), (5704, 5704, 200), (5705, 5706, 199), (5707, 5707, 198), (5708, 5708, 197), (5709, 5709, 196), (5710, 5711, 195), (5712, 5712, 194), (5713, 5713, 193), (5714, 5715, 192), (5716, 5716, 191), (5717, 5718, 190), (5719, 5719, 189), (5720, 5720, 188), (5721, 5722, 187), (5723, 5723, 186), (5724, 5725, 185), (5726, 5727, 184), (5728, 5728, 183), (5729, 5730, 182), (5731, 5731, 181), (5732, 5733, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c378
