-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c488.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c488
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6824, 6908, 47), (6909, 6995, 46), (6996, 7083, 45), (7084, 7173, 44), (7174, 7264, 43), (7265, 7356, 42), (7357, 7449, 41), (7450, 7544, 40), (7545, 7639, 39), (7640, 7736, 38), (7737, 7833, 37), (7834, 7931, 36), (7932, 8030, 35), (8031, 8128, 34), (8129, 8190, 33), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c488
