-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c686.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c686
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5848, 5883, 69), (5884, 5920, 68), (5921, 5958, 67), (5959, 5997, 66), (5998, 6037, 65), (6038, 6078, 64), (6079, 6120, 63), (6121, 6164, 62), (6165, 6208, 61), (6209, 6254, 60), (6255, 6301, 59), (6302, 6349, 58), (6350, 6398, 57), (6399, 6449, 56), (6450, 6501, 55), (6502, 6554, 54), (6555, 6609, 53), (6610, 6665, 52), (6666, 6722, 51), (6723, 6781, 50), (6782, 6841, 49), (6842, 6902, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c686
