-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c663.Data46
import Solutions.SharpCertFast.P06P0r12c663.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c663
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d46_0_okE : (d46_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11746, 11783, 104), (11784, 11823, 103)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_0_k : d46_0.map (·.k) = List.range' 11776 32 := by decide +kernel
theorem d46_1_okE : (d46_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11784, 11823, 103), (11824, 11863, 102)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_1_k : d46_1.map (·.k) = List.range' 11808 32 := by decide +kernel
theorem d46_2_okE : (d46_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11824, 11863, 102), (11864, 11904, 101)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_2_k : d46_2.map (·.k) = List.range' 11840 32 := by decide +kernel
theorem d46_3_okE : (d46_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11864, 11904, 101)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_3_k : d46_3.map (·.k) = List.range' 11872 32 := by decide +kernel
theorem d46_4_okE : (d46_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11864, 11904, 101), (11905, 11945, 100)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_4_k : d46_4.map (·.k) = List.range' 11904 32 := by decide +kernel
theorem d46_5_okE : (d46_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11905, 11945, 100), (11946, 11987, 99)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_5_k : d46_5.map (·.k) = List.range' 11936 32 := by decide +kernel
theorem d46_6_okE : (d46_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11946, 11987, 99), (11988, 12030, 98)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_6_k : d46_6.map (·.k) = List.range' 11968 32 := by decide +kernel
theorem d46_7_okE : (d46_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11988, 12030, 98), (12031, 12074, 97)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_7_k : d46_7.map (·.k) = List.range' 12000 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c663
