-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c653.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c653
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5412, 5456, 69), (5457, 5502, 68), (5503, 5549, 67), (5550, 5597, 66), (5598, 5646, 65), (5647, 5697, 64), (5698, 5749, 63), (5750, 5802, 62), (5803, 5857, 61), (5858, 5913, 60), (5914, 5970, 59), (5971, 6029, 58), (6030, 6089, 57), (6090, 6151, 56), (6152, 6214, 55), (6215, 6279, 54), (6280, 6345, 53), (6346, 6412, 52), (6413, 6482, 51), (6483, 6553, 50), (6554, 6625, 49), (6626, 6699, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c653
