-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c107.Data10
import Solutions.SharpCertFast.P06P0r12c107.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c107
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d10_0_okE : (d10_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2703, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_0_k : d10_0.map (·.k) = List.range' 2560 32 := by decide +kernel
theorem d10_1_okE : (d10_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2703, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_1_k : d10_1.map (·.k) = List.range' 2592 32 := by decide +kernel
theorem d10_2_okE : (d10_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2703, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_2_k : d10_2.map (·.k) = List.range' 2624 32 := by decide +kernel
theorem d10_3_okE : (d10_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2703, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_3_k : d10_3.map (·.k) = List.range' 2656 32 := by decide +kernel
theorem d10_4_okE : (d10_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2703, 201), (2704, 2711, 200), (2712, 2719, 199)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_4_k : d10_4.map (·.k) = List.range' 2688 32 := by decide +kernel
theorem d10_5_okE : (d10_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2720, 2727, 198), (2728, 2735, 197), (2736, 2743, 196), (2744, 2751, 195)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_5_k : d10_5.map (·.k) = List.range' 2720 32 := by decide +kernel
theorem d10_6_okE : (d10_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2752, 2760, 194), (2761, 2768, 193), (2769, 2777, 192), (2778, 2785, 191)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_6_k : d10_6.map (·.k) = List.range' 2752 32 := by decide +kernel
theorem d10_7_okE : (d10_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2778, 2785, 191), (2786, 2794, 190), (2795, 2803, 189), (2804, 2812, 188), (2813, 2821, 187)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_7_k : d10_7.map (·.k) = List.range' 2784 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c107
