-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c250.Data13
import Solutions.SharpCertFast.P06P0r12c250.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c250
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d13_0_okE : (d13_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3316, 3332, 128), (3333, 3349, 127), (3350, 3366, 126)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_0_k : d13_0.map (·.k) = List.range' 3328 32 := by decide +kernel
theorem d13_1_okE : (d13_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3350, 3366, 126), (3367, 3384, 125), (3385, 3402, 124)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_1_k : d13_1.map (·.k) = List.range' 3360 32 := by decide +kernel
theorem d13_2_okE : (d13_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3385, 3402, 124), (3403, 3420, 123), (3421, 3439, 122)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_2_k : d13_2.map (·.k) = List.range' 3392 32 := by decide +kernel
theorem d13_3_okE : (d13_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3421, 3439, 122), (3440, 3458, 121)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_3_k : d13_3.map (·.k) = List.range' 3424 32 := by decide +kernel
theorem d13_4_okE : (d13_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3440, 3458, 121), (3459, 3477, 120), (3478, 3497, 119)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_4_k : d13_4.map (·.k) = List.range' 3456 32 := by decide +kernel
theorem d13_5_okE : (d13_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3478, 3497, 119), (3498, 3517, 118), (3518, 3537, 117)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_5_k : d13_5.map (·.k) = List.range' 3488 32 := by decide +kernel
theorem d13_6_okE : (d13_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3518, 3537, 117), (3538, 3558, 116)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_6_k : d13_6.map (·.k) = List.range' 3520 32 := by decide +kernel
theorem d13_7_okE : (d13_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3538, 3558, 116), (3559, 3579, 115), (3580, 3601, 114)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_7_k : d13_7.map (·.k) = List.range' 3552 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c250
