-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c414.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c414
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(4620, 4649, 91), (4650, 4679, 90), (4680, 4710, 89), (4711, 4741, 88), (4742, 4774, 87), (4775, 4807, 86), (4808, 4841, 85), (4842, 4875, 84), (4876, 4911, 83), (4912, 4947, 82), (4948, 4984, 81), (4985, 5022, 80), (5023, 5061, 79), (5062, 5101, 78), (5102, 5142, 77), (5143, 5184, 76), (5185, 5227, 75), (5228, 5271, 74), (5272, 5316, 73), (5317, 5362, 72), (5363, 5409, 71), (5410, 5457, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c414
