-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c883.Data20
import Solutions.SharpCertFast.P06P0r12c883.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c883
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d20_0_okE : (d20_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5118, 5120, 191), (5121, 5122, 190), (5123, 5124, 189), (5125, 5127, 188), (5128, 5130, 187), (5131, 5132, 186), (5133, 5135, 185), (5136, 5137, 184), (5138, 5140, 183), (5141, 5143, 182), (5144, 5146, 181), (5147, 5149, 180), (5150, 5151, 179)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_0_k : d20_0.map (·.k) = List.range' 5120 32 := by decide +kernel
theorem d20_1_okE : (d20_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5152, 5154, 178), (5155, 5157, 177), (5158, 5160, 176), (5161, 5163, 175), (5164, 5167, 174), (5168, 5170, 173), (5171, 5173, 172), (5174, 5176, 171), (5177, 5180, 170), (5181, 5183, 169)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_1_k : d20_1.map (·.k) = List.range' 5152 32 := by decide +kernel
theorem d20_2_okE : (d20_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5184, 5186, 168), (5187, 5190, 167), (5191, 5193, 166), (5194, 5197, 165), (5198, 5201, 164), (5202, 5204, 163), (5205, 5208, 162), (5209, 5212, 161), (5213, 5216, 160)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_2_k : d20_2.map (·.k) = List.range' 5184 32 := by decide +kernel
theorem d20_3_okE : (d20_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5213, 5216, 160), (5217, 5220, 159), (5221, 5224, 158), (5225, 5228, 157), (5229, 5232, 156), (5233, 5236, 155), (5237, 5241, 154), (5242, 5245, 153), (5246, 5249, 152)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_3_k : d20_3.map (·.k) = List.range' 5216 32 := by decide +kernel
theorem d20_4_okE : (d20_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5246, 5249, 152), (5250, 5254, 151), (5255, 5259, 150), (5260, 5263, 149), (5264, 5268, 148), (5269, 5273, 147), (5274, 5278, 146), (5279, 5283, 145)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_4_k : d20_4.map (·.k) = List.range' 5248 32 := by decide +kernel
theorem d20_5_okE : (d20_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5279, 5283, 145), (5284, 5288, 144), (5289, 5293, 143), (5294, 5299, 142), (5300, 5304, 141), (5305, 5310, 140), (5311, 5315, 139)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_5_k : d20_5.map (·.k) = List.range' 5280 32 := by decide +kernel
theorem d20_6_okE : (d20_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5311, 5315, 139), (5316, 5321, 138), (5322, 5327, 137), (5328, 5333, 136), (5334, 5339, 135), (5340, 5345, 134)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_6_k : d20_6.map (·.k) = List.range' 5312 32 := by decide +kernel
theorem d20_7_okE : (d20_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5340, 5345, 134), (5346, 5351, 133), (5352, 5358, 132), (5359, 5364, 131), (5365, 5371, 130), (5372, 5378, 129)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_7_k : d20_7.map (·.k) = List.range' 5344 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c883
