-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c66.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c66
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(15076, 15230, 47), (15231, 15386, 46), (15387, 15544, 45), (15545, 15703, 44), (15704, 15863, 43), (15864, 16024, 42), (16025, 16185, 41), (16186, 16341, 40), (16342, 16382, 39), (16383, 16383, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c66
