-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c631.Data17
import Solutions.SharpCertFast.P06P0r12c631.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c631
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d17_0_okE : (d17_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 4466, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_0_k : d17_0.map (·.k) = List.range' 4352 32 := by decide +kernel
theorem d17_1_okE : (d17_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 4466, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_1_k : d17_1.map (·.k) = List.range' 4384 32 := by decide +kernel
theorem d17_2_okE : (d17_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 4466, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_2_k : d17_2.map (·.k) = List.range' 4416 32 := by decide +kernel
theorem d17_3_okE : (d17_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 4466, 201), (4467, 4468, 200), (4469, 4470, 199), (4471, 4472, 198), (4473, 4475, 197), (4476, 4477, 196), (4478, 4479, 195)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_3_k : d17_3.map (·.k) = List.range' 4448 32 := by decide +kernel
theorem d17_4_okE : (d17_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4480, 4481, 194), (4482, 4484, 193), (4485, 4486, 192), (4487, 4489, 191), (4490, 4491, 190), (4492, 4494, 189), (4495, 4496, 188), (4497, 4499, 187), (4500, 4501, 186), (4502, 4504, 185), (4505, 4507, 184), (4508, 4510, 183), (4511, 4512, 182)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_4_k : d17_4.map (·.k) = List.range' 4480 32 := by decide +kernel
theorem d17_5_okE : (d17_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4511, 4512, 182), (4513, 4515, 181), (4516, 4518, 180), (4519, 4521, 179), (4522, 4524, 178), (4525, 4527, 177), (4528, 4530, 176), (4531, 4533, 175), (4534, 4536, 174), (4537, 4539, 173), (4540, 4543, 172)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_5_k : d17_5.map (·.k) = List.range' 4512 32 := by decide +kernel
theorem d17_6_okE : (d17_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4544, 4546, 171), (4547, 4549, 170), (4550, 4553, 169), (4554, 4556, 168), (4557, 4560, 167), (4561, 4563, 166), (4564, 4567, 165), (4568, 4571, 164), (4572, 4575, 163)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_6_k : d17_6.map (·.k) = List.range' 4544 32 := by decide +kernel
theorem d17_7_okE : (d17_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4576, 4578, 162), (4579, 4582, 161), (4583, 4586, 160), (4587, 4590, 159), (4591, 4594, 158), (4595, 4599, 157), (4600, 4603, 156), (4604, 4607, 155)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_7_k : d17_7.map (·.k) = List.range' 4576 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c631
