-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c56.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c56
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(11580, 11715, 69), (11716, 11852, 68), (11853, 11992, 67), (11993, 12134, 66), (12135, 12279, 65), (12280, 12426, 64), (12427, 12575, 63), (12576, 12726, 62), (12727, 12880, 61), (12881, 13036, 60), (13037, 13194, 59), (13195, 13355, 58), (13356, 13518, 57), (13519, 13683, 56), (13684, 13851, 55), (13852, 14021, 54), (14022, 14193, 53), (14194, 14367, 52), (14368, 14543, 51), (14544, 14722, 50), (14723, 14902, 49), (14903, 15084, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c56
