-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c328.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c328
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5071, 5125, 69), (5126, 5182, 68), (5183, 5240, 67), (5241, 5300, 66), (5301, 5361, 65), (5362, 5424, 64), (5425, 5487, 63), (5488, 5553, 62), (5554, 5620, 61), (5621, 5689, 60), (5690, 5759, 59), (5760, 5830, 58), (5831, 5904, 57), (5905, 5979, 56), (5980, 6056, 55), (6057, 6134, 54), (6135, 6214, 53), (6215, 6296, 52), (6297, 6379, 51), (6380, 6464, 50), (6465, 6551, 49), (6552, 6639, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c328
