-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c462.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c462
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(3513, 3518, 179), (3519, 3524, 178), (3525, 3530, 177), (3531, 3537, 176), (3538, 3543, 175), (3544, 3549, 174), (3550, 3556, 173), (3557, 3563, 172), (3564, 3569, 171), (3570, 3576, 170), (3577, 3583, 169), (3584, 3590, 168), (3591, 3597, 167), (3598, 3605, 166), (3606, 3612, 165), (3613, 3619, 164), (3620, 3627, 163), (3628, 3635, 162), (3636, 3642, 161), (3643, 3650, 160), (3651, 3659, 159), (3660, 3667, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c462
