-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c301.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c301
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(2098, 2105, 179), (2106, 2114, 178), (2115, 2124, 177), (2125, 2133, 176), (2134, 2142, 175), (2143, 2152, 174), (2153, 2161, 173), (2162, 2171, 172), (2172, 2181, 171), (2182, 2191, 170), (2192, 2201, 169), (2202, 2212, 168), (2213, 2222, 167), (2223, 2233, 166), (2234, 2244, 165), (2245, 2255, 164), (2256, 2266, 163), (2267, 2277, 162), (2278, 2288, 161), (2289, 2300, 160), (2301, 2312, 159), (2313, 2324, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c301
