-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c475.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c475
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(6158, 6167, 91), (6168, 6178, 90), (6179, 6188, 89), (6189, 6199, 88), (6200, 6210, 87), (6211, 6221, 86), (6222, 6233, 85), (6234, 6245, 84), (6246, 6258, 83), (6259, 6271, 82), (6272, 6284, 81), (6285, 6297, 80), (6298, 6311, 79), (6312, 6326, 78), (6327, 6341, 77), (6342, 6356, 76), (6357, 6372, 75), (6373, 6388, 74), (6389, 6405, 73), (6406, 6423, 72), (6424, 6440, 71), (6441, 6459, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c475
