-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c375.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c375
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6791, 6873, 47), (6874, 6957, 46), (6958, 7043, 45), (7044, 7130, 44), (7131, 7219, 43), (7220, 7308, 42), (7309, 7400, 41), (7401, 7492, 40), (7493, 7585, 39), (7586, 7679, 38), (7680, 7774, 37), (7775, 7870, 36), (7871, 7967, 35), (7968, 8064, 34), (8065, 8159, 33), (8160, 8190, 32), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c375
