-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c375.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c375
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(3417, 3424, 157), (3425, 3433, 156), (3434, 3442, 155), (3443, 3451, 154), (3452, 3460, 153), (3461, 3469, 152), (3470, 3479, 151), (3480, 3488, 150), (3489, 3498, 149), (3499, 3508, 148), (3509, 3518, 147), (3519, 3529, 146), (3530, 3539, 145), (3540, 3550, 144), (3551, 3560, 143), (3561, 3571, 142), (3572, 3583, 141), (3584, 3594, 140), (3595, 3606, 139), (3607, 3617, 138), (3618, 3629, 137), (3630, 3642, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c375
