-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c311.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c311
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(2646, 2656, 157), (2657, 2667, 156), (2668, 2679, 155), (2680, 2691, 154), (2692, 2702, 153), (2703, 2714, 152), (2715, 2727, 151), (2728, 2739, 150), (2740, 2752, 149), (2753, 2764, 148), (2765, 2777, 147), (2778, 2791, 146), (2792, 2804, 145), (2805, 2818, 144), (2819, 2832, 143), (2833, 2846, 142), (2847, 2860, 141), (2861, 2875, 140), (2876, 2890, 139), (2891, 2905, 138), (2906, 2920, 137), (2921, 2936, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c311
