-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c771.Data23
import Solutions.SharpCertFast.P06P0r12c771.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c771
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d23_0_okE : (d23_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5886, 5889, 133), (5890, 5893, 132), (5894, 5898, 131), (5899, 5902, 130), (5903, 5907, 129), (5908, 5911, 128), (5912, 5916, 127), (5917, 5921, 126)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d23_0_k : d23_0.map (·.k) = List.range' 5888 32 := by decide +kernel
theorem d23_1_okE : (d23_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5917, 5921, 126), (5922, 5926, 125), (5927, 5931, 124), (5932, 5936, 123), (5937, 5941, 122), (5942, 5947, 121), (5948, 5952, 120)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d23_1_k : d23_1.map (·.k) = List.range' 5920 32 := by decide +kernel
theorem d23_2_okE : (d23_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5948, 5952, 120), (5953, 5958, 119), (5959, 5964, 118), (5965, 5970, 117), (5971, 5976, 116), (5977, 5982, 115), (5983, 5988, 114)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d23_2_k : d23_2.map (·.k) = List.range' 5952 32 := by decide +kernel
theorem d23_3_okE : (d23_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5983, 5988, 114), (5989, 5995, 113), (5996, 6001, 112), (6002, 6008, 111), (6009, 6015, 110)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d23_3_k : d23_3.map (·.k) = List.range' 5984 32 := by decide +kernel
theorem d23_4_okE : (d23_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6016, 6022, 109), (6023, 6029, 108), (6030, 6037, 107), (6038, 6044, 106), (6045, 6052, 105)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d23_4_k : d23_4.map (·.k) = List.range' 6016 32 := by decide +kernel
theorem d23_5_okE : (d23_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6045, 6052, 105), (6053, 6060, 104), (6061, 6068, 103), (6069, 6076, 102), (6077, 6085, 101)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d23_5_k : d23_5.map (·.k) = List.range' 6048 32 := by decide +kernel
theorem d23_6_okE : (d23_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6077, 6085, 101), (6086, 6094, 100), (6095, 6103, 99), (6104, 6112, 98)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d23_6_k : d23_6.map (·.k) = List.range' 6080 32 := by decide +kernel
theorem d23_7_okE : (d23_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6104, 6112, 98), (6113, 6121, 97), (6122, 6131, 96), (6132, 6141, 95), (6142, 6151, 94)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d23_7_k : d23_7.map (·.k) = List.range' 6112 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c771
