-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c668.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c668
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6923, 6996, 47), (6997, 7072, 46), (7073, 7148, 45), (7149, 7227, 44), (7228, 7306, 43), (7307, 7386, 42), (7387, 7468, 41), (7469, 7551, 40), (7552, 7635, 39), (7636, 7720, 38), (7721, 7805, 37), (7806, 7892, 36), (7893, 7978, 35), (7979, 8066, 34), (8067, 8153, 33), (8154, 8190, 32), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c668
