-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c205.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c205
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 2306, 201), (2307, 2313, 200), (2314, 2320, 199), (2321, 2328, 198), (2329, 2335, 197), (2336, 2343, 196), (2344, 2350, 195), (2351, 2358, 194), (2359, 2366, 193), (2367, 2374, 192), (2375, 2382, 191), (2383, 2390, 190), (2391, 2399, 189), (2400, 2407, 188), (2408, 2415, 187), (2416, 2424, 186), (2425, 2433, 185), (2434, 2441, 184), (2442, 2450, 183), (2451, 2459, 182), (2460, 2469, 181), (2470, 2478, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c205
