-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c652.Data35
import Solutions.SharpCertFast.P06P0r12c652.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c652
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d35_0_okE : (d35_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 9093, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d35_0_k : d35_0.map (·.k) = List.range' 8960 32 := by decide +kernel
theorem d35_1_okE : (d35_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 9093, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d35_1_k : d35_1.map (·.k) = List.range' 8992 32 := by decide +kernel
theorem d35_2_okE : (d35_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 9093, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d35_2_k : d35_2.map (·.k) = List.range' 9024 32 := by decide +kernel
theorem d35_3_okE : (d35_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 9093, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d35_3_k : d35_3.map (·.k) = List.range' 9056 32 := by decide +kernel
theorem d35_4_okE : (d35_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 9093, 201), (9094, 9102, 200), (9103, 9111, 199), (9112, 9120, 198)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d35_4_k : d35_4.map (·.k) = List.range' 9088 32 := by decide +kernel
theorem d35_5_okE : (d35_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9112, 9120, 198), (9121, 9129, 197), (9130, 9138, 196), (9139, 9147, 195), (9148, 9156, 194)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d35_5_k : d35_5.map (·.k) = List.range' 9120 32 := by decide +kernel
theorem d35_6_okE : (d35_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9148, 9156, 194), (9157, 9166, 193), (9167, 9175, 192), (9176, 9185, 191)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d35_6_k : d35_6.map (·.k) = List.range' 9152 32 := by decide +kernel
theorem d35_7_okE : (d35_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9176, 9185, 191), (9186, 9195, 190), (9196, 9205, 189), (9206, 9215, 188)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d35_7_k : d35_7.map (·.k) = List.range' 9184 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c652
