-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c395.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c395
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6913, 6999, 47), (7000, 7088, 46), (7089, 7178, 45), (7179, 7270, 44), (7271, 7363, 43), (7364, 7457, 42), (7458, 7552, 41), (7553, 7648, 40), (7649, 7746, 39), (7747, 7844, 38), (7845, 7943, 37), (7944, 8042, 36), (8043, 8142, 35), (8143, 8190, 34), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c395
