-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c395.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c395
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(4404, 4437, 91), (4438, 4472, 90), (4473, 4508, 89), (4509, 4545, 88), (4546, 4582, 87), (4583, 4620, 86), (4621, 4659, 85), (4660, 4699, 84), (4700, 4740, 83), (4741, 4781, 82), (4782, 4824, 81), (4825, 4868, 80), (4869, 4912, 79), (4913, 4958, 78), (4959, 5004, 77), (5005, 5052, 76), (5053, 5101, 75), (5102, 5151, 74), (5152, 5202, 73), (5203, 5254, 72), (5255, 5307, 71), (5308, 5361, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c395
