-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c463.Data13
import Solutions.SharpCertFast.P06P0r12c463.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c463
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d13_0_okE : (d13_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3434, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_0_k : d13_0.map (·.k) = List.range' 3328 32 := by decide +kernel
theorem d13_1_okE : (d13_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3434, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_1_k : d13_1.map (·.k) = List.range' 3360 32 := by decide +kernel
theorem d13_2_okE : (d13_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3434, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_2_k : d13_2.map (·.k) = List.range' 3392 32 := by decide +kernel
theorem d13_3_okE : (d13_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3434, 201), (3435, 3439, 200), (3440, 3444, 199), (3445, 3448, 198), (3449, 3453, 197), (3454, 3458, 196)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_3_k : d13_3.map (·.k) = List.range' 3424 32 := by decide +kernel
theorem d13_4_okE : (d13_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3454, 3458, 196), (3459, 3462, 195), (3463, 3467, 194), (3468, 3472, 193), (3473, 3477, 192), (3478, 3482, 191), (3483, 3487, 190)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_4_k : d13_4.map (·.k) = List.range' 3456 32 := by decide +kernel
theorem d13_5_okE : (d13_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3488, 3493, 189), (3494, 3498, 188), (3499, 3503, 187), (3504, 3509, 186), (3510, 3514, 185), (3515, 3520, 184)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_5_k : d13_5.map (·.k) = List.range' 3488 32 := by decide +kernel
theorem d13_6_okE : (d13_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3515, 3520, 184), (3521, 3525, 183), (3526, 3531, 182), (3532, 3537, 181), (3538, 3543, 180), (3544, 3549, 179), (3550, 3555, 178)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_6_k : d13_6.map (·.k) = List.range' 3520 32 := by decide +kernel
theorem d13_7_okE : (d13_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3550, 3555, 178), (3556, 3561, 177), (3562, 3567, 176), (3568, 3574, 175), (3575, 3580, 174), (3581, 3587, 173)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_7_k : d13_7.map (·.k) = List.range' 3552 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c463
