-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c746.Data25
import Solutions.SharpCertFast.P06P0r12c746.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c746
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d25_0_okE : (d25_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6387, 6405, 73), (6406, 6424, 72), (6425, 6444, 71)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_0_k : d25_0.map (·.k) = List.range' 6400 32 := by decide +kernel
theorem d25_1_okE : (d25_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6425, 6444, 71), (6445, 6465, 70)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_1_k : d25_1.map (·.k) = List.range' 6432 32 := by decide +kernel
theorem d25_2_okE : (d25_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6445, 6465, 70), (6466, 6486, 69), (6487, 6508, 68)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_2_k : d25_2.map (·.k) = List.range' 6464 32 := by decide +kernel
theorem d25_3_okE : (d25_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6487, 6508, 68), (6509, 6531, 67)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_3_k : d25_3.map (·.k) = List.range' 6496 32 := by decide +kernel
theorem d25_4_okE : (d25_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6509, 6531, 67), (6532, 6554, 66), (6555, 6578, 65)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_4_k : d25_4.map (·.k) = List.range' 6528 32 := by decide +kernel
theorem d25_5_okE : (d25_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6555, 6578, 65), (6579, 6603, 64)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_5_k : d25_5.map (·.k) = List.range' 6560 32 := by decide +kernel
theorem d25_6_okE : (d25_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6579, 6603, 64), (6604, 6629, 63)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_6_k : d25_6.map (·.k) = List.range' 6592 32 := by decide +kernel
theorem d25_7_okE : (d25_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6604, 6629, 63), (6630, 6655, 62)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_7_k : d25_7.map (·.k) = List.range' 6624 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c746
