-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c137.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c137
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(4694, 4713, 179), (4714, 4732, 178), (4733, 4752, 177), (4753, 4773, 176), (4774, 4793, 175), (4794, 4814, 174), (4815, 4835, 173), (4836, 4856, 172), (4857, 4878, 171), (4879, 4900, 170), (4901, 4922, 169), (4923, 4945, 168), (4946, 4968, 167), (4969, 4991, 166), (4992, 5015, 165), (5016, 5039, 164), (5040, 5063, 163), (5064, 5088, 162), (5089, 5113, 161), (5114, 5138, 160), (5139, 5164, 159), (5165, 5190, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c137
