-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c775.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c775
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(5242, 5255, 113), (5256, 5269, 112), (5270, 5284, 111), (5285, 5299, 110), (5300, 5314, 109), (5315, 5330, 108), (5331, 5346, 107), (5347, 5362, 106), (5363, 5379, 105), (5380, 5396, 104), (5397, 5413, 103), (5414, 5430, 102), (5431, 5449, 101), (5450, 5467, 100), (5468, 5486, 99), (5487, 5505, 98), (5506, 5524, 97), (5525, 5544, 96), (5545, 5565, 95), (5566, 5586, 94), (5587, 5607, 93), (5608, 5629, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c775
