-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c11.Data62
import Solutions.SharpCertFast.P06P0r12c11.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c11
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d62_0_okE : (d62_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(15748, 15912, 43)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d62_0_k : d62_0.map (·.k) = List.range' 15872 32 := by decide +kernel
theorem d62_1_okE : (d62_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(15748, 15912, 43), (15913, 16078, 42)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d62_1_k : d62_1.map (·.k) = List.range' 15904 32 := by decide +kernel
theorem d62_2_okE : (d62_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(15913, 16078, 42)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d62_2_k : d62_2.map (·.k) = List.range' 15936 32 := by decide +kernel
theorem d62_3_okE : (d62_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(15913, 16078, 42)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d62_3_k : d62_3.map (·.k) = List.range' 15968 32 := by decide +kernel
theorem d62_4_okE : (d62_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(15913, 16078, 42)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d62_4_k : d62_4.map (·.k) = List.range' 16000 32 := by decide +kernel
theorem d62_5_okE : (d62_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(15913, 16078, 42)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d62_5_k : d62_5.map (·.k) = List.range' 16032 32 := by decide +kernel
theorem d62_6_okE : (d62_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(15913, 16078, 42), (16079, 16245, 41)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d62_6_k : d62_6.map (·.k) = List.range' 16064 32 := by decide +kernel
theorem d62_7_okE : (d62_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(16079, 16245, 41)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d62_7_k : d62_7.map (·.k) = List.range' 16096 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c11
