-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c459.Data11
import Solutions.SharpCertFast.P06P0r12c459.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c459
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d11_0_okE : (d11_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2960, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_0_k : d11_0.map (·.k) = List.range' 2816 32 := by decide +kernel
theorem d11_1_okE : (d11_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2960, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_1_k : d11_1.map (·.k) = List.range' 2848 32 := by decide +kernel
theorem d11_2_okE : (d11_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2960, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_2_k : d11_2.map (·.k) = List.range' 2880 32 := by decide +kernel
theorem d11_3_okE : (d11_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2960, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_3_k : d11_3.map (·.k) = List.range' 2912 32 := by decide +kernel
theorem d11_4_okE : (d11_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2960, 201), (2961, 2965, 200), (2966, 2970, 199), (2971, 2975, 198)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_4_k : d11_4.map (·.k) = List.range' 2944 32 := by decide +kernel
theorem d11_5_okE : (d11_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2976, 2980, 197), (2981, 2985, 196), (2986, 2991, 195), (2992, 2996, 194), (2997, 3001, 193), (3002, 3007, 192)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_5_k : d11_5.map (·.k) = List.range' 2976 32 := by decide +kernel
theorem d11_6_okE : (d11_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3008, 3012, 191), (3013, 3018, 190), (3019, 3024, 189), (3025, 3029, 188), (3030, 3035, 187), (3036, 3041, 186)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_6_k : d11_6.map (·.k) = List.range' 3008 32 := by decide +kernel
theorem d11_7_okE : (d11_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3036, 3041, 186), (3042, 3047, 185), (3048, 3053, 184), (3054, 3059, 183), (3060, 3066, 182), (3067, 3072, 181)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_7_k : d11_7.map (·.k) = List.range' 3040 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c459
