-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c459.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c459
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6768, 6852, 47), (6853, 6939, 46), (6940, 7027, 45), (7028, 7117, 44), (7118, 7208, 43), (7209, 7300, 42), (7301, 7393, 41), (7394, 7488, 40), (7489, 7583, 39), (7584, 7680, 38), (7681, 7777, 37), (7778, 7875, 36), (7876, 7974, 35), (7975, 8073, 34), (8074, 8167, 33), (8168, 8190, 32), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c459
