-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c459.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c459
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(3248, 3256, 157), (3257, 3266, 156), (3267, 3275, 155), (3276, 3284, 154), (3285, 3294, 153), (3295, 3304, 152), (3305, 3314, 151), (3315, 3324, 150), (3325, 3335, 149), (3336, 3345, 148), (3346, 3356, 147), (3357, 3367, 146), (3368, 3378, 145), (3379, 3389, 144), (3390, 3400, 143), (3401, 3412, 142), (3413, 3424, 141), (3425, 3436, 140), (3437, 3448, 139), (3449, 3461, 138), (3462, 3473, 137), (3474, 3486, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c459
