-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c507.Data14
import Solutions.SharpCertFast.P06P0r12c507.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c507
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d14_0_okE : (d14_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3623, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_0_k : d14_0.map (·.k) = List.range' 3584 32 := by decide +kernel
theorem d14_1_okE : (d14_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3623, 201), (3624, 3627, 200), (3628, 3631, 199), (3632, 3635, 198), (3636, 3639, 197), (3640, 3644, 196), (3645, 3648, 195)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_1_k : d14_1.map (·.k) = List.range' 3616 32 := by decide +kernel
theorem d14_2_okE : (d14_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3645, 3648, 195), (3649, 3652, 194), (3653, 3657, 193), (3658, 3661, 192), (3662, 3666, 191), (3667, 3670, 190), (3671, 3675, 189), (3676, 3680, 188)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_2_k : d14_2.map (·.k) = List.range' 3648 32 := by decide +kernel
theorem d14_3_okE : (d14_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3676, 3680, 188), (3681, 3685, 187), (3686, 3689, 186), (3690, 3694, 185), (3695, 3699, 184), (3700, 3705, 183), (3706, 3710, 182), (3711, 3715, 181)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_3_k : d14_3.map (·.k) = List.range' 3680 32 := by decide +kernel
theorem d14_4_okE : (d14_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3711, 3715, 181), (3716, 3720, 180), (3721, 3726, 179), (3727, 3731, 178), (3732, 3737, 177), (3738, 3742, 176), (3743, 3748, 175)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_4_k : d14_4.map (·.k) = List.range' 3712 32 := by decide +kernel
theorem d14_5_okE : (d14_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3743, 3748, 175), (3749, 3754, 174), (3755, 3760, 173), (3761, 3766, 172), (3767, 3772, 171), (3773, 3778, 170)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_5_k : d14_5.map (·.k) = List.range' 3744 32 := by decide +kernel
theorem d14_6_okE : (d14_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3773, 3778, 170), (3779, 3784, 169), (3785, 3790, 168), (3791, 3797, 167), (3798, 3803, 166), (3804, 3810, 165)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_6_k : d14_6.map (·.k) = List.range' 3776 32 := by decide +kernel
theorem d14_7_okE : (d14_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3804, 3810, 165), (3811, 3817, 164), (3818, 3824, 163), (3825, 3831, 162), (3832, 3838, 161), (3839, 3845, 160)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_7_k : d14_7.map (·.k) = List.range' 3808 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c507
