-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c879.Data24
import Solutions.SharpCertFast.P06P0r12c879.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c879
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d24_0_okE : (d24_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6132, 6144, 86), (6145, 6158, 85), (6159, 6172, 84), (6173, 6186, 83)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_0_k : d24_0.map (·.k) = List.range' 6144 32 := by decide +kernel
theorem d24_1_okE : (d24_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6173, 6186, 83), (6187, 6201, 82), (6202, 6216, 81)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_1_k : d24_1.map (·.k) = List.range' 6176 32 := by decide +kernel
theorem d24_2_okE : (d24_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6202, 6216, 81), (6217, 6231, 80), (6232, 6247, 79)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_2_k : d24_2.map (·.k) = List.range' 6208 32 := by decide +kernel
theorem d24_3_okE : (d24_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6232, 6247, 79), (6248, 6263, 78), (6264, 6280, 77)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_3_k : d24_3.map (·.k) = List.range' 6240 32 := by decide +kernel
theorem d24_4_okE : (d24_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6264, 6280, 77), (6281, 6298, 76), (6299, 6316, 75)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_4_k : d24_4.map (·.k) = List.range' 6272 32 := by decide +kernel
theorem d24_5_okE : (d24_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6299, 6316, 75), (6317, 6334, 74), (6335, 6353, 73)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_5_k : d24_5.map (·.k) = List.range' 6304 32 := by decide +kernel
theorem d24_6_okE : (d24_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6335, 6353, 73), (6354, 6373, 72)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_6_k : d24_6.map (·.k) = List.range' 6336 32 := by decide +kernel
theorem d24_7_okE : (d24_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6354, 6373, 72), (6374, 6393, 71), (6394, 6414, 70)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_7_k : d24_7.map (·.k) = List.range' 6368 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c879
