-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c184.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c184
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 2191, 201), (2192, 2197, 200), (2198, 2204, 199), (2205, 2210, 198), (2211, 2217, 197), (2218, 2224, 196), (2225, 2231, 195), (2232, 2238, 194), (2239, 2245, 193), (2246, 2252, 192), (2253, 2259, 191), (2260, 2267, 190), (2268, 2274, 189), (2275, 2282, 188), (2283, 2289, 187), (2290, 2297, 186), (2298, 2305, 185), (2306, 2313, 184), (2314, 2321, 183), (2322, 2329, 182), (2330, 2338, 181), (2339, 2346, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c184
