-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c146.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c146
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(1362, 1372, 179), (1373, 1384, 178), (1385, 1395, 177), (1396, 1407, 176), (1408, 1419, 175), (1420, 1432, 174), (1433, 1444, 173), (1445, 1457, 172), (1458, 1469, 171), (1470, 1482, 170), (1483, 1495, 169), (1496, 1509, 168), (1510, 1522, 167), (1523, 1536, 166), (1537, 1550, 165), (1551, 1564, 164), (1565, 1578, 163), (1579, 1592, 162), (1593, 1607, 161), (1608, 1622, 160), (1623, 1637, 159), (1638, 1652, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c146
