-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c189.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c189
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(2559, 2589, 113), (2590, 2621, 112), (2622, 2653, 111), (2654, 2686, 110), (2687, 2719, 109), (2720, 2753, 108), (2754, 2788, 107), (2789, 2823, 106), (2824, 2860, 105), (2861, 2896, 104), (2897, 2934, 103), (2935, 2972, 102), (2973, 3011, 101), (3012, 3051, 100), (3052, 3091, 99), (3092, 3132, 98), (3133, 3174, 97), (3175, 3217, 96), (3218, 3261, 95), (3262, 3306, 94), (3307, 3351, 93), (3352, 3398, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c189
