-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c452.Data11
import Solutions.SharpCertFast.P06P0r12c452.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c452
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d11_0_okE : (d11_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2854, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_0_k : d11_0.map (·.k) = List.range' 2816 32 := by decide +kernel
theorem d11_1_okE : (d11_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2854, 201), (2855, 2859, 200), (2860, 2864, 199), (2865, 2870, 198), (2871, 2875, 197), (2876, 2881, 196)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_1_k : d11_1.map (·.k) = List.range' 2848 32 := by decide +kernel
theorem d11_2_okE : (d11_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2876, 2881, 196), (2882, 2886, 195), (2887, 2892, 194), (2893, 2897, 193), (2898, 2903, 192), (2904, 2909, 191), (2910, 2915, 190)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_2_k : d11_2.map (·.k) = List.range' 2880 32 := by decide +kernel
theorem d11_3_okE : (d11_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2910, 2915, 190), (2916, 2921, 189), (2922, 2927, 188), (2928, 2933, 187), (2934, 2940, 186), (2941, 2946, 185)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_3_k : d11_3.map (·.k) = List.range' 2912 32 := by decide +kernel
theorem d11_4_okE : (d11_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2941, 2946, 185), (2947, 2952, 184), (2953, 2959, 183), (2960, 2966, 182), (2967, 2972, 181), (2973, 2979, 180)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_4_k : d11_4.map (·.k) = List.range' 2944 32 := by decide +kernel
theorem d11_5_okE : (d11_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2973, 2979, 180), (2980, 2986, 179), (2987, 2993, 178), (2994, 3000, 177), (3001, 3007, 176)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_5_k : d11_5.map (·.k) = List.range' 2976 32 := by decide +kernel
theorem d11_6_okE : (d11_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3008, 3015, 175), (3016, 3022, 174), (3023, 3029, 173), (3030, 3037, 172), (3038, 3045, 171)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_6_k : d11_6.map (·.k) = List.range' 3008 32 := by decide +kernel
theorem d11_7_okE : (d11_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3038, 3045, 171), (3046, 3053, 170), (3054, 3061, 169), (3062, 3069, 168), (3070, 3077, 167)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_7_k : d11_7.map (·.k) = List.range' 3040 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c452
