-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c452.Data13
import Solutions.SharpCertFast.P06P0r12c452.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c452
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d13_0_okE : (d13_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3319, 3330, 142), (3331, 3342, 141), (3343, 3355, 140), (3356, 3368, 139)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_0_k : d13_0.map (·.k) = List.range' 3328 32 := by decide +kernel
theorem d13_1_okE : (d13_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3356, 3368, 139), (3369, 3381, 138), (3382, 3394, 137)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_1_k : d13_1.map (·.k) = List.range' 3360 32 := by decide +kernel
theorem d13_2_okE : (d13_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3382, 3394, 137), (3395, 3408, 136), (3409, 3422, 135), (3423, 3436, 134)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_2_k : d13_2.map (·.k) = List.range' 3392 32 := by decide +kernel
theorem d13_3_okE : (d13_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3423, 3436, 134), (3437, 3450, 133), (3451, 3464, 132)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_3_k : d13_3.map (·.k) = List.range' 3424 32 := by decide +kernel
theorem d13_4_okE : (d13_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3451, 3464, 132), (3465, 3479, 131), (3480, 3494, 130)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_4_k : d13_4.map (·.k) = List.range' 3456 32 := by decide +kernel
theorem d13_5_okE : (d13_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3480, 3494, 130), (3495, 3509, 129), (3510, 3525, 128)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_5_k : d13_5.map (·.k) = List.range' 3488 32 := by decide +kernel
theorem d13_6_okE : (d13_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3510, 3525, 128), (3526, 3541, 127), (3542, 3557, 126)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_6_k : d13_6.map (·.k) = List.range' 3520 32 := by decide +kernel
theorem d13_7_okE : (d13_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3542, 3557, 126), (3558, 3574, 125), (3575, 3590, 124)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_7_k : d13_7.map (·.k) = List.range' 3552 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c452
