-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c448.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c448
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 2917, 201), (2918, 2922, 200), (2923, 2927, 199), (2928, 2933, 198), (2934, 2938, 197), (2939, 2944, 196), (2945, 2949, 195), (2950, 2955, 194), (2956, 2960, 193), (2961, 2966, 192), (2967, 2972, 191), (2973, 2978, 190), (2979, 2984, 189), (2985, 2990, 188), (2991, 2996, 187), (2997, 3003, 186), (3004, 3009, 185), (3010, 3015, 184), (3016, 3022, 183), (3023, 3029, 182), (3030, 3035, 181), (3036, 3042, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c448
