-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c900.Data57
import Solutions.SharpCertFast.P06P0r12c900.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c900
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d57_0_okE : (d57_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(14576, 14600, 75), (14601, 14627, 74)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d57_0_k : d57_0.map (·.k) = List.range' 14592 32 := by decide +kernel
theorem d57_1_okE : (d57_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(14601, 14627, 74), (14628, 14653, 73), (14654, 14681, 72)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d57_1_k : d57_1.map (·.k) = List.range' 14624 32 := by decide +kernel
theorem d57_2_okE : (d57_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(14654, 14681, 72), (14682, 14709, 71)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d57_2_k : d57_2.map (·.k) = List.range' 14656 32 := by decide +kernel
theorem d57_3_okE : (d57_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(14682, 14709, 71), (14710, 14738, 70)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d57_3_k : d57_3.map (·.k) = List.range' 14688 32 := by decide +kernel
theorem d57_4_okE : (d57_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(14710, 14738, 70), (14739, 14768, 69)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d57_4_k : d57_4.map (·.k) = List.range' 14720 32 := by decide +kernel
theorem d57_5_okE : (d57_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(14739, 14768, 69), (14769, 14798, 68)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d57_5_k : d57_5.map (·.k) = List.range' 14752 32 := by decide +kernel
theorem d57_6_okE : (d57_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(14769, 14798, 68), (14799, 14829, 67)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d57_6_k : d57_6.map (·.k) = List.range' 14784 32 := by decide +kernel
theorem d57_7_okE : (d57_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(14799, 14829, 67), (14830, 14861, 66)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d57_7_k : d57_7.map (·.k) = List.range' 14816 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c900
