-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c23.Data21
import Solutions.SharpCertFast.P06P0r12c23.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c23
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d21_0_okE : (d21_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5372, 5382, 100), (5383, 5394, 99), (5395, 5406, 98), (5407, 5419, 97)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_0_k : d21_0.map (·.k) = List.range' 5376 32 := by decide +kernel
theorem d21_1_okE : (d21_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5407, 5419, 97), (5420, 5432, 96), (5433, 5445, 95)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_1_k : d21_1.map (·.k) = List.range' 5408 32 := by decide +kernel
theorem d21_2_okE : (d21_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5433, 5445, 95), (5446, 5459, 94), (5460, 5473, 93)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_2_k : d21_2.map (·.k) = List.range' 5440 32 := by decide +kernel
theorem d21_3_okE : (d21_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5460, 5473, 93), (5474, 5487, 92), (5488, 5502, 91), (5503, 5517, 90)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_3_k : d21_3.map (·.k) = List.range' 5472 32 := by decide +kernel
theorem d21_4_okE : (d21_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5503, 5517, 90), (5518, 5532, 89), (5533, 5548, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_4_k : d21_4.map (·.k) = List.range' 5504 32 := by decide +kernel
theorem d21_5_okE : (d21_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5533, 5548, 88), (5549, 5565, 87), (5566, 5582, 86)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_5_k : d21_5.map (·.k) = List.range' 5536 32 := by decide +kernel
theorem d21_6_okE : (d21_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5566, 5582, 86), (5583, 5599, 85)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_6_k : d21_6.map (·.k) = List.range' 5568 32 := by decide +kernel
theorem d21_7_okE : (d21_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5600, 5617, 84), (5618, 5635, 83)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_7_k : d21_7.map (·.k) = List.range' 5600 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c23
