-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c354.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c354
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5034, 5091, 69), (5092, 5151, 68), (5152, 5212, 67), (5213, 5275, 66), (5276, 5339, 65), (5340, 5404, 64), (5405, 5471, 63), (5472, 5540, 62), (5541, 5610, 61), (5611, 5682, 60), (5683, 5755, 59), (5756, 5830, 58), (5831, 5907, 57), (5908, 5985, 56), (5986, 6065, 55), (6066, 6146, 54), (6147, 6230, 53), (6231, 6314, 52), (6315, 6401, 51), (6402, 6489, 50), (6490, 6579, 49), (6580, 6670, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c354
