-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c483.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c483
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6852, 6938, 47), (6939, 7027, 46), (7028, 7117, 45), (7118, 7208, 44), (7209, 7300, 43), (7301, 7394, 42), (7395, 7489, 41), (7490, 7585, 40), (7586, 7682, 39), (7683, 7780, 38), (7781, 7879, 37), (7880, 7978, 36), (7979, 8078, 35), (8079, 8171, 34), (8172, 8190, 33), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c483
