-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c747.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c747
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(6594, 6598, 105), (6599, 6603, 104), (6604, 6608, 103), (6609, 6613, 102), (6614, 6618, 101), (6619, 6624, 100), (6625, 6629, 99), (6630, 6635, 98), (6636, 6641, 97), (6642, 6646, 96), (6647, 6653, 95), (6654, 6659, 94), (6660, 6665, 93), (6666, 6672, 92), (6673, 6679, 91), (6680, 6686, 90), (6687, 6693, 89), (6694, 6701, 88), (6702, 6708, 87), (6709, 6716, 86), (6717, 6724, 85), (6725, 6733, 84)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c747
