-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c618.Data82
import Solutions.SharpCertFast.P06P0r12c618.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c618
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d82_0_okE : (d82_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(20975, 21030, 131)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d82_0_k : d82_0.map (·.k) = List.range' 20992 32 := by decide +kernel
theorem d82_1_okE : (d82_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(20975, 21030, 131), (21031, 21087, 130)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d82_1_k : d82_1.map (·.k) = List.range' 21024 32 := by decide +kernel
theorem d82_2_okE : (d82_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(21031, 21087, 130)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d82_2_k : d82_2.map (·.k) = List.range' 21056 32 := by decide +kernel
theorem d82_3_okE : (d82_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(21088, 21144, 129)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d82_3_k : d82_3.map (·.k) = List.range' 21088 32 := by decide +kernel
theorem d82_4_okE : (d82_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(21088, 21144, 129), (21145, 21203, 128)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d82_4_k : d82_4.map (·.k) = List.range' 21120 32 := by decide +kernel
theorem d82_5_okE : (d82_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(21145, 21203, 128)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d82_5_k : d82_5.map (·.k) = List.range' 21152 32 := by decide +kernel
theorem d82_6_okE : (d82_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(21145, 21203, 128), (21204, 21262, 127)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d82_6_k : d82_6.map (·.k) = List.range' 21184 32 := by decide +kernel
theorem d82_7_okE : (d82_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(21204, 21262, 127)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d82_7_k : d82_7.map (·.k) = List.range' 21216 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c618
