-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c770.Data22
import Solutions.SharpCertFast.P06P0r12c770.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c770
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d22_0_okE : (d22_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5580, 5691, 188)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_0_k : d22_0.map (·.k) = List.range' 5632 32 := by decide +kernel
theorem d22_1_okE : (d22_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5580, 5691, 188), (5692, 5693, 187), (5694, 5694, 186), (5695, 5696, 185)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_1_k : d22_1.map (·.k) = List.range' 5664 32 := by decide +kernel
theorem d22_2_okE : (d22_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5695, 5696, 185), (5697, 5698, 184), (5699, 5699, 183), (5700, 5701, 182), (5702, 5703, 181), (5704, 5705, 180), (5706, 5707, 179), (5708, 5709, 178), (5710, 5711, 177), (5712, 5712, 176), (5713, 5714, 175), (5715, 5716, 174), (5717, 5719, 173), (5720, 5721, 172), (5722, 5723, 171), (5724, 5725, 170), (5726, 5727, 169)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_2_k : d22_2.map (·.k) = List.range' 5696 32 := by decide +kernel
theorem d22_3_okE : (d22_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5728, 5729, 168), (5730, 5732, 167), (5733, 5734, 166), (5735, 5736, 165), (5737, 5739, 164), (5740, 5741, 163), (5742, 5743, 162), (5744, 5746, 161), (5747, 5748, 160), (5749, 5751, 159), (5752, 5754, 158), (5755, 5756, 157), (5757, 5759, 156)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_3_k : d22_3.map (·.k) = List.range' 5728 32 := by decide +kernel
theorem d22_4_okE : (d22_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5760, 5762, 155), (5763, 5765, 154), (5766, 5768, 153), (5769, 5771, 152), (5772, 5773, 151), (5774, 5777, 150), (5778, 5780, 149), (5781, 5783, 148), (5784, 5786, 147), (5787, 5789, 146), (5790, 5793, 145)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_4_k : d22_4.map (·.k) = List.range' 5760 32 := by decide +kernel
theorem d22_5_okE : (d22_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5790, 5793, 145), (5794, 5796, 144), (5797, 5799, 143), (5800, 5803, 142), (5804, 5807, 141), (5808, 5810, 140), (5811, 5814, 139), (5815, 5818, 138), (5819, 5822, 137), (5823, 5826, 136)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_5_k : d22_5.map (·.k) = List.range' 5792 32 := by decide +kernel
theorem d22_6_okE : (d22_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5823, 5826, 136), (5827, 5830, 135), (5831, 5834, 134), (5835, 5838, 133), (5839, 5842, 132), (5843, 5847, 131), (5848, 5851, 130), (5852, 5856, 129)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_6_k : d22_6.map (·.k) = List.range' 5824 32 := by decide +kernel
theorem d22_7_okE : (d22_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5852, 5856, 129), (5857, 5860, 128), (5861, 5865, 127), (5866, 5870, 126), (5871, 5875, 125), (5876, 5880, 124), (5881, 5885, 123), (5886, 5890, 122)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_7_k : d22_7.map (·.k) = List.range' 5856 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c770
