-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c20.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c20
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5859, 5891, 69), (5892, 5925, 68), (5926, 5959, 67), (5960, 5995, 66), (5996, 6032, 65), (6033, 6070, 64), (6071, 6109, 63), (6110, 6150, 62), (6151, 6192, 61), (6193, 6235, 60), (6236, 6279, 59), (6280, 6325, 58), (6326, 6372, 57), (6373, 6421, 56), (6422, 6472, 55), (6473, 6524, 54), (6525, 6578, 53), (6579, 6633, 52), (6634, 6690, 51), (6691, 6749, 50), (6750, 6810, 49), (6811, 6872, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c20
