-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c284.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c284
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(8834, 8862, 135), (8863, 8891, 134), (8892, 8921, 133), (8922, 8951, 132), (8952, 8981, 131), (8982, 9013, 130), (9014, 9044, 129), (9045, 9076, 128), (9077, 9109, 127), (9110, 9143, 126), (9144, 9176, 125), (9177, 9211, 124), (9212, 9246, 123), (9247, 9281, 122), (9282, 9318, 121), (9319, 9354, 120), (9355, 9392, 119), (9393, 9430, 118), (9431, 9469, 117), (9470, 9508, 116), (9509, 9549, 115), (9550, 9589, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c284
