-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c200.Data13
import Solutions.SharpCertFast.P06P0r12c200.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c200
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d13_0_okE : (d13_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3307, 3336, 107), (3337, 3366, 106)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_0_k : d13_0.map (·.k) = List.range' 3328 32 := by decide +kernel
theorem d13_1_okE : (d13_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3337, 3366, 106), (3367, 3397, 105)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_1_k : d13_1.map (·.k) = List.range' 3360 32 := by decide +kernel
theorem d13_2_okE : (d13_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3367, 3397, 105), (3398, 3429, 104)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_2_k : d13_2.map (·.k) = List.range' 3392 32 := by decide +kernel
theorem d13_3_okE : (d13_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3398, 3429, 104), (3430, 3461, 103)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_3_k : d13_3.map (·.k) = List.range' 3424 32 := by decide +kernel
theorem d13_4_okE : (d13_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3430, 3461, 103), (3462, 3493, 102)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_4_k : d13_4.map (·.k) = List.range' 3456 32 := by decide +kernel
theorem d13_5_okE : (d13_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3462, 3493, 102), (3494, 3527, 101)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_5_k : d13_5.map (·.k) = List.range' 3488 32 := by decide +kernel
theorem d13_6_okE : (d13_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3494, 3527, 101), (3528, 3561, 100)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_6_k : d13_6.map (·.k) = List.range' 3520 32 := by decide +kernel
theorem d13_7_okE : (d13_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3528, 3561, 100), (3562, 3596, 99)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_7_k : d13_7.map (·.k) = List.range' 3552 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c200
