-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c44.Data19
import Solutions.SharpCertFast.P06P0r12c44.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c44
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d19_0_okE : (d19_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4855, 4884, 169), (4885, 4914, 168)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d19_0_k : d19_0.map (·.k) = List.range' 4864 32 := by decide +kernel
theorem d19_1_okE : (d19_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4885, 4914, 168), (4915, 4944, 167)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d19_1_k : d19_1.map (·.k) = List.range' 4896 32 := by decide +kernel
theorem d19_2_okE : (d19_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4915, 4944, 167), (4945, 4975, 166)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d19_2_k : d19_2.map (·.k) = List.range' 4928 32 := by decide +kernel
theorem d19_3_okE : (d19_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4945, 4975, 166), (4976, 5006, 165)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d19_3_k : d19_3.map (·.k) = List.range' 4960 32 := by decide +kernel
theorem d19_4_okE : (d19_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4976, 5006, 165), (5007, 5038, 164)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d19_4_k : d19_4.map (·.k) = List.range' 4992 32 := by decide +kernel
theorem d19_5_okE : (d19_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5007, 5038, 164), (5039, 5070, 163)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d19_5_k : d19_5.map (·.k) = List.range' 5024 32 := by decide +kernel
theorem d19_6_okE : (d19_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5039, 5070, 163), (5071, 5102, 162)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d19_6_k : d19_6.map (·.k) = List.range' 5056 32 := by decide +kernel
theorem d19_7_okE : (d19_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5071, 5102, 162), (5103, 5135, 161)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d19_7_k : d19_7.map (·.k) = List.range' 5088 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c44
