-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c798.Data21
import Solutions.SharpCertFast.P06P0r12c798.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c798
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d21_0_okE : (d21_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5371, 5385, 97), (5386, 5400, 96), (5401, 5416, 95)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_0_k : d21_0.map (·.k) = List.range' 5376 32 := by decide +kernel
theorem d21_1_okE : (d21_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5401, 5416, 95), (5417, 5432, 94), (5433, 5448, 93)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_1_k : d21_1.map (·.k) = List.range' 5408 32 := by decide +kernel
theorem d21_2_okE : (d21_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5433, 5448, 93), (5449, 5465, 92), (5466, 5482, 91)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_2_k : d21_2.map (·.k) = List.range' 5440 32 := by decide +kernel
theorem d21_3_okE : (d21_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5466, 5482, 91), (5483, 5500, 90), (5501, 5518, 89)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_3_k : d21_3.map (·.k) = List.range' 5472 32 := by decide +kernel
theorem d21_4_okE : (d21_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5501, 5518, 89), (5519, 5536, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_4_k : d21_4.map (·.k) = List.range' 5504 32 := by decide +kernel
theorem d21_5_okE : (d21_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5519, 5536, 88), (5537, 5555, 87), (5556, 5575, 86)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_5_k : d21_5.map (·.k) = List.range' 5536 32 := by decide +kernel
theorem d21_6_okE : (d21_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5556, 5575, 86), (5576, 5595, 85), (5596, 5616, 84)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_6_k : d21_6.map (·.k) = List.range' 5568 32 := by decide +kernel
theorem d21_7_okE : (d21_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5596, 5616, 84), (5617, 5637, 83)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_7_k : d21_7.map (·.k) = List.range' 5600 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c798
