-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c548.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c548
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5404, 5454, 69), (5455, 5507, 68), (5508, 5561, 67), (5562, 5617, 66), (5618, 5674, 65), (5675, 5732, 64), (5733, 5791, 63), (5792, 5852, 62), (5853, 5914, 61), (5915, 5978, 60), (5979, 6043, 59), (6044, 6109, 58), (6110, 6177, 57), (6178, 6247, 56), (6248, 6318, 55), (6319, 6390, 54), (6391, 6464, 53), (6465, 6540, 52), (6541, 6617, 51), (6618, 6695, 50), (6696, 6775, 49), (6776, 6857, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c548
