-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c149.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c149
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(1695, 1706, 179), (1707, 1717, 178), (1718, 1729, 177), (1730, 1741, 176), (1742, 1754, 175), (1755, 1766, 174), (1767, 1779, 173), (1780, 1792, 172), (1793, 1805, 171), (1806, 1818, 170), (1819, 1831, 169), (1832, 1844, 168), (1845, 1858, 167), (1859, 1872, 166), (1873, 1886, 165), (1887, 1900, 164), (1901, 1914, 163), (1915, 1929, 162), (1930, 1944, 161), (1945, 1959, 160), (1960, 1974, 159), (1975, 1990, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c149
