-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c519.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c519
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5378, 5430, 69), (5431, 5483, 68), (5484, 5538, 67), (5539, 5594, 66), (5595, 5652, 65), (5653, 5711, 64), (5712, 5771, 63), (5772, 5833, 62), (5834, 5896, 61), (5897, 5960, 60), (5961, 6026, 59), (6027, 6093, 58), (6094, 6162, 57), (6163, 6233, 56), (6234, 6304, 55), (6305, 6378, 54), (6379, 6453, 53), (6454, 6529, 52), (6530, 6607, 51), (6608, 6687, 50), (6688, 6768, 49), (6769, 6850, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c519
