-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c40.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c40
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(3115, 3125, 179), (3126, 3136, 178), (3137, 3147, 177), (3148, 3158, 176), (3159, 3169, 175), (3170, 3181, 174), (3182, 3192, 173), (3193, 3204, 172), (3205, 3216, 171), (3217, 3228, 170), (3229, 3241, 169), (3242, 3253, 168), (3254, 3266, 167), (3267, 3278, 166), (3279, 3291, 165), (3292, 3304, 164), (3305, 3318, 163), (3319, 3331, 162), (3332, 3345, 161), (3346, 3358, 160), (3359, 3372, 159), (3373, 3387, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c40
