-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c242.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c242
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(9098, 9120, 157), (9121, 9143, 156), (9144, 9167, 155), (9168, 9191, 154), (9192, 9215, 153), (9216, 9239, 152), (9240, 9264, 151), (9265, 9289, 150), (9290, 9315, 149), (9316, 9341, 148), (9342, 9367, 147), (9368, 9394, 146), (9395, 9421, 145), (9422, 9448, 144), (9449, 9476, 143), (9477, 9504, 142), (9505, 9533, 141), (9534, 9562, 140), (9563, 9591, 139), (9592, 9621, 138), (9622, 9651, 137), (9652, 9682, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c242
