-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c442.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c442
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(4511, 4544, 91), (4545, 4578, 90), (4579, 4613, 89), (4614, 4649, 88), (4650, 4686, 87), (4687, 4723, 86), (4724, 4762, 85), (4763, 4801, 84), (4802, 4841, 83), (4842, 4882, 82), (4883, 4923, 81), (4924, 4966, 80), (4967, 5010, 79), (5011, 5055, 78), (5056, 5100, 77), (5101, 5147, 76), (5148, 5195, 75), (5196, 5244, 74), (5245, 5294, 73), (5295, 5345, 72), (5346, 5397, 71), (5398, 5450, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c442
