-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c557.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c557
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6835, 6915, 47), (6916, 6998, 46), (6999, 7082, 45), (7083, 7168, 44), (7169, 7255, 43), (7256, 7343, 42), (7344, 7432, 41), (7433, 7523, 40), (7524, 7615, 39), (7616, 7707, 38), (7708, 7800, 37), (7801, 7894, 36), (7895, 7989, 35), (7990, 8084, 34), (8085, 8172, 33), (8173, 8190, 32), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c557
