-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c557.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c557
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(3318, 3324, 179), (3325, 3330, 178), (3331, 3336, 177), (3337, 3343, 176), (3344, 3349, 175), (3350, 3356, 174), (3357, 3363, 173), (3364, 3370, 172), (3371, 3377, 171), (3378, 3384, 170), (3385, 3391, 169), (3392, 3398, 168), (3399, 3406, 167), (3407, 3413, 166), (3414, 3421, 165), (3422, 3429, 164), (3430, 3437, 163), (3438, 3445, 162), (3446, 3453, 161), (3454, 3461, 160), (3462, 3469, 159), (3470, 3478, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c557
