-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c564.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c564
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(3732, 3736, 179), (3737, 3741, 178), (3742, 3746, 177), (3747, 3752, 176), (3753, 3757, 175), (3758, 3763, 174), (3764, 3769, 173), (3770, 3774, 172), (3775, 3780, 171), (3781, 3786, 170), (3787, 3792, 169), (3793, 3798, 168), (3799, 3804, 167), (3805, 3811, 166), (3812, 3817, 165), (3818, 3823, 164), (3824, 3830, 163), (3831, 3837, 162), (3838, 3844, 161), (3845, 3850, 160), (3851, 3857, 159), (3858, 3865, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c564
