-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c688.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c688
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(5255, 5260, 135), (5261, 5266, 134), (5267, 5272, 133), (5273, 5279, 132), (5280, 5285, 131), (5286, 5292, 130), (5293, 5298, 129), (5299, 5305, 128), (5306, 5312, 127), (5313, 5319, 126), (5320, 5326, 125), (5327, 5334, 124), (5335, 5341, 123), (5342, 5349, 122), (5350, 5357, 121), (5358, 5365, 120), (5366, 5373, 119), (5374, 5381, 118), (5382, 5390, 117), (5391, 5398, 116), (5399, 5407, 115), (5408, 5416, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c688
