-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c214.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c214
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(3007, 3022, 135), (3023, 3038, 134), (3039, 3054, 133), (3055, 3070, 132), (3071, 3087, 131), (3088, 3104, 130), (3105, 3122, 129), (3123, 3139, 128), (3140, 3157, 127), (3158, 3176, 126), (3177, 3194, 125), (3195, 3213, 124), (3214, 3233, 123), (3234, 3253, 122), (3254, 3273, 121), (3274, 3293, 120), (3294, 3314, 119), (3315, 3335, 118), (3336, 3357, 117), (3358, 3379, 116), (3380, 3402, 115), (3403, 3425, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c214
