-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c255.Data12
import Solutions.SharpCertFast.P06P0r12c255.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c255
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d12_0_okE : (d12_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3063, 3086, 116), (3087, 3112, 115)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_0_k : d12_0.map (·.k) = List.range' 3072 32 := by decide +kernel
theorem d12_1_okE : (d12_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3087, 3112, 115), (3113, 3137, 114)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_1_k : d12_1.map (·.k) = List.range' 3104 32 := by decide +kernel
theorem d12_2_okE : (d12_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3113, 3137, 114), (3138, 3163, 113), (3164, 3189, 112)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_2_k : d12_2.map (·.k) = List.range' 3136 32 := by decide +kernel
theorem d12_3_okE : (d12_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3164, 3189, 112), (3190, 3216, 111)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_3_k : d12_3.map (·.k) = List.range' 3168 32 := by decide +kernel
theorem d12_4_okE : (d12_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3190, 3216, 111), (3217, 3244, 110)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_4_k : d12_4.map (·.k) = List.range' 3200 32 := by decide +kernel
theorem d12_5_okE : (d12_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3217, 3244, 110), (3245, 3272, 109)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_5_k : d12_5.map (·.k) = List.range' 3232 32 := by decide +kernel
theorem d12_6_okE : (d12_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3245, 3272, 109), (3273, 3301, 108)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_6_k : d12_6.map (·.k) = List.range' 3264 32 := by decide +kernel
theorem d12_7_okE : (d12_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3273, 3301, 108), (3302, 3330, 107)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_7_k : d12_7.map (·.k) = List.range' 3296 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c255
