-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c673.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c673
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(3945, 3950, 179), (3951, 3956, 178), (3957, 3961, 177), (3962, 3967, 176), (3968, 3973, 175), (3974, 3979, 174), (3980, 3985, 173), (3986, 3991, 172), (3992, 3997, 171), (3998, 4003, 170), (4004, 4010, 169), (4011, 4016, 168), (4017, 4023, 167), (4024, 4030, 166), (4031, 4036, 165), (4037, 4043, 164), (4044, 4050, 163), (4051, 4057, 162), (4058, 4065, 161), (4066, 4072, 160), (4073, 4079, 159), (4080, 4087, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c673
