-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c512.Data33
import Solutions.SharpCertFast.P06P0r12c512.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c512
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d33_0_okE : (d33_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8448, 8460, 197), (8461, 8474, 196), (8475, 8488, 195)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_0_k : d33_0.map (·.k) = List.range' 8448 32 := by decide +kernel
theorem d33_1_okE : (d33_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8475, 8488, 195), (8489, 8503, 194), (8504, 8517, 193)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_1_k : d33_1.map (·.k) = List.range' 8480 32 := by decide +kernel
theorem d33_2_okE : (d33_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8504, 8517, 193), (8518, 8532, 192), (8533, 8546, 191)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_2_k : d33_2.map (·.k) = List.range' 8512 32 := by decide +kernel
theorem d33_3_okE : (d33_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8533, 8546, 191), (8547, 8561, 190), (8562, 8576, 189)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_3_k : d33_3.map (·.k) = List.range' 8544 32 := by decide +kernel
theorem d33_4_okE : (d33_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8562, 8576, 189), (8577, 8592, 188), (8593, 8607, 187)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_4_k : d33_4.map (·.k) = List.range' 8576 32 := by decide +kernel
theorem d33_5_okE : (d33_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8608, 8623, 186), (8624, 8639, 185)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_5_k : d33_5.map (·.k) = List.range' 8608 32 := by decide +kernel
theorem d33_6_okE : (d33_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8640, 8655, 184), (8656, 8671, 183)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_6_k : d33_6.map (·.k) = List.range' 8640 32 := by decide +kernel
theorem d33_7_okE : (d33_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8672, 8688, 182), (8689, 8704, 181)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_7_k : d33_7.map (·.k) = List.range' 8672 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c512
