-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c636.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c636
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(6368, 6374, 95), (6375, 6382, 94), (6383, 6390, 93), (6391, 6399, 92), (6400, 6407, 91), (6408, 6416, 90), (6417, 6425, 89), (6426, 6434, 88), (6435, 6444, 87), (6445, 6454, 86), (6455, 6464, 85), (6465, 6474, 84), (6475, 6485, 83), (6486, 6496, 82), (6497, 6507, 81), (6508, 6519, 80), (6520, 6531, 79), (6532, 6543, 78), (6544, 6556, 77), (6557, 6569, 76), (6570, 6583, 75), (6584, 6597, 74)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c636
