-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c623.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c623
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(3677, 3682, 179), (3683, 3687, 178), (3688, 3692, 177), (3693, 3698, 176), (3699, 3704, 175), (3705, 3709, 174), (3710, 3715, 173), (3716, 3721, 172), (3722, 3727, 171), (3728, 3733, 170), (3734, 3739, 169), (3740, 3745, 168), (3746, 3752, 167), (3753, 3758, 166), (3759, 3765, 165), (3766, 3771, 164), (3772, 3778, 163), (3779, 3785, 162), (3786, 3792, 161), (3793, 3799, 160), (3800, 3806, 159), (3807, 3813, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c623
