-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c737.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c737
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(7401, 7433, 43), (7434, 7467, 42), (7468, 7501, 41), (7502, 7537, 40), (7538, 7573, 39), (7574, 7610, 38), (7611, 7649, 37), (7650, 7688, 36), (7689, 7728, 35), (7729, 7768, 34), (7769, 7809, 33), (7810, 7851, 32), (7852, 7894, 31), (7895, 7936, 30), (7937, 7980, 29), (7981, 8023, 28), (8024, 8066, 27), (8067, 8110, 26), (8111, 8153, 25), (8154, 8187, 24), (8188, 8190, 23), (8191, 8191, 0)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c737
