-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c203.Data20
import Solutions.SharpCertFast.P06P0r12c203.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c203
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d20_0_okE : (d20_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5098, 5124, 153), (5125, 5151, 152)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_0_k : d20_0.map (·.k) = List.range' 5120 32 := by decide +kernel
theorem d20_1_okE : (d20_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5152, 5179, 151), (5180, 5208, 150)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_1_k : d20_1.map (·.k) = List.range' 5152 32 := by decide +kernel
theorem d20_2_okE : (d20_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5180, 5208, 150), (5209, 5236, 149)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_2_k : d20_2.map (·.k) = List.range' 5184 32 := by decide +kernel
theorem d20_3_okE : (d20_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5209, 5236, 149), (5237, 5266, 148)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_3_k : d20_3.map (·.k) = List.range' 5216 32 := by decide +kernel
theorem d20_4_okE : (d20_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5237, 5266, 148), (5267, 5295, 147)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_4_k : d20_4.map (·.k) = List.range' 5248 32 := by decide +kernel
theorem d20_5_okE : (d20_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5267, 5295, 147), (5296, 5325, 146)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_5_k : d20_5.map (·.k) = List.range' 5280 32 := by decide +kernel
theorem d20_6_okE : (d20_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5296, 5325, 146), (5326, 5356, 145)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_6_k : d20_6.map (·.k) = List.range' 5312 32 := by decide +kernel
theorem d20_7_okE : (d20_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5326, 5356, 145), (5357, 5387, 144)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_7_k : d20_7.map (·.k) = List.range' 5344 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c203
