-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c335.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c335
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(2763, 2779, 135), (2780, 2796, 134), (2797, 2814, 133), (2815, 2832, 132), (2833, 2851, 131), (2852, 2869, 130), (2870, 2888, 129), (2889, 2908, 128), (2909, 2927, 127), (2928, 2947, 126), (2948, 2968, 125), (2969, 2988, 124), (2989, 3009, 123), (3010, 3031, 122), (3032, 3053, 121), (3054, 3075, 120), (3076, 3098, 119), (3099, 3121, 118), (3122, 3145, 117), (3146, 3169, 116), (3170, 3193, 115), (3194, 3218, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c335
