-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c733.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c733
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(6190, 6216, 69), (6217, 6243, 68), (6244, 6271, 67), (6272, 6300, 66), (6301, 6329, 65), (6330, 6360, 64), (6361, 6391, 63), (6392, 6424, 62), (6425, 6457, 61), (6458, 6491, 60), (6492, 6527, 59), (6528, 6563, 58), (6564, 6601, 57), (6602, 6639, 56), (6640, 6679, 55), (6680, 6719, 54), (6720, 6761, 53), (6762, 6804, 52), (6805, 6849, 51), (6850, 6894, 50), (6895, 6941, 49), (6942, 6989, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c733
