-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c796.Data17
import Solutions.SharpCertFast.P06P0r12c796.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c796
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d17_0_okE : (d17_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4350, 4355, 147), (4356, 4362, 146), (4363, 4369, 145), (4370, 4376, 144), (4377, 4383, 143)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_0_k : d17_0.map (·.k) = List.range' 4352 32 := by decide +kernel
theorem d17_1_okE : (d17_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4384, 4391, 142), (4392, 4398, 141), (4399, 4406, 140), (4407, 4414, 139), (4415, 4422, 138)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_1_k : d17_1.map (·.k) = List.range' 4384 32 := by decide +kernel
theorem d17_2_okE : (d17_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4415, 4422, 138), (4423, 4430, 137), (4431, 4438, 136), (4439, 4446, 135), (4447, 4455, 134)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_2_k : d17_2.map (·.k) = List.range' 4416 32 := by decide +kernel
theorem d17_3_okE : (d17_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4447, 4455, 134), (4456, 4463, 133), (4464, 4472, 132), (4473, 4481, 131)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_3_k : d17_3.map (·.k) = List.range' 4448 32 := by decide +kernel
theorem d17_4_okE : (d17_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4473, 4481, 131), (4482, 4490, 130), (4491, 4500, 129), (4501, 4509, 128), (4510, 4519, 127)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_4_k : d17_4.map (·.k) = List.range' 4480 32 := by decide +kernel
theorem d17_5_okE : (d17_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4510, 4519, 127), (4520, 4529, 126), (4530, 4539, 125), (4540, 4549, 124)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_5_k : d17_5.map (·.k) = List.range' 4512 32 := by decide +kernel
theorem d17_6_okE : (d17_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4540, 4549, 124), (4550, 4560, 123), (4561, 4571, 122), (4572, 4582, 121)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_6_k : d17_6.map (·.k) = List.range' 4544 32 := by decide +kernel
theorem d17_7_okE : (d17_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4572, 4582, 121), (4583, 4593, 120), (4594, 4604, 119), (4605, 4616, 118)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_7_k : d17_7.map (·.k) = List.range' 4576 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c796
