-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c383.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c383
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(3588, 3610, 113), (3611, 3633, 112), (3634, 3657, 111), (3658, 3682, 110), (3683, 3707, 109), (3708, 3732, 108), (3733, 3758, 107), (3759, 3784, 106), (3785, 3811, 105), (3812, 3839, 104), (3840, 3867, 103), (3868, 3896, 102), (3897, 3925, 101), (3926, 3955, 100), (3956, 3985, 99), (3986, 4016, 98), (4017, 4048, 97), (4049, 4081, 96), (4082, 4114, 95), (4115, 4147, 94), (4148, 4182, 93), (4183, 4217, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c383
