-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c138.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c138
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(14403, 14587, 47), (14588, 14775, 46), (14776, 14965, 45), (14966, 15157, 44), (15158, 15351, 43), (15352, 15547, 42), (15548, 15745, 41), (15746, 15945, 40), (15946, 16146, 39), (16147, 16337, 38), (16338, 16382, 37), (16383, 16383, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c138
