-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c572.Data24
import Solutions.SharpCertFast.P06P0r12c572.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c572
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d24_0_okE : (d24_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6140, 6145, 108), (6146, 6151, 107), (6152, 6158, 106), (6159, 6164, 105), (6165, 6171, 104), (6172, 6177, 103)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_0_k : d24_0.map (·.k) = List.range' 6144 32 := by decide +kernel
theorem d24_1_okE : (d24_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6172, 6177, 103), (6178, 6184, 102), (6185, 6191, 101), (6192, 6199, 100), (6200, 6206, 99), (6207, 6214, 98)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_1_k : d24_1.map (·.k) = List.range' 6176 32 := by decide +kernel
theorem d24_2_okE : (d24_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6207, 6214, 98), (6215, 6222, 97), (6223, 6230, 96), (6231, 6238, 95), (6239, 6247, 94)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_2_k : d24_2.map (·.k) = List.range' 6208 32 := by decide +kernel
theorem d24_3_okE : (d24_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6239, 6247, 94), (6248, 6255, 93), (6256, 6264, 92), (6265, 6274, 91)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_3_k : d24_3.map (·.k) = List.range' 6240 32 := by decide +kernel
theorem d24_4_okE : (d24_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6265, 6274, 91), (6275, 6283, 90), (6284, 6293, 89), (6294, 6303, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_4_k : d24_4.map (·.k) = List.range' 6272 32 := by decide +kernel
theorem d24_5_okE : (d24_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6304, 6313, 87), (6314, 6324, 86), (6325, 6335, 85)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_5_k : d24_5.map (·.k) = List.range' 6304 32 := by decide +kernel
theorem d24_6_okE : (d24_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6336, 6346, 84), (6347, 6358, 83), (6359, 6370, 82)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_6_k : d24_6.map (·.k) = List.range' 6336 32 := by decide +kernel
theorem d24_7_okE : (d24_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6359, 6370, 82), (6371, 6382, 81), (6383, 6395, 80), (6396, 6408, 79)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_7_k : d24_7.map (·.k) = List.range' 6368 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c572
