-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c471.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c471
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6875, 6950, 47), (6951, 7028, 46), (7029, 7107, 45), (7108, 7188, 44), (7189, 7270, 43), (7271, 7353, 42), (7354, 7437, 41), (7438, 7523, 40), (7524, 7610, 39), (7611, 7698, 38), (7699, 7786, 37), (7787, 7876, 36), (7877, 7966, 35), (7967, 8056, 34), (8057, 8147, 33), (8148, 8190, 32), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c471
