-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c845.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c845
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(5656, 5673, 91), (5674, 5691, 90), (5692, 5709, 89), (5710, 5728, 88), (5729, 5747, 87), (5748, 5767, 86), (5768, 5787, 85), (5788, 5808, 84), (5809, 5829, 83), (5830, 5851, 82), (5852, 5874, 81), (5875, 5897, 80), (5898, 5920, 79), (5921, 5944, 78), (5945, 5969, 77), (5970, 5995, 76), (5996, 6021, 75), (6022, 6048, 74), (6049, 6075, 73), (6076, 6104, 72), (6105, 6133, 71), (6134, 6163, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c845
