-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c266.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c266
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(2669, 2679, 157), (2680, 2690, 156), (2691, 2702, 155), (2703, 2714, 154), (2715, 2726, 153), (2727, 2738, 152), (2739, 2750, 151), (2751, 2763, 150), (2764, 2776, 149), (2777, 2789, 148), (2790, 2802, 147), (2803, 2815, 146), (2816, 2829, 145), (2830, 2843, 144), (2844, 2857, 143), (2858, 2871, 142), (2872, 2886, 141), (2887, 2901, 140), (2902, 2916, 139), (2917, 2931, 138), (2932, 2947, 137), (2948, 2963, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c266
