-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c431.Data12
import Solutions.SharpCertFast.P06P0r12c431.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c431
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d12_0_okE : (d12_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3071, 3082, 152), (3083, 3093, 151), (3094, 3105, 150)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_0_k : d12_0.map (·.k) = List.range' 3072 32 := by decide +kernel
theorem d12_1_okE : (d12_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3094, 3105, 150), (3106, 3117, 149), (3118, 3130, 148), (3131, 3142, 147)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_1_k : d12_1.map (·.k) = List.range' 3104 32 := by decide +kernel
theorem d12_2_okE : (d12_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3131, 3142, 147), (3143, 3155, 146), (3156, 3168, 145)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_2_k : d12_2.map (·.k) = List.range' 3136 32 := by decide +kernel
theorem d12_3_okE : (d12_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3156, 3168, 145), (3169, 3181, 144), (3182, 3195, 143), (3196, 3208, 142)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_3_k : d12_3.map (·.k) = List.range' 3168 32 := by decide +kernel
theorem d12_4_okE : (d12_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3196, 3208, 142), (3209, 3222, 141), (3223, 3236, 140)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_4_k : d12_4.map (·.k) = List.range' 3200 32 := by decide +kernel
theorem d12_5_okE : (d12_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3223, 3236, 140), (3237, 3250, 139), (3251, 3265, 138)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_5_k : d12_5.map (·.k) = List.range' 3232 32 := by decide +kernel
theorem d12_6_okE : (d12_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3251, 3265, 138), (3266, 3280, 137), (3281, 3295, 136)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_6_k : d12_6.map (·.k) = List.range' 3264 32 := by decide +kernel
theorem d12_7_okE : (d12_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3296, 3310, 135), (3311, 3326, 134), (3327, 3341, 133)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_7_k : d12_7.map (·.k) = List.range' 3296 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c431
