-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c193.Data7
import Solutions.SharpCertFast.P06P0r12c193.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c193
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d7_0_okE : (d7_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1783, 1797, 160), (1798, 1812, 159), (1813, 1827, 158)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d7_0_k : d7_0.map (·.k) = List.range' 1792 32 := by decide +kernel
theorem d7_1_okE : (d7_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1813, 1827, 158), (1828, 1842, 157), (1843, 1858, 156)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d7_1_k : d7_1.map (·.k) = List.range' 1824 32 := by decide +kernel
theorem d7_2_okE : (d7_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1843, 1858, 156), (1859, 1873, 155), (1874, 1889, 154)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d7_2_k : d7_2.map (·.k) = List.range' 1856 32 := by decide +kernel
theorem d7_3_okE : (d7_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1874, 1889, 154), (1890, 1906, 153), (1907, 1922, 152)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d7_3_k : d7_3.map (·.k) = List.range' 1888 32 := by decide +kernel
theorem d7_4_okE : (d7_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1907, 1922, 152), (1923, 1939, 151), (1940, 1956, 150)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d7_4_k : d7_4.map (·.k) = List.range' 1920 32 := by decide +kernel
theorem d7_5_okE : (d7_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1940, 1956, 150), (1957, 1973, 149), (1974, 1990, 148)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d7_5_k : d7_5.map (·.k) = List.range' 1952 32 := by decide +kernel
theorem d7_6_okE : (d7_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1974, 1990, 148), (1991, 2008, 147), (2009, 2026, 146)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d7_6_k : d7_6.map (·.k) = List.range' 1984 32 := by decide +kernel
theorem d7_7_okE : (d7_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2009, 2026, 146), (2027, 2044, 145), (2045, 2063, 144)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d7_7_k : d7_7.map (·.k) = List.range' 2016 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c193
