-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c193.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c193
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(1828, 1842, 157), (1843, 1858, 156), (1859, 1873, 155), (1874, 1889, 154), (1890, 1906, 153), (1907, 1922, 152), (1923, 1939, 151), (1940, 1956, 150), (1957, 1973, 149), (1974, 1990, 148), (1991, 2008, 147), (2009, 2026, 146), (2027, 2044, 145), (2045, 2063, 144), (2064, 2081, 143), (2082, 2100, 142), (2101, 2120, 141), (2121, 2140, 140), (2141, 2160, 139), (2161, 2180, 138), (2181, 2201, 137), (2202, 2222, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c193
