-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c678.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c678
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5312, 5358, 69), (5359, 5407, 68), (5408, 5456, 67), (5457, 5507, 66), (5508, 5559, 65), (5560, 5612, 64), (5613, 5667, 63), (5668, 5723, 62), (5724, 5780, 61), (5781, 5839, 60), (5840, 5899, 59), (5900, 5961, 58), (5962, 6024, 57), (6025, 6089, 56), (6090, 6155, 55), (6156, 6223, 54), (6224, 6292, 53), (6293, 6363, 52), (6364, 6436, 51), (6437, 6510, 50), (6511, 6585, 49), (6586, 6662, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c678
