-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c740.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c740
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(4157, 4160, 179), (4161, 4164, 178), (4165, 4168, 177), (4169, 4172, 176), (4173, 4176, 175), (4177, 4181, 174), (4182, 4185, 173), (4186, 4190, 172), (4191, 4194, 171), (4195, 4199, 170), (4200, 4204, 169), (4205, 4208, 168), (4209, 4213, 167), (4214, 4218, 166), (4219, 4223, 165), (4224, 4228, 164), (4229, 4233, 163), (4234, 4238, 162), (4239, 4244, 161), (4245, 4249, 160), (4250, 4255, 159), (4256, 4260, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c740
