-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c32.Data102
import Solutions.SharpCertFast.P06P0r12c32.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c32
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d102_0_okE : (d102_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(25990, 26206, 68)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d102_0_k : d102_0.map (·.k) = List.range' 26112 32 := by decide +kernel
theorem d102_1_okE : (d102_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(25990, 26206, 68)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d102_1_k : d102_1.map (·.k) = List.range' 26144 32 := by decide +kernel
theorem d102_2_okE : (d102_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(25990, 26206, 68), (26207, 26426, 67)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d102_2_k : d102_2.map (·.k) = List.range' 26176 32 := by decide +kernel
theorem d102_3_okE : (d102_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26207, 26426, 67)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d102_3_k : d102_3.map (·.k) = List.range' 26208 32 := by decide +kernel
theorem d102_4_okE : (d102_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26207, 26426, 67)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d102_4_k : d102_4.map (·.k) = List.range' 26240 32 := by decide +kernel
theorem d102_5_okE : (d102_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26207, 26426, 67)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d102_5_k : d102_5.map (·.k) = List.range' 26272 32 := by decide +kernel
theorem d102_6_okE : (d102_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26207, 26426, 67)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d102_6_k : d102_6.map (·.k) = List.range' 26304 32 := by decide +kernel
theorem d102_7_okE : (d102_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26207, 26426, 67)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d102_7_k : d102_7.map (·.k) = List.range' 26336 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c32
