-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c398.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c398
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(3075, 3089, 135), (3090, 3104, 134), (3105, 3119, 133), (3120, 3135, 132), (3136, 3150, 131), (3151, 3166, 130), (3167, 3183, 129), (3184, 3199, 128), (3200, 3216, 127), (3217, 3233, 126), (3234, 3251, 125), (3252, 3269, 124), (3270, 3287, 123), (3288, 3306, 122), (3307, 3324, 121), (3325, 3344, 120), (3345, 3363, 119), (3364, 3383, 118), (3384, 3404, 117), (3405, 3424, 116), (3425, 3446, 115), (3447, 3467, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c398
