-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c424.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c424
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(5790, 5791, 157), (5792, 5794, 156), (5795, 5796, 155), (5797, 5799, 154), (5800, 5801, 153), (5802, 5804, 152), (5805, 5807, 151), (5808, 5809, 150), (5810, 5812, 149), (5813, 5815, 148), (5816, 5818, 147), (5819, 5821, 146), (5822, 5824, 145), (5825, 5827, 144), (5828, 5830, 143), (5831, 5833, 142), (5834, 5836, 141), (5837, 5839, 140), (5840, 5842, 139), (5843, 5846, 138), (5847, 5849, 137), (5850, 5853, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c424
