-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c701.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c701
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(5121, 5140, 91), (5141, 5161, 90), (5162, 5182, 89), (5183, 5204, 88), (5205, 5227, 87), (5228, 5250, 86), (5251, 5273, 85), (5274, 5298, 84), (5299, 5322, 83), (5323, 5348, 82), (5349, 5374, 81), (5375, 5401, 80), (5402, 5429, 79), (5430, 5457, 78), (5458, 5486, 77), (5487, 5516, 76), (5517, 5547, 75), (5548, 5578, 74), (5579, 5611, 73), (5612, 5644, 72), (5645, 5678, 71), (5679, 5713, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c701
