-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c634.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c634
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 5104, 201), (5105, 5106, 200), (5107, 5107, 199), (5108, 5109, 198), (5110, 5111, 197), (5112, 5113, 196), (5114, 5115, 195), (5116, 5117, 194), (5118, 5119, 193), (5120, 5121, 192), (5122, 5123, 191), (5124, 5125, 190), (5126, 5127, 189), (5128, 5129, 188), (5130, 5131, 187), (5132, 5133, 186), (5134, 5135, 185), (5136, 5138, 184), (5139, 5140, 183), (5141, 5142, 182), (5143, 5144, 181), (5145, 5147, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c634
