-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c554.Data33
import Solutions.SharpCertFast.P06P0r12c554.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c554
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d33_0_okE : (d33_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 8559, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_0_k : d33_0.map (·.k) = List.range' 8448 32 := by decide +kernel
theorem d33_1_okE : (d33_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 8559, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_1_k : d33_1.map (·.k) = List.range' 8480 32 := by decide +kernel
theorem d33_2_okE : (d33_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 8559, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_2_k : d33_2.map (·.k) = List.range' 8512 32 := by decide +kernel
theorem d33_3_okE : (d33_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 8559, 201), (8560, 8569, 200), (8570, 8579, 199)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_3_k : d33_3.map (·.k) = List.range' 8544 32 := by decide +kernel
theorem d33_4_okE : (d33_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8570, 8579, 199), (8580, 8589, 198), (8590, 8599, 197), (8600, 8609, 196)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_4_k : d33_4.map (·.k) = List.range' 8576 32 := by decide +kernel
theorem d33_5_okE : (d33_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8600, 8609, 196), (8610, 8619, 195), (8620, 8630, 194), (8631, 8640, 193)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_5_k : d33_5.map (·.k) = List.range' 8608 32 := by decide +kernel
theorem d33_6_okE : (d33_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8631, 8640, 193), (8641, 8651, 192), (8652, 8662, 191), (8663, 8673, 190)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_6_k : d33_6.map (·.k) = List.range' 8640 32 := by decide +kernel
theorem d33_7_okE : (d33_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(8663, 8673, 190), (8674, 8684, 189), (8685, 8695, 188), (8696, 8706, 187)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d33_7_k : d33_7.map (·.k) = List.range' 8672 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c554
