-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c522.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c522
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 3173, 201), (3174, 3177, 200), (3178, 3182, 199), (3183, 3187, 198), (3188, 3192, 197), (3193, 3197, 196), (3198, 3202, 195), (3203, 3207, 194), (3208, 3213, 193), (3214, 3218, 192), (3219, 3223, 191), (3224, 3229, 190), (3230, 3234, 189), (3235, 3240, 188), (3241, 3246, 187), (3247, 3251, 186), (3252, 3257, 185), (3258, 3263, 184), (3264, 3269, 183), (3270, 3275, 182), (3276, 3281, 181), (3282, 3288, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c522
