-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c728.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c728
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(4984, 5007, 91), (5008, 5031, 90), (5032, 5056, 89), (5057, 5081, 88), (5082, 5107, 87), (5108, 5134, 86), (5135, 5161, 85), (5162, 5189, 84), (5190, 5217, 83), (5218, 5246, 82), (5247, 5276, 81), (5277, 5307, 80), (5308, 5339, 79), (5340, 5371, 78), (5372, 5404, 77), (5405, 5438, 76), (5439, 5473, 75), (5474, 5509, 74), (5510, 5545, 73), (5546, 5583, 72), (5584, 5621, 71), (5622, 5661, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c728
