-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c404.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c404
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(4188, 4220, 91), (4221, 4255, 90), (4256, 4290, 89), (4291, 4325, 88), (4326, 4362, 87), (4363, 4399, 86), (4400, 4438, 85), (4439, 4477, 84), (4478, 4517, 83), (4518, 4558, 82), (4559, 4600, 81), (4601, 4643, 80), (4644, 4687, 79), (4688, 4732, 78), (4733, 4778, 77), (4779, 4825, 76), (4826, 4873, 75), (4874, 4923, 74), (4924, 4973, 73), (4974, 5025, 72), (5026, 5078, 71), (5079, 5132, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c404
