-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c194.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c194
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6944, 7049, 47), (7050, 7156, 46), (7157, 7265, 45), (7266, 7375, 44), (7376, 7486, 43), (7487, 7598, 42), (7599, 7711, 41), (7712, 7825, 40), (7826, 7939, 39), (7940, 8055, 38), (8056, 8164, 37), (8165, 8190, 36), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c194
