-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c194.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c194
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(3714, 3760, 91), (3761, 3808, 90), (3809, 3856, 89), (3857, 3906, 88), (3907, 3957, 87), (3958, 4008, 86), (4009, 4061, 85), (4062, 4115, 84), (4116, 4170, 83), (4171, 4226, 82), (4227, 4283, 81), (4284, 4341, 80), (4342, 4400, 79), (4401, 4461, 78), (4462, 4523, 77), (4524, 4586, 76), (4587, 4650, 75), (4651, 4716, 74), (4717, 4783, 73), (4784, 4851, 72), (4852, 4921, 71), (4922, 4992, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c194
