-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c641.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c641
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(4308, 4311, 179), (4312, 4315, 178), (4316, 4319, 177), (4320, 4323, 176), (4324, 4327, 175), (4328, 4332, 174), (4333, 4336, 173), (4337, 4341, 172), (4342, 4345, 171), (4346, 4350, 170), (4351, 4355, 169), (4356, 4360, 168), (4361, 4364, 167), (4365, 4369, 166), (4370, 4375, 165), (4376, 4380, 164), (4381, 4385, 163), (4386, 4390, 162), (4391, 4396, 161), (4397, 4401, 160), (4402, 4407, 159), (4408, 4412, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c641
