-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c641.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c641
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 4233, 201), (4234, 4236, 200), (4237, 4239, 199), (4240, 4243, 198), (4244, 4246, 197), (4247, 4249, 196), (4250, 4252, 195), (4253, 4255, 194), (4256, 4259, 193), (4260, 4262, 192), (4263, 4265, 191), (4266, 4269, 190), (4270, 4272, 189), (4273, 4276, 188), (4277, 4280, 187), (4281, 4283, 186), (4284, 4287, 185), (4288, 4291, 184), (4292, 4295, 183), (4296, 4299, 182), (4300, 4303, 181), (4304, 4307, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c641
