-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c679.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c679
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(9309, 9322, 157), (9323, 9336, 156), (9337, 9351, 155), (9352, 9365, 154), (9366, 9380, 153), (9381, 9395, 152), (9396, 9410, 151), (9411, 9426, 150), (9427, 9442, 149), (9443, 9458, 148), (9459, 9474, 147), (9475, 9491, 146), (9492, 9508, 145), (9509, 9525, 144), (9526, 9543, 143), (9544, 9560, 142), (9561, 9578, 141), (9579, 9597, 140), (9598, 9616, 139), (9617, 9635, 138), (9636, 9654, 137), (9655, 9674, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c679
