-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c163.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c163
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(5738, 5744, 113), (5745, 5750, 112), (5751, 5757, 111), (5758, 5765, 110), (5766, 5772, 109), (5773, 5779, 108), (5780, 5787, 107), (5788, 5795, 106), (5796, 5803, 105), (5804, 5811, 104), (5812, 5820, 103), (5821, 5829, 102), (5830, 5838, 101), (5839, 5847, 100), (5848, 5856, 99), (5857, 5866, 98), (5867, 5876, 97), (5877, 5886, 96), (5887, 5896, 95), (5897, 5907, 94), (5908, 5918, 93), (5919, 5929, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c163
