-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c861.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c861
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(7292, 7301, 65), (7302, 7312, 64), (7313, 7322, 63), (7323, 7334, 62), (7335, 7345, 61), (7346, 7357, 60), (7358, 7369, 59), (7370, 7382, 58), (7383, 7395, 57), (7396, 7409, 56), (7410, 7423, 55), (7424, 7438, 54), (7439, 7454, 53), (7455, 7469, 52), (7470, 7486, 51), (7487, 7503, 50), (7504, 7521, 49), (7522, 7539, 48), (7540, 7558, 47), (7559, 7577, 46), (7578, 7598, 45), (7599, 7619, 44)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c861
