-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c690.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c690
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(6331, 6333, 122), (6334, 6337, 121), (6338, 6341, 120), (6342, 6345, 119), (6346, 6349, 118), (6350, 6353, 117), (6354, 6357, 116), (6358, 6361, 115), (6362, 6366, 114), (6367, 6370, 113), (6371, 6375, 112), (6376, 6379, 111), (6380, 6384, 110), (6385, 6389, 109), (6390, 6394, 108), (6395, 6399, 107), (6400, 6404, 106), (6405, 6410, 105), (6411, 6415, 104), (6416, 6421, 103), (6422, 6427, 102), (6428, 6433, 101)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c690
