import Bridge.TangentLines

/-! Lines of the exported bank `P0r12` (generated by research/turibius-of-mogrovejo/p06/lw_lines.py). -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace DiagRamsey

open LuWangBridge

theorem line_P0r12_40 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((11667999999999963093801697/10000000000000000000000000 : ℚ)) : ℝ) + (((374269729489035776035589/1250000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 1002 1864658340202305 4503599627370496 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11667999999999963093801697 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2994157835912286208284712 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_41 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((11703999999999711168634383/10000000000000000000000000 : ℚ)) : ℝ) + (((2979300425412277342807213/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 995 1852685564359789 4503599627370496 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11703999999999711168634383 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2979300425412277342807213 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_42 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((1173199999999986608450343/1000000000000000000000000 : ℚ)) : ℝ) + (((1483905272872785592385289/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 991 921728119139507 2251799813685248 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11731999999999866084503430 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2967810545745571184770578 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_43 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((11744000000000287670074369/10000000000000000000000000 : ℚ)) : ℝ) + (((46295372418388777656507/156250000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 989 1839522921684837 4503599627370496 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11744000000000287670074369 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2962903834776881770016448 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_44 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((1469249999999991593181017/1250000000000000000000000 : ℚ)) : ℝ) + (((2958822903207979824962349/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 987 7345019961414813 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11753999999999932745448136 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2958822903207979824962349 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_45 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((2357600000000072406948899/2000000000000000000000000 : ℚ)) : ℝ) + (((2945001814866729328291041/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 982 1825212205803751 4503599627370496 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11788000000000362034744495 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2945001814866729328291041 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_46 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((5900000000000023003581281/5000000000000000000000000 : ℚ)) : ℝ) + (((2940143634617203197586417/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 980 7285358785682783 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11800000000000046007162562 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2940143634617203197586417 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_47 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((5910000000000006287886491/5000000000000000000000000 : ℚ)) : ℝ) + (((1466034771381028519479153/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 977 7259656391764515 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11820000000000012575772982 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2932069542762057038958306 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_48 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((739249999999998611914559/625000000000000000000000 : ℚ)) : ℝ) + (((14644239413572436167109/50000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 975 7249414870025891 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11827999999999977790632944 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2928847882714487233421800 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_49 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((5924999999999946699237151/5000000000000000000000000 : ℚ)) : ℝ) + (((146000585597223761391913/500000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 972 7221368368662853 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11849999999999893398474302 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2920011711944475227838260 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_50 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((2377599999999933592428967/2000000000000000000000000 : ℚ)) : ℝ) + (((290482954574109247409737/1000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 967 7173325784801035 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11887999999999667962144835 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2904829545741092474097370 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_51 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((2387200000000007825996253/2000000000000000000000000 : ℚ)) : ℝ) + (((1442898017345537764209551/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 959 7113358830511671 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11936000000000039129981265 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2885796034691075528419102 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_52 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((11938000000000051540959617/10000000000000000000000000 : ℚ)) : ℝ) + (((2885006430987706742095331/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 959 7110877256188941 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11938000000000051540959617 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2885006430987706742095331 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_53 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((5976000000000015905077233/5000000000000000000000000 : ℚ)) : ℝ) + (((2879486907961901621654489/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 957 432955679385 1099511627776 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11952000000000031810154466 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2879486907961901621654489 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_54 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((748499999999993289896703/625000000000000000000000 : ℚ)) : ℝ) + (((717514028944977412506147/2500000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 954 7063990534864719 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    11975999999999892638347248 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2870056115779909650024588 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_55 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12009999999999942503985071/10000000000000000000000000 : ℚ)) : ℝ) + (((1428381473060858245605801/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 948 7022453806268425 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12009999999999942503985071 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2856762946121716491211602 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_56 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((1502250000000032986345919/1250000000000000000000000 : ℚ)) : ℝ) + (((570729301688533128899919/2000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 947 219148027909293 562949953421312 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12018000000000263890767352 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2853646508442665644499595 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_57 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((6017999999999931084052753/5000000000000000000000000 : ℚ)) : ℝ) + (((569330053821733603175733/2000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 945 3495476263977303 9007199254740992 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12035999999999862168105506 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2846650269108668015878665 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_58 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12048000000000017487436509/10000000000000000000000000 : ℚ)) : ℝ) + (((2841998179190341849577383/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 943 6976488820163467 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12048000000000017487436509 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2841998179190341849577383 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_59 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((6026000000000000856685433/5000000000000000000000000 : ℚ)) : ℝ) + (((2840449621601052689854947/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 943 3485839578488883 9007199254740992 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12052000000000001713370866 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2840449621601052689854947 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_60 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((6029999999999997786873879/5000000000000000000000000 : ℚ)) : ℝ) + (((70933892697094840411071/250000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 941 6962073915254997 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12059999999999995573747758 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2837355707883793616442840 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_61 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((6039999999999965770485757/5000000000000000000000000 : ℚ)) : ℝ) + (((2829639544309204461259219/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 938 6938152902771799 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12079999999999931540971514 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2829639544309204461259219 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_62 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((2421999999999976824587489/2000000000000000000000000 : ℚ)) : ℝ) + (((1409057455638905555657811/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 934 1725629465218531 4503599627370496 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12109999999999884122937445 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2818114911277811111315622 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_63 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((6059999999999996044553901/5000000000000000000000000 : ℚ)) : ℝ) + (((1407143262173167319983449/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 933 6890705394570065 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12119999999999992089107802 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2814286524346334639966898 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_64 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12124000000000033557077407/10000000000000000000000000 : ℚ)) : ℝ) + (((2812757004203157879504179/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 932 3442994173153999 9007199254740992 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12124000000000033557077407 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2812757004203157879504179 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_65 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12138000000000105652604439/10000000000000000000000000 : ℚ)) : ℝ) + (((701852979600083812546647/2500000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 930 3434761226597869 9007199254740992 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12138000000000105652604439 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2807411918400335250186588 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_66 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((6114000000000006018024203/5000000000000000000000000 : ℚ)) : ℝ) + (((173334594587336941470451/625000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 918 422822888251949 1125899906842624 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12228000000000012036048406 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2773353513397391063527216 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_67 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12231999999999866985186923/10000000000000000000000000 : ℚ)) : ℝ) + (((1385925926606645975665411/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 917 6760586899785865 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12231999999999866985186923 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2771851853213291951330822 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_68 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((1223599999999999486996073/1000000000000000000000000 : ℚ)) : ℝ) + (((2770351209191717669451243/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 917 211125437155243 562949953421312 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12235999999999994869960730 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2770351209191717669451243 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_69 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12255999999999794624898443/10000000000000000000000000 : ℚ)) : ℝ) + (((2762863191678996143901477/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 913 6733219982418977 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12255999999999794624898443 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2762863191678996143901477 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_70 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((6137999999999993117707647/5000000000000000000000000 : ℚ)) : ℝ) + (((2755400410738937514471651/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 911 1677637985868995 4503599627370496 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12275999999999986235415294 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2755400410738937514471651 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_71 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12316000000000007175859933/10000000000000000000000000 : ℚ)) : ℝ) + (((2740550009025244943309031/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 906 6665583838325009 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12316000000000007175859933 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2740550009025244943309031 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_72 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12339999999999994829731231/10000000000000000000000000 : ℚ)) : ℝ) + (((1365843752092534452738231/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 902 103731837383515 281474976710656 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12339999999999994829731231 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2731687504185068905476462 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_73 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12356000000000049253437509/10000000000000000000000000 : ℚ)) : ℝ) + (((2725798913426225336232139/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 900 6621103738542933 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12356000000000049253437509 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2725798913426225336232139 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_74 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12363999999999990784073711/10000000000000000000000000 : ℚ)) : ℝ) + (((1361430257994676169371291/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 899 6612265764964779 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12363999999999990784073711 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2722860515989352338742582 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_75 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((3092000000000031268647461/2500000000000000000000000 : ℚ)) : ℝ) + (((2721392787964377743186977/10000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 898 1651963354815485 4503599627370496 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12368000000000125074589844 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2721392787964377743186977 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_76 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12372000000000059908526131/10000000000000000000000000 : ℚ)) : ℝ) + (((1359963019548618296128757/5000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 898 6603447034022481 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12372000000000059908526131 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2719926039097236592257514 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_77 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((1549499999999985304533987/1250000000000000000000000 : ℚ)) : ℝ) + (((6777865116034306743951/25000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 895 6577105855668201 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12395999999999882436271896 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2711146046413722697580400 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_78 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12423999999999921606170871/10000000000000000000000000 : ℚ)) : ℝ) + (((2700946914812446849727/10000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 890 6546591561395285 18014398509481984 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12423999999999921606170871 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2700946914812446849727000 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

theorem line_P0r12_79 : ∀ s : ℝ, 0 < s →
    symmetricProfile luWangSource 1 s ≤ (((12425999999999872655352799/10000000000000000000000000 : ℚ)) : ℝ) + (((540044043536527333117833/2000000000000000000000000 : ℚ)) : ℝ) * s := by
  intro s hs
  have h := (line_atS 890 3272210208331227 9007199254740992 (by norm_num) (by norm_num) (by norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    12425999999999872655352799 10000000000000000000000000 (by norm_num) (by decide +kernel)
    2700220217682636665589165 10000000000000000000000000 (by norm_num) (by decide +kernel) s hs).1
  push_cast at h ⊢; linarith

end DiagRamsey
