-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c288.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c288
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5245, 5299, 69), (5300, 5355, 68), (5356, 5412, 67), (5413, 5471, 66), (5472, 5532, 65), (5533, 5593, 64), (5594, 5657, 63), (5658, 5721, 62), (5722, 5787, 61), (5788, 5855, 60), (5856, 5924, 59), (5925, 5995, 58), (5996, 6067, 57), (6068, 6141, 56), (6142, 6216, 55), (6217, 6293, 54), (6294, 6372, 53), (6373, 6452, 52), (6453, 6534, 51), (6535, 6617, 50), (6618, 6702, 49), (6703, 6789, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c288
