-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c516.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c516
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(2984, 2990, 179), (2991, 2997, 178), (2998, 3005, 177), (3006, 3012, 176), (3013, 3020, 175), (3021, 3027, 174), (3028, 3035, 173), (3036, 3043, 172), (3044, 3051, 171), (3052, 3059, 170), (3060, 3067, 169), (3068, 3075, 168), (3076, 3084, 167), (3085, 3092, 166), (3093, 3101, 165), (3102, 3110, 164), (3111, 3119, 163), (3120, 3128, 162), (3129, 3137, 161), (3138, 3146, 160), (3147, 3156, 159), (3157, 3165, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c516
