-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c212.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c212
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(4212, 4249, 91), (4250, 4288, 90), (4289, 4327, 89), (4328, 4368, 88), (4369, 4409, 87), (4410, 4451, 86), (4452, 4494, 85), (4495, 4538, 84), (4539, 4582, 83), (4583, 4628, 82), (4629, 4675, 81), (4676, 4723, 80), (4724, 4772, 79), (4773, 4822, 78), (4823, 4873, 77), (4874, 4925, 76), (4926, 4978, 75), (4979, 5033, 74), (5034, 5088, 73), (5089, 5145, 72), (5146, 5203, 71), (5204, 5263, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c212
