-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c19.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c19
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(4800, 4806, 135), (4807, 4812, 134), (4813, 4819, 133), (4820, 4826, 132), (4827, 4833, 131), (4834, 4840, 130), (4841, 4847, 129), (4848, 4855, 128), (4856, 4862, 127), (4863, 4870, 126), (4871, 4878, 125), (4879, 4886, 124), (4887, 4894, 123), (4895, 4903, 122), (4904, 4911, 121), (4912, 4920, 120), (4921, 4929, 119), (4930, 4938, 118), (4939, 4948, 117), (4949, 4957, 116), (4958, 4967, 115), (4968, 4977, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c19
