-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c456.Data12
import Solutions.SharpCertFast.P06P0r12c456.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c456
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d12_0_okE : (d12_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3214, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_0_k : d12_0.map (·.k) = List.range' 3072 32 := by decide +kernel
theorem d12_1_okE : (d12_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3214, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_1_k : d12_1.map (·.k) = List.range' 3104 32 := by decide +kernel
theorem d12_2_okE : (d12_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3214, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_2_k : d12_2.map (·.k) = List.range' 3136 32 := by decide +kernel
theorem d12_3_okE : (d12_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3214, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_3_k : d12_3.map (·.k) = List.range' 3168 32 := by decide +kernel
theorem d12_4_okE : (d12_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3214, 201), (3215, 3219, 200), (3220, 3224, 199), (3225, 3229, 198), (3230, 3235, 197)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_4_k : d12_4.map (·.k) = List.range' 3200 32 := by decide +kernel
theorem d12_5_okE : (d12_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3230, 3235, 197), (3236, 3240, 196), (3241, 3245, 195), (3246, 3251, 194), (3252, 3256, 193), (3257, 3261, 192), (3262, 3267, 191)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_5_k : d12_5.map (·.k) = List.range' 3232 32 := by decide +kernel
theorem d12_6_okE : (d12_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3262, 3267, 191), (3268, 3273, 190), (3274, 3279, 189), (3280, 3284, 188), (3285, 3290, 187), (3291, 3296, 186)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_6_k : d12_6.map (·.k) = List.range' 3264 32 := by decide +kernel
theorem d12_7_okE : (d12_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3291, 3296, 186), (3297, 3302, 185), (3303, 3308, 184), (3309, 3315, 183), (3316, 3321, 182), (3322, 3327, 181)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_7_k : d12_7.map (·.k) = List.range' 3296 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c456
