-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c456.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c456
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(3745, 3757, 135), (3758, 3770, 134), (3771, 3784, 133), (3785, 3798, 132), (3799, 3812, 131), (3813, 3826, 130), (3827, 3841, 129), (3842, 3856, 128), (3857, 3871, 127), (3872, 3886, 126), (3887, 3902, 125), (3903, 3918, 124), (3919, 3934, 123), (3935, 3951, 122), (3952, 3968, 121), (3969, 3985, 120), (3986, 4003, 119), (4004, 4020, 118), (4021, 4039, 117), (4040, 4057, 116), (4058, 4076, 115), (4077, 4096, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c456
