-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c289.Data20
import Solutions.SharpCertFast.P06P0r12c289.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c289
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d20_0_okE : (d20_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5118, 5133, 95), (5134, 5149, 94), (5150, 5165, 93)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_0_k : d20_0.map (·.k) = List.range' 5120 32 := by decide +kernel
theorem d20_1_okE : (d20_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5150, 5165, 93), (5166, 5182, 92), (5183, 5200, 91)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_1_k : d20_1.map (·.k) = List.range' 5152 32 := by decide +kernel
theorem d20_2_okE : (d20_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5183, 5200, 91), (5201, 5218, 90)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_2_k : d20_2.map (·.k) = List.range' 5184 32 := by decide +kernel
theorem d20_3_okE : (d20_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5201, 5218, 90), (5219, 5236, 89), (5237, 5255, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_3_k : d20_3.map (·.k) = List.range' 5216 32 := by decide +kernel
theorem d20_4_okE : (d20_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5237, 5255, 88), (5256, 5274, 87), (5275, 5294, 86)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_4_k : d20_4.map (·.k) = List.range' 5248 32 := by decide +kernel
theorem d20_5_okE : (d20_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5275, 5294, 86), (5295, 5315, 85)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_5_k : d20_5.map (·.k) = List.range' 5280 32 := by decide +kernel
theorem d20_6_okE : (d20_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5295, 5315, 85), (5316, 5336, 84), (5337, 5358, 83)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_6_k : d20_6.map (·.k) = List.range' 5312 32 := by decide +kernel
theorem d20_7_okE : (d20_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5337, 5358, 83), (5359, 5380, 82)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d20_7_k : d20_7.map (·.k) = List.range' 5344 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c289
