-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c180.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c180
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(4082, 4122, 91), (4123, 4164, 90), (4165, 4206, 89), (4207, 4250, 88), (4251, 4294, 87), (4295, 4339, 86), (4340, 4386, 85), (4387, 4433, 84), (4434, 4481, 83), (4482, 4530, 82), (4531, 4580, 81), (4581, 4632, 80), (4633, 4684, 79), (4685, 4738, 78), (4739, 4792, 77), (4793, 4848, 76), (4849, 4905, 75), (4906, 4963, 74), (4964, 5023, 73), (5024, 5083, 72), (5084, 5145, 71), (5146, 5209, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c180
