-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c822.Data28
import Solutions.SharpCertFast.P06P0r12c822.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c822
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d28_0_okE : (d28_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7156, 7168, 62), (7169, 7183, 61), (7184, 7197, 60), (7198, 7212, 59)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d28_0_k : d28_0.map (·.k) = List.range' 7168 32 := by decide +kernel
theorem d28_1_okE : (d28_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7198, 7212, 59), (7213, 7228, 58), (7229, 7245, 57)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d28_1_k : d28_1.map (·.k) = List.range' 7200 32 := by decide +kernel
theorem d28_2_okE : (d28_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7229, 7245, 57), (7246, 7262, 56), (7263, 7279, 55)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d28_2_k : d28_2.map (·.k) = List.range' 7232 32 := by decide +kernel
theorem d28_3_okE : (d28_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7263, 7279, 55), (7280, 7297, 54)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d28_3_k : d28_3.map (·.k) = List.range' 7264 32 := by decide +kernel
theorem d28_4_okE : (d28_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7280, 7297, 54), (7298, 7316, 53), (7317, 7335, 52)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d28_4_k : d28_4.map (·.k) = List.range' 7296 32 := by decide +kernel
theorem d28_5_okE : (d28_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7317, 7335, 52), (7336, 7356, 51), (7357, 7376, 50)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d28_5_k : d28_5.map (·.k) = List.range' 7328 32 := by decide +kernel
theorem d28_6_okE : (d28_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7357, 7376, 50), (7377, 7398, 49)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d28_6_k : d28_6.map (·.k) = List.range' 7360 32 := by decide +kernel
theorem d28_7_okE : (d28_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(7377, 7398, 49), (7399, 7420, 48), (7421, 7443, 47)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d28_7_k : d28_7.map (·.k) = List.range' 7392 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c822
