-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c650.Data36
import Solutions.SharpCertFast.P06P0r12c650.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c650
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d36_0_okE : (d36_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9201, 9219, 152), (9220, 9238, 151), (9239, 9257, 150)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_0_k : d36_0.map (·.k) = List.range' 9216 32 := by decide +kernel
theorem d36_1_okE : (d36_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9239, 9257, 150), (9258, 9277, 149), (9278, 9297, 148)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_1_k : d36_1.map (·.k) = List.range' 9248 32 := by decide +kernel
theorem d36_2_okE : (d36_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9278, 9297, 148), (9298, 9318, 147)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_2_k : d36_2.map (·.k) = List.range' 9280 32 := by decide +kernel
theorem d36_3_okE : (d36_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9298, 9318, 147), (9319, 9338, 146), (9339, 9359, 145)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_3_k : d36_3.map (·.k) = List.range' 9312 32 := by decide +kernel
theorem d36_4_okE : (d36_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9339, 9359, 145), (9360, 9381, 144)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_4_k : d36_4.map (·.k) = List.range' 9344 32 := by decide +kernel
theorem d36_5_okE : (d36_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9360, 9381, 144), (9382, 9402, 143), (9403, 9425, 142)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_5_k : d36_5.map (·.k) = List.range' 9376 32 := by decide +kernel
theorem d36_6_okE : (d36_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9403, 9425, 142), (9426, 9447, 141)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_6_k : d36_6.map (·.k) = List.range' 9408 32 := by decide +kernel
theorem d36_7_okE : (d36_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9426, 9447, 141), (9448, 9470, 140), (9471, 9493, 139)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_7_k : d36_7.map (·.k) = List.range' 9440 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c650
