-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c465.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c465
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(3738, 3749, 135), (3750, 3761, 134), (3762, 3774, 133), (3775, 3786, 132), (3787, 3799, 131), (3800, 3813, 130), (3814, 3826, 129), (3827, 3840, 128), (3841, 3854, 127), (3855, 3868, 126), (3869, 3882, 125), (3883, 3897, 124), (3898, 3912, 123), (3913, 3927, 122), (3928, 3943, 121), (3944, 3959, 120), (3960, 3975, 119), (3976, 3992, 118), (3993, 4009, 117), (4010, 4026, 116), (4027, 4043, 115), (4044, 4061, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c465
