-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c357.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c357
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5346, 5400, 69), (5401, 5456, 68), (5457, 5513, 67), (5514, 5572, 66), (5573, 5632, 65), (5633, 5693, 64), (5694, 5756, 63), (5757, 5820, 62), (5821, 5885, 61), (5886, 5953, 60), (5954, 6021, 59), (6022, 6091, 58), (6092, 6163, 57), (6164, 6236, 56), (6237, 6310, 55), (6311, 6387, 54), (6388, 6464, 53), (6465, 6544, 52), (6545, 6624, 51), (6625, 6707, 50), (6708, 6791, 49), (6792, 6876, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c357
