-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c253.Data22
import Solutions.SharpCertFast.P06P0r12c253.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c253
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d22_0_okE : (d22_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5632, 5633, 171), (5634, 5635, 170), (5636, 5637, 169), (5638, 5639, 168), (5640, 5642, 167), (5643, 5644, 166), (5645, 5646, 165), (5647, 5648, 164), (5649, 5651, 163), (5652, 5653, 162), (5654, 5655, 161), (5656, 5658, 160), (5659, 5660, 159), (5661, 5663, 158)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_0_k : d22_0.map (·.k) = List.range' 5632 32 := by decide +kernel
theorem d22_1_okE : (d22_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5664, 5665, 157), (5666, 5668, 156), (5669, 5671, 155), (5672, 5673, 154), (5674, 5676, 153), (5677, 5679, 152), (5680, 5682, 151), (5683, 5685, 150), (5686, 5688, 149), (5689, 5691, 148), (5692, 5694, 147), (5695, 5697, 146)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_1_k : d22_1.map (·.k) = List.range' 5664 32 := by decide +kernel
theorem d22_2_okE : (d22_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5695, 5697, 146), (5698, 5700, 145), (5701, 5704, 144), (5705, 5707, 143), (5708, 5710, 142), (5711, 5714, 141), (5715, 5717, 140), (5718, 5721, 139), (5722, 5725, 138), (5726, 5729, 137)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_2_k : d22_2.map (·.k) = List.range' 5696 32 := by decide +kernel
theorem d22_3_okE : (d22_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5726, 5729, 137), (5730, 5732, 136), (5733, 5736, 135), (5737, 5740, 134), (5741, 5744, 133), (5745, 5748, 132), (5749, 5753, 131), (5754, 5757, 130), (5758, 5761, 129)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_3_k : d22_3.map (·.k) = List.range' 5728 32 := by decide +kernel
theorem d22_4_okE : (d22_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5758, 5761, 129), (5762, 5766, 128), (5767, 5771, 127), (5772, 5775, 126), (5776, 5780, 125), (5781, 5785, 124), (5786, 5790, 123), (5791, 5795, 122)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_4_k : d22_4.map (·.k) = List.range' 5760 32 := by decide +kernel
theorem d22_5_okE : (d22_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5791, 5795, 122), (5796, 5801, 121), (5802, 5806, 120), (5807, 5811, 119), (5812, 5817, 118), (5818, 5823, 117)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_5_k : d22_5.map (·.k) = List.range' 5792 32 := by decide +kernel
theorem d22_6_okE : (d22_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5824, 5829, 116), (5830, 5835, 115), (5836, 5841, 114), (5842, 5847, 113), (5848, 5854, 112), (5855, 5860, 111)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_6_k : d22_6.map (·.k) = List.range' 5824 32 := by decide +kernel
theorem d22_7_okE : (d22_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5855, 5860, 111), (5861, 5867, 110), (5868, 5874, 109), (5875, 5881, 108), (5882, 5888, 107)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_7_k : d22_7.map (·.k) = List.range' 5856 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c253
