-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c117.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c117
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(15061, 15239, 47), (15240, 15420, 46), (15421, 15602, 45), (15603, 15786, 44), (15787, 15971, 43), (15972, 16158, 42), (16159, 16337, 41), (16338, 16382, 40), (16383, 16383, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c117
