-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c646.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c646
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(5358, 5362, 135), (5363, 5367, 134), (5368, 5372, 133), (5373, 5378, 132), (5379, 5383, 131), (5384, 5389, 130), (5390, 5394, 129), (5395, 5400, 128), (5401, 5406, 127), (5407, 5412, 126), (5413, 5418, 125), (5419, 5425, 124), (5426, 5431, 123), (5432, 5438, 122), (5439, 5445, 121), (5446, 5451, 120), (5452, 5459, 119), (5460, 5466, 118), (5467, 5473, 117), (5474, 5481, 116), (5482, 5488, 115), (5489, 5496, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c646
