-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c347.Data10
import Solutions.SharpCertFast.P06P0r12c347.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c347
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d10_0_okE : (d10_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2560, 201), (2561, 2566, 200), (2567, 2572, 199), (2573, 2579, 198), (2580, 2585, 197), (2586, 2591, 196)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_0_k : d10_0.map (·.k) = List.range' 2560 32 := by decide +kernel
theorem d10_1_okE : (d10_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2592, 2598, 195), (2599, 2605, 194), (2606, 2611, 193), (2612, 2618, 192), (2619, 2625, 191)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_1_k : d10_1.map (·.k) = List.range' 2592 32 := by decide +kernel
theorem d10_2_okE : (d10_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2619, 2625, 191), (2626, 2632, 190), (2633, 2639, 189), (2640, 2646, 188), (2647, 2653, 187), (2654, 2660, 186)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_2_k : d10_2.map (·.k) = List.range' 2624 32 := by decide +kernel
theorem d10_3_okE : (d10_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2654, 2660, 186), (2661, 2668, 185), (2669, 2675, 184), (2676, 2683, 183), (2684, 2691, 182)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_3_k : d10_3.map (·.k) = List.range' 2656 32 := by decide +kernel
theorem d10_4_okE : (d10_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2684, 2691, 182), (2692, 2698, 181), (2699, 2706, 180), (2707, 2714, 179), (2715, 2722, 178)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_4_k : d10_4.map (·.k) = List.range' 2688 32 := by decide +kernel
theorem d10_5_okE : (d10_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2715, 2722, 178), (2723, 2731, 177), (2732, 2739, 176), (2740, 2748, 175), (2749, 2756, 174)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_5_k : d10_5.map (·.k) = List.range' 2720 32 := by decide +kernel
theorem d10_6_okE : (d10_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2749, 2756, 174), (2757, 2765, 173), (2766, 2774, 172), (2775, 2783, 171)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_6_k : d10_6.map (·.k) = List.range' 2752 32 := by decide +kernel
theorem d10_7_okE : (d10_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2784, 2792, 170), (2793, 2801, 169), (2802, 2810, 168), (2811, 2820, 167)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_7_k : d10_7.map (·.k) = List.range' 2784 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c347
