-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c201.Data15
import Solutions.SharpCertFast.P06P0r12c201.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c201
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d15_0_okE : (d15_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3823, 3861, 93), (3862, 3901, 92)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_0_k : d15_0.map (·.k) = List.range' 3840 32 := by decide +kernel
theorem d15_1_okE : (d15_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3862, 3901, 92), (3902, 3942, 91)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_1_k : d15_1.map (·.k) = List.range' 3872 32 := by decide +kernel
theorem d15_2_okE : (d15_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3902, 3942, 91)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_2_k : d15_2.map (·.k) = List.range' 3904 32 := by decide +kernel
theorem d15_3_okE : (d15_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3902, 3942, 91), (3943, 3984, 90)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_3_k : d15_3.map (·.k) = List.range' 3936 32 := by decide +kernel
theorem d15_4_okE : (d15_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3943, 3984, 90), (3985, 4026, 89)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_4_k : d15_4.map (·.k) = List.range' 3968 32 := by decide +kernel
theorem d15_5_okE : (d15_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3985, 4026, 89), (4027, 4070, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_5_k : d15_5.map (·.k) = List.range' 4000 32 := by decide +kernel
theorem d15_6_okE : (d15_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4027, 4070, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_6_k : d15_6.map (·.k) = List.range' 4032 32 := by decide +kernel
theorem d15_7_okE : (d15_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4027, 4070, 88), (4071, 4115, 87)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d15_7_k : d15_7.map (·.k) = List.range' 4064 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c201
