-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c268.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c268
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(3620, 3643, 113), (3644, 3667, 112), (3668, 3692, 111), (3693, 3718, 110), (3719, 3743, 109), (3744, 3770, 108), (3771, 3796, 107), (3797, 3824, 106), (3825, 3852, 105), (3853, 3880, 104), (3881, 3909, 103), (3910, 3939, 102), (3940, 3969, 101), (3970, 3999, 100), (4000, 4031, 99), (4032, 4063, 98), (4064, 4096, 97), (4097, 4129, 96), (4130, 4163, 95), (4164, 4198, 94), (4199, 4233, 93), (4234, 4270, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c268
