-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c779.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c779
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(5081, 5093, 113), (5094, 5106, 112), (5107, 5120, 111), (5121, 5134, 110), (5135, 5148, 109), (5149, 5163, 108), (5164, 5178, 107), (5179, 5193, 106), (5194, 5208, 105), (5209, 5224, 104), (5225, 5240, 103), (5241, 5257, 102), (5258, 5274, 101), (5275, 5291, 100), (5292, 5309, 99), (5310, 5327, 98), (5328, 5346, 97), (5347, 5365, 96), (5366, 5384, 95), (5385, 5404, 94), (5405, 5424, 93), (5425, 5445, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c779
