-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c588.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c588
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(4025, 4031, 157), (4032, 4039, 156), (4040, 4046, 155), (4047, 4053, 154), (4054, 4061, 153), (4062, 4069, 152), (4070, 4077, 151), (4078, 4085, 150), (4086, 4093, 149), (4094, 4101, 148), (4102, 4109, 147), (4110, 4118, 146), (4119, 4127, 145), (4128, 4135, 144), (4136, 4144, 143), (4145, 4154, 142), (4155, 4163, 141), (4164, 4172, 140), (4173, 4182, 139), (4183, 4192, 138), (4193, 4202, 137), (4203, 4212, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c588
