-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c853.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c853
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(6899, 6919, 60), (6920, 6941, 59), (6942, 6964, 58), (6965, 6987, 57), (6988, 7011, 56), (7012, 7035, 55), (7036, 7061, 54), (7062, 7087, 53), (7088, 7115, 52), (7116, 7143, 51), (7144, 7172, 50), (7173, 7202, 49), (7203, 7233, 48), (7234, 7264, 47), (7265, 7297, 46), (7298, 7331, 45), (7332, 7366, 44), (7367, 7401, 43), (7402, 7438, 42), (7439, 7476, 41), (7477, 7514, 40), (7515, 7554, 39)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c853
