-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c315.Data10
import Solutions.SharpCertFast.P06P0r12c315.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c315
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d10_0_okE : (d10_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2554, 2562, 173), (2563, 2570, 172), (2571, 2579, 171), (2580, 2587, 170), (2588, 2596, 169)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_0_k : d10_0.map (·.k) = List.range' 2560 32 := by decide +kernel
theorem d10_1_okE : (d10_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2588, 2596, 169), (2597, 2605, 168), (2606, 2614, 167), (2615, 2623, 166)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_1_k : d10_1.map (·.k) = List.range' 2592 32 := by decide +kernel
theorem d10_2_okE : (d10_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2624, 2632, 165), (2633, 2642, 164), (2643, 2651, 163), (2652, 2661, 162)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_2_k : d10_2.map (·.k) = List.range' 2624 32 := by decide +kernel
theorem d10_3_okE : (d10_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2652, 2661, 162), (2662, 2671, 161), (2672, 2681, 160), (2682, 2691, 159)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_3_k : d10_3.map (·.k) = List.range' 2656 32 := by decide +kernel
theorem d10_4_okE : (d10_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2682, 2691, 159), (2692, 2701, 158), (2702, 2712, 157), (2713, 2723, 156)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_4_k : d10_4.map (·.k) = List.range' 2688 32 := by decide +kernel
theorem d10_5_okE : (d10_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2713, 2723, 156), (2724, 2733, 155), (2734, 2744, 154), (2745, 2755, 153)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_5_k : d10_5.map (·.k) = List.range' 2720 32 := by decide +kernel
theorem d10_6_okE : (d10_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2745, 2755, 153), (2756, 2767, 152), (2768, 2778, 151), (2779, 2790, 150)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_6_k : d10_6.map (·.k) = List.range' 2752 32 := by decide +kernel
theorem d10_7_okE : (d10_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2779, 2790, 150), (2791, 2802, 149), (2803, 2814, 148), (2815, 2826, 147)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_7_k : d10_7.map (·.k) = List.range' 2784 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c315
