-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c113.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c113
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(4849, 4923, 69), (4924, 5000, 68), (5001, 5079, 67), (5080, 5159, 66), (5160, 5240, 65), (5241, 5324, 64), (5325, 5408, 63), (5409, 5495, 62), (5496, 5583, 61), (5584, 5673, 60), (5674, 5764, 59), (5765, 5857, 58), (5858, 5952, 57), (5953, 6048, 56), (6049, 6146, 55), (6147, 6246, 54), (6247, 6347, 53), (6348, 6450, 52), (6451, 6554, 51), (6555, 6660, 50), (6661, 6768, 49), (6769, 6877, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c113
