-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c263.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c263
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6655, 6755, 47), (6756, 6859, 46), (6860, 6963, 45), (6964, 7070, 44), (7071, 7177, 43), (7178, 7286, 42), (7287, 7396, 41), (7397, 7507, 40), (7508, 7619, 39), (7620, 7731, 38), (7732, 7845, 37), (7846, 7959, 36), (7960, 8073, 35), (8074, 8175, 34), (8176, 8190, 33), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c263
