-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c77.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c77
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(12938, 13041, 69), (13042, 13146, 68), (13147, 13253, 67), (13254, 13361, 66), (13362, 13471, 65), (13472, 13583, 64), (13584, 13696, 63), (13697, 13811, 62), (13812, 13927, 61), (13928, 14044, 60), (14045, 14163, 59), (14164, 14284, 58), (14285, 14406, 57), (14407, 14530, 56), (14531, 14654, 55), (14655, 14781, 54), (14782, 14908, 53), (14909, 15037, 52), (15038, 15167, 51), (15168, 15299, 50), (15300, 15431, 49), (15432, 15565, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c77
