-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c324.Data11
import Solutions.SharpCertFast.P06P0r12c324.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c324
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d11_0_okE : (d11_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2884, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_0_k : d11_0.map (·.k) = List.range' 2816 32 := by decide +kernel
theorem d11_1_okE : (d11_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2884, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_1_k : d11_1.map (·.k) = List.range' 2848 32 := by decide +kernel
theorem d11_2_okE : (d11_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2884, 201), (2885, 2889, 200), (2890, 2894, 199), (2895, 2899, 198), (2900, 2905, 197), (2906, 2910, 196), (2911, 2916, 195)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_2_k : d11_2.map (·.k) = List.range' 2880 32 := by decide +kernel
theorem d11_3_okE : (d11_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2911, 2916, 195), (2917, 2921, 194), (2922, 2927, 193), (2928, 2933, 192), (2934, 2939, 191), (2940, 2945, 190)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_3_k : d11_3.map (·.k) = List.range' 2912 32 := by decide +kernel
theorem d11_4_okE : (d11_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2940, 2945, 190), (2946, 2951, 189), (2952, 2957, 188), (2958, 2963, 187), (2964, 2969, 186), (2970, 2975, 185)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_4_k : d11_4.map (·.k) = List.range' 2944 32 := by decide +kernel
theorem d11_5_okE : (d11_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2976, 2982, 184), (2983, 2988, 183), (2989, 2995, 182), (2996, 3002, 181), (3003, 3008, 180)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_5_k : d11_5.map (·.k) = List.range' 2976 32 := by decide +kernel
theorem d11_6_okE : (d11_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3003, 3008, 180), (3009, 3015, 179), (3016, 3022, 178), (3023, 3029, 177), (3030, 3036, 176), (3037, 3044, 175)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_6_k : d11_6.map (·.k) = List.range' 3008 32 := by decide +kernel
theorem d11_7_okE : (d11_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3037, 3044, 175), (3045, 3051, 174), (3052, 3059, 173), (3060, 3066, 172), (3067, 3074, 171)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_7_k : d11_7.map (·.k) = List.range' 3040 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c324
