-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c139.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c139
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(3024, 3036, 157), (3037, 3049, 156), (3050, 3063, 155), (3064, 3076, 154), (3077, 3090, 153), (3091, 3104, 152), (3105, 3118, 151), (3119, 3132, 150), (3133, 3147, 149), (3148, 3162, 148), (3163, 3177, 147), (3178, 3192, 146), (3193, 3208, 145), (3209, 3224, 144), (3225, 3240, 143), (3241, 3256, 142), (3257, 3272, 141), (3273, 3289, 140), (3290, 3306, 139), (3307, 3323, 138), (3324, 3341, 137), (3342, 3359, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c139
