-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c282.Data12
import Solutions.SharpCertFast.P06P0r12c282.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c282
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d12_0_okE : (d12_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3069, 3078, 159), (3079, 3088, 158), (3089, 3098, 157), (3099, 3108, 156)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_0_k : d12_0.map (·.k) = List.range' 3072 32 := by decide +kernel
theorem d12_1_okE : (d12_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3099, 3108, 156), (3109, 3119, 155), (3120, 3130, 154), (3131, 3140, 153)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_1_k : d12_1.map (·.k) = List.range' 3104 32 := by decide +kernel
theorem d12_2_okE : (d12_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3131, 3140, 153), (3141, 3151, 152), (3152, 3163, 151), (3164, 3174, 150)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_2_k : d12_2.map (·.k) = List.range' 3136 32 := by decide +kernel
theorem d12_3_okE : (d12_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3164, 3174, 150), (3175, 3186, 149), (3187, 3197, 148), (3198, 3209, 147)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_3_k : d12_3.map (·.k) = List.range' 3168 32 := by decide +kernel
theorem d12_4_okE : (d12_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3198, 3209, 147), (3210, 3221, 146), (3222, 3234, 145)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_4_k : d12_4.map (·.k) = List.range' 3200 32 := by decide +kernel
theorem d12_5_okE : (d12_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3222, 3234, 145), (3235, 3246, 144), (3247, 3259, 143), (3260, 3272, 142)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_5_k : d12_5.map (·.k) = List.range' 3232 32 := by decide +kernel
theorem d12_6_okE : (d12_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3260, 3272, 142), (3273, 3285, 141), (3286, 3298, 140)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_6_k : d12_6.map (·.k) = List.range' 3264 32 := by decide +kernel
theorem d12_7_okE : (d12_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3286, 3298, 140), (3299, 3312, 139), (3313, 3326, 138), (3327, 3340, 137)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d12_7_k : d12_7.map (·.k) = List.range' 3296 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c282
