-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c817.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c817
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(6858, 6863, 91), (6864, 6869, 90), (6870, 6875, 89), (6876, 6881, 88), (6882, 6887, 87), (6888, 6894, 86), (6895, 6901, 85), (6902, 6908, 84), (6909, 6915, 83), (6916, 6923, 82), (6924, 6931, 81), (6932, 6939, 80), (6940, 6947, 79), (6948, 6955, 78), (6956, 6964, 77), (6965, 6973, 76), (6974, 6983, 75), (6984, 6992, 74), (6993, 7002, 73), (7003, 7012, 72), (7013, 7023, 71), (7024, 7034, 70)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c817
