-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c726.Data41
import Solutions.SharpCertFast.P06P0r12c726.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c726
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d41_0_okE : (d41_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(10494, 10507, 151), (10508, 10521, 150), (10522, 10535, 149)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d41_0_k : d41_0.map (·.k) = List.range' 10496 32 := by decide +kernel
theorem d41_1_okE : (d41_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(10522, 10535, 149), (10536, 10550, 148), (10551, 10565, 147)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d41_1_k : d41_1.map (·.k) = List.range' 10528 32 := by decide +kernel
theorem d41_2_okE : (d41_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(10551, 10565, 147), (10566, 10580, 146), (10581, 10596, 145)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d41_2_k : d41_2.map (·.k) = List.range' 10560 32 := by decide +kernel
theorem d41_3_okE : (d41_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(10581, 10596, 145), (10597, 10611, 144), (10612, 10627, 143)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d41_3_k : d41_3.map (·.k) = List.range' 10592 32 := by decide +kernel
theorem d41_4_okE : (d41_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(10612, 10627, 143), (10628, 10644, 142), (10645, 10660, 141)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d41_4_k : d41_4.map (·.k) = List.range' 10624 32 := by decide +kernel
theorem d41_5_okE : (d41_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(10645, 10660, 141), (10661, 10677, 140), (10678, 10694, 139)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d41_5_k : d41_5.map (·.k) = List.range' 10656 32 := by decide +kernel
theorem d41_6_okE : (d41_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(10678, 10694, 139), (10695, 10711, 138), (10712, 10729, 137)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d41_6_k : d41_6.map (·.k) = List.range' 10688 32 := by decide +kernel
theorem d41_7_okE : (d41_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(10712, 10729, 137), (10730, 10747, 136), (10748, 10765, 135)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d41_7_k : d41_7.map (·.k) = List.range' 10720 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c726
