-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c153.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c153
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(3070, 3096, 113), (3097, 3123, 112), (3124, 3151, 111), (3152, 3180, 110), (3181, 3209, 109), (3210, 3239, 108), (3240, 3269, 107), (3270, 3300, 106), (3301, 3332, 105), (3333, 3364, 104), (3365, 3396, 103), (3397, 3430, 102), (3431, 3464, 101), (3465, 3499, 100), (3500, 3534, 99), (3535, 3571, 98), (3572, 3607, 97), (3608, 3645, 96), (3646, 3684, 95), (3685, 3723, 94), (3724, 3763, 93), (3764, 3804, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c153
