-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c109.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c109
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(3674, 3691, 135), (3692, 3710, 134), (3711, 3729, 133), (3730, 3749, 132), (3750, 3768, 131), (3769, 3788, 130), (3789, 3809, 129), (3810, 3830, 128), (3831, 3851, 127), (3852, 3872, 126), (3873, 3894, 125), (3895, 3916, 124), (3917, 3938, 123), (3939, 3961, 122), (3962, 3984, 121), (3985, 4007, 120), (4008, 4031, 119), (4032, 4056, 118), (4057, 4080, 117), (4081, 4105, 116), (4106, 4131, 115), (4132, 4157, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c109
