-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c546.Data46
import Solutions.SharpCertFast.P06P0r12c546.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c546
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d46_0_okE : (d46_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11737, 11784, 97), (11785, 11833, 96)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_0_k : d46_0.map (·.k) = List.range' 11776 32 := by decide +kernel
theorem d46_1_okE : (d46_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11785, 11833, 96), (11834, 11884, 95)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_1_k : d46_1.map (·.k) = List.range' 11808 32 := by decide +kernel
theorem d46_2_okE : (d46_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11834, 11884, 95)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_2_k : d46_2.map (·.k) = List.range' 11840 32 := by decide +kernel
theorem d46_3_okE : (d46_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11834, 11884, 95), (11885, 11935, 94)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_3_k : d46_3.map (·.k) = List.range' 11872 32 := by decide +kernel
theorem d46_4_okE : (d46_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11885, 11935, 94)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_4_k : d46_4.map (·.k) = List.range' 11904 32 := by decide +kernel
theorem d46_5_okE : (d46_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11936, 11986, 93)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_5_k : d46_5.map (·.k) = List.range' 11936 32 := by decide +kernel
theorem d46_6_okE : (d46_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11936, 11986, 93), (11987, 12039, 92)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_6_k : d46_6.map (·.k) = List.range' 11968 32 := by decide +kernel
theorem d46_7_okE : (d46_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(11987, 12039, 92)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d46_7_k : d46_7.map (·.k) = List.range' 12000 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c546
