-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c566.Data17
import Solutions.SharpCertFast.P06P0r12c566.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c566
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d17_0_okE : (d17_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4342, 4355, 120), (4356, 4370, 119), (4371, 4384, 118)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_0_k : d17_0.map (·.k) = List.range' 4352 32 := by decide +kernel
theorem d17_1_okE : (d17_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4371, 4384, 118), (4385, 4399, 117), (4400, 4414, 116), (4415, 4430, 115)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_1_k : d17_1.map (·.k) = List.range' 4384 32 := by decide +kernel
theorem d17_2_okE : (d17_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4415, 4430, 115), (4431, 4446, 114), (4447, 4462, 113)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_2_k : d17_2.map (·.k) = List.range' 4416 32 := by decide +kernel
theorem d17_3_okE : (d17_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4447, 4462, 113), (4463, 4478, 112), (4479, 4495, 111)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_3_k : d17_3.map (·.k) = List.range' 4448 32 := by decide +kernel
theorem d17_4_okE : (d17_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4479, 4495, 111), (4496, 4512, 110)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_4_k : d17_4.map (·.k) = List.range' 4480 32 := by decide +kernel
theorem d17_5_okE : (d17_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4496, 4512, 110), (4513, 4530, 109), (4531, 4547, 108)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_5_k : d17_5.map (·.k) = List.range' 4512 32 := by decide +kernel
theorem d17_6_okE : (d17_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4531, 4547, 108), (4548, 4566, 107), (4567, 4584, 106)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_6_k : d17_6.map (·.k) = List.range' 4544 32 := by decide +kernel
theorem d17_7_okE : (d17_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4567, 4584, 106), (4585, 4603, 105), (4604, 4623, 104)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_7_k : d17_7.map (·.k) = List.range' 4576 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c566
