-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c704.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c704
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(5141, 5143, 179), (5144, 5145, 178), (5146, 5148, 177), (5149, 5151, 176), (5152, 5154, 175), (5155, 5157, 174), (5158, 5160, 173), (5161, 5163, 172), (5164, 5166, 171), (5167, 5169, 170), (5170, 5172, 169), (5173, 5175, 168), (5176, 5178, 167), (5179, 5182, 166), (5183, 5185, 165), (5186, 5188, 164), (5189, 5192, 163), (5193, 5195, 162), (5196, 5199, 161), (5200, 5203, 160), (5204, 5206, 159), (5207, 5210, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c704
