-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c704.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c704
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(7007, 7057, 47), (7058, 7109, 46), (7110, 7162, 45), (7163, 7217, 44), (7218, 7272, 43), (7273, 7329, 42), (7330, 7387, 41), (7388, 7447, 40), (7448, 7507, 39), (7508, 7568, 38), (7569, 7630, 37), (7631, 7693, 36), (7694, 7757, 35), (7758, 7822, 34), (7823, 7887, 33), (7888, 7953, 32), (7954, 8019, 31), (8020, 8085, 30), (8086, 8151, 29), (8152, 8190, 28), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c704
