-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c21.Data22
import Solutions.SharpCertFast.P06P0r12c21.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c21
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d22_0_okE : (d22_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 5678, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_0_k : d22_0.map (·.k) = List.range' 5632 32 := by decide +kernel
theorem d22_1_okE : (d22_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 5678, 201), (5679, 5695, 200)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_1_k : d22_1.map (·.k) = List.range' 5664 32 := by decide +kernel
theorem d22_2_okE : (d22_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5696, 5713, 199), (5714, 5731, 198)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_2_k : d22_2.map (·.k) = List.range' 5696 32 := by decide +kernel
theorem d22_3_okE : (d22_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5714, 5731, 198), (5732, 5749, 197), (5750, 5767, 196)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_3_k : d22_3.map (·.k) = List.range' 5728 32 := by decide +kernel
theorem d22_4_okE : (d22_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5750, 5767, 196), (5768, 5785, 195), (5786, 5804, 194)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_4_k : d22_4.map (·.k) = List.range' 5760 32 := by decide +kernel
theorem d22_5_okE : (d22_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5786, 5804, 194), (5805, 5823, 193)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_5_k : d22_5.map (·.k) = List.range' 5792 32 := by decide +kernel
theorem d22_6_okE : (d22_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5824, 5842, 192), (5843, 5861, 191)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_6_k : d22_6.map (·.k) = List.range' 5824 32 := by decide +kernel
theorem d22_7_okE : (d22_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5843, 5861, 191), (5862, 5881, 190), (5882, 5900, 189)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d22_7_k : d22_7.map (·.k) = List.range' 5856 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c21
