-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c558.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c558
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(3762, 3772, 135), (3773, 3784, 134), (3785, 3796, 133), (3797, 3808, 132), (3809, 3820, 131), (3821, 3832, 130), (3833, 3845, 129), (3846, 3858, 128), (3859, 3872, 127), (3873, 3885, 126), (3886, 3899, 125), (3900, 3913, 124), (3914, 3927, 123), (3928, 3942, 122), (3943, 3957, 121), (3958, 3972, 120), (3973, 3987, 119), (3988, 4003, 118), (4004, 4019, 117), (4020, 4036, 116), (4037, 4052, 115), (4053, 4069, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c558
