-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c558.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c558
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5360, 5407, 69), (5408, 5456, 68), (5457, 5507, 67), (5508, 5558, 66), (5559, 5611, 65), (5612, 5665, 64), (5666, 5721, 63), (5722, 5778, 62), (5779, 5836, 61), (5837, 5896, 60), (5897, 5957, 59), (5958, 6020, 58), (6021, 6084, 57), (6085, 6149, 56), (6150, 6216, 55), (6217, 6285, 54), (6286, 6355, 53), (6356, 6427, 52), (6428, 6501, 51), (6502, 6575, 50), (6576, 6652, 49), (6653, 6730, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c558
