-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c446.Data10
import Solutions.SharpCertFast.P06P0r12c446.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c446
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d10_0_okE : (d10_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2668, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_0_k : d10_0.map (·.k) = List.range' 2560 32 := by decide +kernel
theorem d10_1_okE : (d10_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2668, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_1_k : d10_1.map (·.k) = List.range' 2592 32 := by decide +kernel
theorem d10_2_okE : (d10_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2668, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_2_k : d10_2.map (·.k) = List.range' 2624 32 := by decide +kernel
theorem d10_3_okE : (d10_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2668, 201), (2669, 2674, 200), (2675, 2679, 199), (2680, 2685, 198), (2686, 2691, 197)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_3_k : d10_3.map (·.k) = List.range' 2656 32 := by decide +kernel
theorem d10_4_okE : (d10_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2686, 2691, 197), (2692, 2696, 196), (2697, 2702, 195), (2703, 2708, 194), (2709, 2714, 193), (2715, 2720, 192)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_4_k : d10_4.map (·.k) = List.range' 2688 32 := by decide +kernel
theorem d10_5_okE : (d10_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2715, 2720, 192), (2721, 2727, 191), (2728, 2733, 190), (2734, 2739, 189), (2740, 2746, 188), (2747, 2752, 187)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_5_k : d10_5.map (·.k) = List.range' 2720 32 := by decide +kernel
theorem d10_6_okE : (d10_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2747, 2752, 187), (2753, 2759, 186), (2760, 2765, 185), (2766, 2772, 184), (2773, 2779, 183), (2780, 2786, 182)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_6_k : d10_6.map (·.k) = List.range' 2752 32 := by decide +kernel
theorem d10_7_okE : (d10_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2780, 2786, 182), (2787, 2793, 181), (2794, 2800, 180), (2801, 2808, 179), (2809, 2815, 178)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_7_k : d10_7.map (·.k) = List.range' 2784 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c446
