-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c915.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c915
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(4896, 4905, 113), (4906, 4915, 112), (4916, 4925, 111), (4926, 4935, 110), (4936, 4946, 109), (4947, 4957, 108), (4958, 4968, 107), (4969, 4980, 106), (4981, 4992, 105), (4993, 5004, 104), (5005, 5016, 103), (5017, 5029, 102), (5030, 5042, 101), (5043, 5056, 100), (5057, 5069, 99), (5070, 5083, 98), (5084, 5098, 97), (5099, 5113, 96), (5114, 5128, 95), (5129, 5144, 94), (5145, 5160, 93), (5161, 5176, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c915
