-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c450.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c450
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5159, 5213, 69), (5214, 5269, 68), (5270, 5326, 67), (5327, 5385, 66), (5386, 5446, 65), (5447, 5507, 64), (5508, 5571, 63), (5572, 5635, 62), (5636, 5702, 61), (5703, 5769, 60), (5770, 5838, 59), (5839, 5909, 58), (5910, 5982, 57), (5983, 6056, 56), (6057, 6131, 55), (6132, 6208, 54), (6209, 6287, 53), (6288, 6368, 52), (6369, 6450, 51), (6451, 6533, 50), (6534, 6619, 49), (6620, 6706, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c450
