-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c270.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c270
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(3829, 3851, 113), (3852, 3876, 112), (3877, 3900, 111), (3901, 3925, 110), (3926, 3951, 109), (3952, 3977, 108), (3978, 4004, 107), (4005, 4031, 106), (4032, 4059, 105), (4060, 4087, 104), (4088, 4115, 103), (4116, 4145, 102), (4146, 4175, 101), (4176, 4205, 100), (4206, 4236, 99), (4237, 4268, 98), (4269, 4300, 97), (4301, 4333, 96), (4334, 4367, 95), (4368, 4401, 94), (4402, 4436, 93), (4437, 4472, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c270
