-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c223.Data14
import Solutions.SharpCertFast.P06P0r12c223.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c223
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d14_0_okE : (d14_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3557, 3601, 93), (3602, 3647, 92)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_0_k : d14_0.map (·.k) = List.range' 3584 32 := by decide +kernel
theorem d14_1_okE : (d14_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3602, 3647, 92)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_1_k : d14_1.map (·.k) = List.range' 3616 32 := by decide +kernel
theorem d14_2_okE : (d14_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3648, 3693, 91)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_2_k : d14_2.map (·.k) = List.range' 3648 32 := by decide +kernel
theorem d14_3_okE : (d14_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3648, 3693, 91), (3694, 3741, 90)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_3_k : d14_3.map (·.k) = List.range' 3680 32 := by decide +kernel
theorem d14_4_okE : (d14_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3694, 3741, 90), (3742, 3789, 89)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_4_k : d14_4.map (·.k) = List.range' 3712 32 := by decide +kernel
theorem d14_5_okE : (d14_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3742, 3789, 89)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_5_k : d14_5.map (·.k) = List.range' 3744 32 := by decide +kernel
theorem d14_6_okE : (d14_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3742, 3789, 89), (3790, 3839, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_6_k : d14_6.map (·.k) = List.range' 3776 32 := by decide +kernel
theorem d14_7_okE : (d14_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3790, 3839, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_7_k : d14_7.map (·.k) = List.range' 3808 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c223
