-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c454.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c454
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5453, 5504, 69), (5505, 5556, 68), (5557, 5610, 67), (5611, 5666, 66), (5667, 5722, 65), (5723, 5780, 64), (5781, 5839, 63), (5840, 5900, 62), (5901, 5962, 61), (5963, 6025, 60), (6026, 6090, 59), (6091, 6156, 58), (6157, 6224, 57), (6225, 6293, 56), (6294, 6364, 55), (6365, 6436, 54), (6437, 6510, 53), (6511, 6585, 52), (6586, 6662, 51), (6663, 6740, 50), (6741, 6820, 49), (6821, 6901, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c454
