-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c639.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c639
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(4599, 4611, 113), (4612, 4624, 112), (4625, 4638, 111), (4639, 4652, 110), (4653, 4667, 109), (4668, 4681, 108), (4682, 4696, 107), (4697, 4711, 106), (4712, 4727, 105), (4728, 4743, 104), (4744, 4760, 103), (4761, 4776, 102), (4777, 4794, 101), (4795, 4811, 100), (4812, 4829, 99), (4830, 4848, 98), (4849, 4866, 97), (4867, 4886, 96), (4887, 4905, 95), (4906, 4926, 94), (4927, 4946, 93), (4947, 4968, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c639
