-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c700.Data18
import Solutions.SharpCertFast.P06P0r12c700.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c700
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d18_0_okE : (d18_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4603, 4612, 121), (4613, 4623, 120), (4624, 4633, 119), (4634, 4644, 118)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_0_k : d18_0.map (·.k) = List.range' 4608 32 := by decide +kernel
theorem d18_1_okE : (d18_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4634, 4644, 118), (4645, 4656, 117), (4657, 4667, 116), (4668, 4679, 115)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_1_k : d18_1.map (·.k) = List.range' 4640 32 := by decide +kernel
theorem d18_2_okE : (d18_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4668, 4679, 115), (4680, 4691, 114), (4692, 4703, 113)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_2_k : d18_2.map (·.k) = List.range' 4672 32 := by decide +kernel
theorem d18_3_okE : (d18_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4704, 4716, 112), (4717, 4729, 111), (4730, 4742, 110)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_3_k : d18_3.map (·.k) = List.range' 4704 32 := by decide +kernel
theorem d18_4_okE : (d18_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4730, 4742, 110), (4743, 4755, 109), (4756, 4769, 108)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_4_k : d18_4.map (·.k) = List.range' 4736 32 := by decide +kernel
theorem d18_5_okE : (d18_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4756, 4769, 108), (4770, 4783, 107), (4784, 4797, 106), (4798, 4812, 105)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_5_k : d18_5.map (·.k) = List.range' 4768 32 := by decide +kernel
theorem d18_6_okE : (d18_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4798, 4812, 105), (4813, 4827, 104), (4828, 4842, 103)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_6_k : d18_6.map (·.k) = List.range' 4800 32 := by decide +kernel
theorem d18_7_okE : (d18_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4828, 4842, 103), (4843, 4858, 102), (4859, 4874, 101)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_7_k : d18_7.map (·.k) = List.range' 4832 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c700
