-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c573.Data25
import Solutions.SharpCertFast.P06P0r12c573.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c573
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d25_0_okE : (d25_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6394, 6405, 81), (6406, 6418, 80), (6419, 6431, 79)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_0_k : d25_0.map (·.k) = List.range' 6400 32 := by decide +kernel
theorem d25_1_okE : (d25_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6432, 6444, 78), (6445, 6458, 77), (6459, 6472, 76)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_1_k : d25_1.map (·.k) = List.range' 6432 32 := by decide +kernel
theorem d25_2_okE : (d25_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6459, 6472, 76), (6473, 6487, 75), (6488, 6502, 74)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_2_k : d25_2.map (·.k) = List.range' 6464 32 := by decide +kernel
theorem d25_3_okE : (d25_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6488, 6502, 74), (6503, 6518, 73), (6519, 6534, 72)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_3_k : d25_3.map (·.k) = List.range' 6496 32 := by decide +kernel
theorem d25_4_okE : (d25_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6519, 6534, 72), (6535, 6551, 71), (6552, 6568, 70)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_4_k : d25_4.map (·.k) = List.range' 6528 32 := by decide +kernel
theorem d25_5_okE : (d25_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6552, 6568, 70), (6569, 6586, 69), (6587, 6604, 68)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_5_k : d25_5.map (·.k) = List.range' 6560 32 := by decide +kernel
theorem d25_6_okE : (d25_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6587, 6604, 68), (6605, 6623, 67)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_6_k : d25_6.map (·.k) = List.range' 6592 32 := by decide +kernel
theorem d25_7_okE : (d25_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6624, 6642, 66), (6643, 6663, 65)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d25_7_k : d25_7.map (·.k) = List.range' 6624 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c573
