-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c758.Data18
import Solutions.SharpCertFast.P06P0r12c758.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c758
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d18_0_okE : (d18_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4606, 4609, 181), (4610, 4614, 180), (4615, 4618, 179), (4619, 4622, 178), (4623, 4627, 177), (4628, 4631, 176), (4632, 4636, 175), (4637, 4641, 174)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_0_k : d18_0.map (·.k) = List.range' 4608 32 := by decide +kernel
theorem d18_1_okE : (d18_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4637, 4641, 174), (4642, 4645, 173), (4646, 4650, 172), (4651, 4655, 171), (4656, 4660, 170), (4661, 4665, 169), (4666, 4670, 168), (4671, 4675, 167)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_1_k : d18_1.map (·.k) = List.range' 4640 32 := by decide +kernel
theorem d18_2_okE : (d18_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4671, 4675, 167), (4676, 4681, 166), (4682, 4686, 165), (4687, 4691, 164), (4692, 4697, 163), (4698, 4703, 162)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_2_k : d18_2.map (·.k) = List.range' 4672 32 := by decide +kernel
theorem d18_3_okE : (d18_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4704, 4708, 161), (4709, 4714, 160), (4715, 4720, 159), (4721, 4726, 158), (4727, 4732, 157), (4733, 4738, 156)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_3_k : d18_3.map (·.k) = List.range' 4704 32 := by decide +kernel
theorem d18_4_okE : (d18_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4733, 4738, 156), (4739, 4744, 155), (4745, 4751, 154), (4752, 4757, 153), (4758, 4764, 152), (4765, 4771, 151)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_4_k : d18_4.map (·.k) = List.range' 4736 32 := by decide +kernel
theorem d18_5_okE : (d18_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4765, 4771, 151), (4772, 4777, 150), (4778, 4784, 149), (4785, 4791, 148), (4792, 4798, 147), (4799, 4806, 146)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_5_k : d18_5.map (·.k) = List.range' 4768 32 := by decide +kernel
theorem d18_6_okE : (d18_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4799, 4806, 146), (4807, 4813, 145), (4814, 4821, 144), (4822, 4828, 143), (4829, 4836, 142)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_6_k : d18_6.map (·.k) = List.range' 4800 32 := by decide +kernel
theorem d18_7_okE : (d18_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4829, 4836, 142), (4837, 4844, 141), (4845, 4852, 140), (4853, 4860, 139), (4861, 4869, 138)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_7_k : d18_7.map (·.k) = List.range' 4832 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c758
