-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c758.Data21
import Solutions.SharpCertFast.P06P0r12c758.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c758
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d21_0_okE : (d21_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5360, 5377, 98), (5378, 5396, 97), (5397, 5415, 96)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_0_k : d21_0.map (·.k) = List.range' 5376 32 := by decide +kernel
theorem d21_1_okE : (d21_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5397, 5415, 96), (5416, 5435, 95), (5436, 5455, 94)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_1_k : d21_1.map (·.k) = List.range' 5408 32 := by decide +kernel
theorem d21_2_okE : (d21_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5436, 5455, 94), (5456, 5476, 93)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_2_k : d21_2.map (·.k) = List.range' 5440 32 := by decide +kernel
theorem d21_3_okE : (d21_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5456, 5476, 93), (5477, 5497, 92), (5498, 5518, 91)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_3_k : d21_3.map (·.k) = List.range' 5472 32 := by decide +kernel
theorem d21_4_okE : (d21_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5498, 5518, 91), (5519, 5540, 90)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_4_k : d21_4.map (·.k) = List.range' 5504 32 := by decide +kernel
theorem d21_5_okE : (d21_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5519, 5540, 90), (5541, 5563, 89), (5564, 5586, 88)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_5_k : d21_5.map (·.k) = List.range' 5536 32 := by decide +kernel
theorem d21_6_okE : (d21_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5564, 5586, 88), (5587, 5610, 87)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_6_k : d21_6.map (·.k) = List.range' 5568 32 := by decide +kernel
theorem d21_7_okE : (d21_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5587, 5610, 87), (5611, 5634, 86)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_7_k : d21_7.map (·.k) = List.range' 5600 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c758
