-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c121.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c121
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(7179, 7264, 47), (7265, 7350, 46), (7351, 7437, 45), (7438, 7525, 44), (7526, 7614, 43), (7615, 7703, 42), (7704, 7793, 41), (7794, 7883, 40), (7884, 7974, 39), (7975, 8065, 38), (8066, 8155, 37), (8156, 8190, 36), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c121
