-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c309.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c309
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 2159, 201), (2160, 2165, 200), (2166, 2172, 199), (2173, 2178, 198), (2179, 2184, 197), (2185, 2190, 196), (2191, 2197, 195), (2198, 2203, 194), (2204, 2210, 193), (2211, 2217, 192), (2218, 2224, 191), (2225, 2231, 190), (2232, 2238, 189), (2239, 2245, 188), (2246, 2252, 187), (2253, 2259, 186), (2260, 2267, 185), (2268, 2274, 184), (2275, 2282, 183), (2283, 2289, 182), (2290, 2297, 181), (2298, 2305, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c309
