-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c484.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c484
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5346, 5399, 69), (5400, 5456, 68), (5457, 5513, 67), (5514, 5572, 66), (5573, 5632, 65), (5633, 5693, 64), (5694, 5756, 63), (5757, 5820, 62), (5821, 5885, 61), (5886, 5952, 60), (5953, 6021, 59), (6022, 6091, 58), (6092, 6162, 57), (6163, 6235, 56), (6236, 6310, 55), (6311, 6386, 54), (6387, 6464, 53), (6465, 6543, 52), (6544, 6623, 51), (6624, 6706, 50), (6707, 6789, 49), (6790, 6874, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c484
