-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c741.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c741
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(4357, 4361, 157), (4362, 4367, 156), (4368, 4373, 155), (4374, 4379, 154), (4380, 4385, 153), (4386, 4391, 152), (4392, 4398, 151), (4399, 4404, 150), (4405, 4411, 149), (4412, 4417, 148), (4418, 4424, 147), (4425, 4431, 146), (4432, 4438, 145), (4439, 4445, 144), (4446, 4452, 143), (4453, 4460, 142), (4461, 4467, 141), (4468, 4475, 140), (4476, 4482, 139), (4483, 4490, 138), (4491, 4498, 137), (4499, 4507, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c741
