-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c609.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c609
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(4180, 4183, 179), (4184, 4187, 178), (4188, 4192, 177), (4193, 4196, 176), (4197, 4200, 175), (4201, 4205, 174), (4206, 4210, 173), (4211, 4214, 172), (4215, 4219, 171), (4220, 4224, 170), (4225, 4229, 169), (4230, 4234, 168), (4235, 4239, 167), (4240, 4244, 166), (4245, 4250, 165), (4251, 4255, 164), (4256, 4261, 163), (4262, 4266, 162), (4267, 4272, 161), (4273, 4277, 160), (4278, 4283, 159), (4284, 4289, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c609
