-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c59.Data104
import Solutions.SharpCertFast.P06P0r12c59.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c59
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d104_0_okE : (d104_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26483, 26701, 66)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d104_0_k : d104_0.map (·.k) = List.range' 26624 32 := by decide +kernel
theorem d104_1_okE : (d104_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26483, 26701, 66)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d104_1_k : d104_1.map (·.k) = List.range' 26656 32 := by decide +kernel
theorem d104_2_okE : (d104_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26483, 26701, 66), (26702, 26923, 65)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d104_2_k : d104_2.map (·.k) = List.range' 26688 32 := by decide +kernel
theorem d104_3_okE : (d104_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26702, 26923, 65)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d104_3_k : d104_3.map (·.k) = List.range' 26720 32 := by decide +kernel
theorem d104_4_okE : (d104_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26702, 26923, 65)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d104_4_k : d104_4.map (·.k) = List.range' 26752 32 := by decide +kernel
theorem d104_5_okE : (d104_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26702, 26923, 65)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d104_5_k : d104_5.map (·.k) = List.range' 26784 32 := by decide +kernel
theorem d104_6_okE : (d104_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26702, 26923, 65)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d104_6_k : d104_6.map (·.k) = List.range' 26816 32 := by decide +kernel
theorem d104_7_okE : (d104_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(26702, 26923, 65)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d104_7_k : d104_7.map (·.k) = List.range' 26848 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c59
