-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c147.Data6
import Solutions.SharpCertFast.P06P0r12c147.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c147
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d6_0_okE : (d6_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1535, 1547, 172), (1548, 1560, 171), (1561, 1573, 170)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_0_k : d6_0.map (·.k) = List.range' 1536 32 := by decide +kernel
theorem d6_1_okE : (d6_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1561, 1573, 170), (1574, 1586, 169), (1587, 1599, 168)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_1_k : d6_1.map (·.k) = List.range' 1568 32 := by decide +kernel
theorem d6_2_okE : (d6_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1600, 1613, 167), (1614, 1626, 166), (1627, 1640, 165)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_2_k : d6_2.map (·.k) = List.range' 1600 32 := by decide +kernel
theorem d6_3_okE : (d6_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1627, 1640, 165), (1641, 1654, 164), (1655, 1669, 163)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_3_k : d6_3.map (·.k) = List.range' 1632 32 := by decide +kernel
theorem d6_4_okE : (d6_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1655, 1669, 163), (1670, 1683, 162), (1684, 1698, 161)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_4_k : d6_4.map (·.k) = List.range' 1664 32 := by decide +kernel
theorem d6_5_okE : (d6_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1684, 1698, 161), (1699, 1713, 160), (1714, 1728, 159)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_5_k : d6_5.map (·.k) = List.range' 1696 32 := by decide +kernel
theorem d6_6_okE : (d6_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1714, 1728, 159), (1729, 1743, 158), (1744, 1759, 157)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_6_k : d6_6.map (·.k) = List.range' 1728 32 := by decide +kernel
theorem d6_7_okE : (d6_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(1760, 1774, 156), (1775, 1790, 155), (1791, 1807, 154)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d6_7_k : d6_7.map (·.k) = List.range' 1760 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c147
