-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c204.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c204
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(2916, 2933, 135), (2934, 2951, 134), (2952, 2970, 133), (2971, 2989, 132), (2990, 3008, 131), (3009, 3028, 130), (3029, 3048, 129), (3049, 3068, 128), (3069, 3089, 127), (3090, 3110, 126), (3111, 3131, 125), (3132, 3153, 124), (3154, 3175, 123), (3176, 3197, 122), (3198, 3220, 121), (3221, 3243, 120), (3244, 3267, 119), (3268, 3291, 118), (3292, 3316, 117), (3317, 3341, 116), (3342, 3366, 115), (3367, 3392, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c204
