-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c610.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c610
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP4 : List (ℕ × ℕ × ℕ) := [(4755, 4768, 113), (4769, 4782, 112), (4783, 4796, 111), (4797, 4810, 110), (4811, 4825, 109), (4826, 4840, 108), (4841, 4856, 107), (4857, 4872, 106), (4873, 4888, 105), (4889, 4904, 104), (4905, 4921, 103), (4922, 4939, 102), (4940, 4956, 101), (4957, 4974, 100), (4975, 4993, 99), (4994, 5012, 98), (5013, 5031, 97), (5032, 5051, 96), (5052, 5071, 95), (5072, 5092, 94), (5093, 5113, 93), (5114, 5135, 92)]
theorem envP4_ok : envP4.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c610
