-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c591.Data17
import Solutions.SharpCertFast.P06P0r12c591.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c591
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d17_0_okE : (d17_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4346, 4353, 141), (4354, 4361, 140), (4362, 4369, 139), (4370, 4378, 138), (4379, 4387, 137)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_0_k : d17_0.map (·.k) = List.range' 4352 32 := by decide +kernel
theorem d17_1_okE : (d17_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4379, 4387, 137), (4388, 4395, 136), (4396, 4404, 135), (4405, 4414, 134), (4415, 4423, 133)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_1_k : d17_1.map (·.k) = List.range' 4384 32 := by decide +kernel
theorem d17_2_okE : (d17_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4415, 4423, 133), (4424, 4433, 132), (4434, 4442, 131), (4443, 4452, 130)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_2_k : d17_2.map (·.k) = List.range' 4416 32 := by decide +kernel
theorem d17_3_okE : (d17_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4443, 4452, 130), (4453, 4462, 129), (4463, 4473, 128), (4474, 4483, 127)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_3_k : d17_3.map (·.k) = List.range' 4448 32 := by decide +kernel
theorem d17_4_okE : (d17_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4474, 4483, 127), (4484, 4494, 126), (4495, 4505, 125), (4506, 4516, 124)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_4_k : d17_4.map (·.k) = List.range' 4480 32 := by decide +kernel
theorem d17_5_okE : (d17_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4506, 4516, 124), (4517, 4527, 123), (4528, 4539, 122), (4540, 4551, 121)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_5_k : d17_5.map (·.k) = List.range' 4512 32 := by decide +kernel
theorem d17_6_okE : (d17_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4540, 4551, 121), (4552, 4563, 120), (4564, 4575, 119)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_6_k : d17_6.map (·.k) = List.range' 4544 32 := by decide +kernel
theorem d17_7_okE : (d17_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4576, 4587, 118), (4588, 4600, 117), (4601, 4613, 116)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d17_7_k : d17_7.map (·.k) = List.range' 4576 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c591
