-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c635.Data24
import Solutions.SharpCertFast.P06P0r12c635.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c635
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d24_0_okE : (d24_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6144, 6146, 137), (6147, 6149, 136), (6150, 6152, 135), (6153, 6155, 134), (6156, 6158, 133), (6159, 6161, 132), (6162, 6164, 131), (6165, 6168, 130), (6169, 6171, 129), (6172, 6175, 128)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_0_k : d24_0.map (·.k) = List.range' 6144 32 := by decide +kernel
theorem d24_1_okE : (d24_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6176, 6178, 127), (6179, 6182, 126), (6183, 6185, 125), (6186, 6189, 124), (6190, 6193, 123), (6194, 6197, 122), (6198, 6201, 121), (6202, 6205, 120), (6206, 6210, 119)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_1_k : d24_1.map (·.k) = List.range' 6176 32 := by decide +kernel
theorem d24_2_okE : (d24_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6206, 6210, 119), (6211, 6214, 118), (6215, 6218, 117), (6219, 6223, 116), (6224, 6228, 115), (6229, 6232, 114), (6233, 6237, 113), (6238, 6242, 112)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_2_k : d24_2.map (·.k) = List.range' 6208 32 := by decide +kernel
theorem d24_3_okE : (d24_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6238, 6242, 112), (6243, 6247, 111), (6248, 6253, 110), (6254, 6258, 109), (6259, 6263, 108), (6264, 6269, 107), (6270, 6275, 106)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_3_k : d24_3.map (·.k) = List.range' 6240 32 := by decide +kernel
theorem d24_4_okE : (d24_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6270, 6275, 106), (6276, 6281, 105), (6282, 6287, 104), (6288, 6293, 103), (6294, 6299, 102), (6300, 6306, 101)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_4_k : d24_4.map (·.k) = List.range' 6272 32 := by decide +kernel
theorem d24_5_okE : (d24_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6300, 6306, 101), (6307, 6313, 100), (6314, 6320, 99), (6321, 6327, 98), (6328, 6334, 97), (6335, 6341, 96)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_5_k : d24_5.map (·.k) = List.range' 6304 32 := by decide +kernel
theorem d24_6_okE : (d24_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6335, 6341, 96), (6342, 6349, 95), (6350, 6357, 94), (6358, 6365, 93), (6366, 6374, 92)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_6_k : d24_6.map (·.k) = List.range' 6336 32 := by decide +kernel
theorem d24_7_okE : (d24_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(6366, 6374, 92), (6375, 6382, 91), (6383, 6391, 90), (6392, 6400, 89)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d24_7_k : d24_7.map (·.k) = List.range' 6368 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c635
