-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c50.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c50
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(6295, 6316, 179), (6317, 6337, 178), (6338, 6359, 177), (6360, 6382, 176), (6383, 6404, 175), (6405, 6427, 174), (6428, 6450, 173), (6451, 6474, 172), (6475, 6497, 171), (6498, 6521, 170), (6522, 6546, 169), (6547, 6570, 168), (6571, 6595, 167), (6596, 6620, 166), (6621, 6646, 165), (6647, 6672, 164), (6673, 6698, 163), (6699, 6725, 162), (6726, 6752, 161), (6753, 6779, 160), (6780, 6807, 159), (6808, 6835, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c50
