-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c303.Data9
import Solutions.SharpCertFast.P06P0r12c303.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c303
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d9_0_okE : (d9_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2362, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_0_k : d9_0.map (·.k) = List.range' 2304 32 := by decide +kernel
theorem d9_1_okE : (d9_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2362, 201), (2363, 2368, 200)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_1_k : d9_1.map (·.k) = List.range' 2336 32 := by decide +kernel
theorem d9_2_okE : (d9_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2363, 2368, 200), (2369, 2374, 199), (2375, 2380, 198), (2381, 2387, 197), (2388, 2393, 196), (2394, 2400, 195)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_2_k : d9_2.map (·.k) = List.range' 2368 32 := by decide +kernel
theorem d9_3_okE : (d9_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2394, 2400, 195), (2401, 2406, 194), (2407, 2413, 193), (2414, 2420, 192), (2421, 2427, 191), (2428, 2434, 190)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_3_k : d9_3.map (·.k) = List.range' 2400 32 := by decide +kernel
theorem d9_4_okE : (d9_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2428, 2434, 190), (2435, 2441, 189), (2442, 2448, 188), (2449, 2455, 187), (2456, 2463, 186)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_4_k : d9_4.map (·.k) = List.range' 2432 32 := by decide +kernel
theorem d9_5_okE : (d9_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2464, 2470, 185), (2471, 2478, 184), (2479, 2485, 183), (2486, 2493, 182), (2494, 2501, 181)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_5_k : d9_5.map (·.k) = List.range' 2464 32 := by decide +kernel
theorem d9_6_okE : (d9_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2494, 2501, 181), (2502, 2509, 180), (2510, 2517, 179), (2518, 2525, 178), (2526, 2534, 177)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_6_k : d9_6.map (·.k) = List.range' 2496 32 := by decide +kernel
theorem d9_7_okE : (d9_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2526, 2534, 177), (2535, 2542, 176), (2543, 2551, 175), (2552, 2559, 174)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_7_k : d9_7.map (·.k) = List.range' 2528 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c303
