-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c303.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c303
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP7 : List (ℕ × ℕ × ℕ) := [(6791, 6884, 47), (6885, 6980, 46), (6981, 7077, 45), (7078, 7175, 44), (7176, 7275, 43), (7276, 7376, 42), (7377, 7478, 41), (7479, 7581, 40), (7582, 7685, 39), (7686, 7790, 38), (7791, 7895, 37), (7896, 8002, 36), (8003, 8109, 35), (8110, 8187, 34), (8188, 8190, 33), (8191, 8191, 0)]
theorem envP7_ok : envP7.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c303
