-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c318.Data11
import Solutions.SharpCertFast.P06P0r12c318.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c318
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d11_0_okE : (d11_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2813, 2818, 189), (2819, 2825, 188), (2826, 2831, 187), (2832, 2838, 186), (2839, 2845, 185), (2846, 2851, 184)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_0_k : d11_0.map (·.k) = List.range' 2816 32 := by decide +kernel
theorem d11_1_okE : (d11_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2846, 2851, 184), (2852, 2858, 183), (2859, 2865, 182), (2866, 2872, 181), (2873, 2879, 180)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_1_k : d11_1.map (·.k) = List.range' 2848 32 := by decide +kernel
theorem d11_2_okE : (d11_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2880, 2887, 179), (2888, 2894, 178), (2895, 2901, 177), (2902, 2909, 176), (2910, 2917, 175)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_2_k : d11_2.map (·.k) = List.range' 2880 32 := by decide +kernel
theorem d11_3_okE : (d11_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2910, 2917, 175), (2918, 2924, 174), (2925, 2932, 173), (2933, 2940, 172), (2941, 2948, 171)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_3_k : d11_3.map (·.k) = List.range' 2912 32 := by decide +kernel
theorem d11_4_okE : (d11_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2941, 2948, 171), (2949, 2957, 170), (2958, 2965, 169), (2966, 2973, 168), (2974, 2982, 167)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_4_k : d11_4.map (·.k) = List.range' 2944 32 := by decide +kernel
theorem d11_5_okE : (d11_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2974, 2982, 167), (2983, 2991, 166), (2992, 3000, 165), (3001, 3009, 164)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_5_k : d11_5.map (·.k) = List.range' 2976 32 := by decide +kernel
theorem d11_6_okE : (d11_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3001, 3009, 164), (3010, 3018, 163), (3019, 3027, 162), (3028, 3036, 161), (3037, 3046, 160)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_6_k : d11_6.map (·.k) = List.range' 3008 32 := by decide +kernel
theorem d11_7_okE : (d11_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3037, 3046, 160), (3047, 3056, 159), (3057, 3066, 158), (3067, 3076, 157)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d11_7_k : d11_7.map (·.k) = List.range' 3040 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c318
