-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c910.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c910
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(7564, 7573, 61), (7574, 7582, 60), (7583, 7592, 59), (7593, 7602, 58), (7603, 7612, 57), (7613, 7623, 56), (7624, 7634, 55), (7635, 7646, 54), (7647, 7658, 53), (7659, 7670, 52), (7671, 7683, 51), (7684, 7697, 50), (7698, 7710, 49), (7711, 7725, 48), (7726, 7739, 47), (7740, 7755, 46), (7756, 7771, 45), (7772, 7787, 44), (7788, 7804, 43), (7805, 7821, 42), (7822, 7839, 41), (7840, 7858, 40)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c910
