-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c480.Data73
import Solutions.SharpCertFast.P06P0r12c480.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c480
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d73_0_okE : (d73_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(18651, 18688, 166), (18689, 18725, 165)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d73_0_k : d73_0.map (·.k) = List.range' 18688 32 := by decide +kernel
theorem d73_1_okE : (d73_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(18689, 18725, 165), (18726, 18763, 164)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d73_1_k : d73_1.map (·.k) = List.range' 18720 32 := by decide +kernel
theorem d73_2_okE : (d73_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(18726, 18763, 164), (18764, 18802, 163)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d73_2_k : d73_2.map (·.k) = List.range' 18752 32 := by decide +kernel
theorem d73_3_okE : (d73_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(18764, 18802, 163), (18803, 18841, 162)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d73_3_k : d73_3.map (·.k) = List.range' 18784 32 := by decide +kernel
theorem d73_4_okE : (d73_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(18803, 18841, 162), (18842, 18880, 161)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d73_4_k : d73_4.map (·.k) = List.range' 18816 32 := by decide +kernel
theorem d73_5_okE : (d73_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(18842, 18880, 161)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d73_5_k : d73_5.map (·.k) = List.range' 18848 32 := by decide +kernel
theorem d73_6_okE : (d73_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(18842, 18880, 161), (18881, 18921, 160)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d73_6_k : d73_6.map (·.k) = List.range' 18880 32 := by decide +kernel
theorem d73_7_okE : (d73_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(18881, 18921, 160), (18922, 18961, 159)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d73_7_k : d73_7.map (·.k) = List.range' 18912 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c480
