-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c444.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c444
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 15403, 201), (15404, 15426, 200), (15427, 15450, 199), (15451, 15473, 198), (15474, 15497, 197), (15498, 15521, 196), (15522, 15545, 195), (15546, 15570, 194), (15571, 15595, 193), (15596, 15621, 192), (15622, 15646, 191), (15647, 15672, 190), (15673, 15699, 189), (15700, 15725, 188), (15726, 15752, 187), (15753, 15780, 186), (15781, 15807, 185), (15808, 15836, 184), (15837, 15864, 183), (15865, 15893, 182), (15894, 15922, 181), (15923, 15952, 180)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c444
