-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c585.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c585
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(3733, 3739, 157), (3740, 3746, 156), (3747, 3754, 155), (3755, 3761, 154), (3762, 3769, 153), (3770, 3776, 152), (3777, 3784, 151), (3785, 3792, 150), (3793, 3800, 149), (3801, 3808, 148), (3809, 3817, 147), (3818, 3825, 146), (3826, 3834, 145), (3835, 3843, 144), (3844, 3852, 143), (3853, 3861, 142), (3862, 3870, 141), (3871, 3880, 140), (3881, 3889, 139), (3890, 3899, 138), (3900, 3909, 137), (3910, 3919, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c585
