-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c916.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c916
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(4740, 4745, 135), (4746, 4752, 134), (4753, 4758, 133), (4759, 4764, 132), (4765, 4771, 131), (4772, 4778, 130), (4779, 4784, 129), (4785, 4791, 128), (4792, 4799, 127), (4800, 4806, 126), (4807, 4813, 125), (4814, 4821, 124), (4822, 4829, 123), (4830, 4837, 122), (4838, 4845, 121), (4846, 4853, 120), (4854, 4862, 119), (4863, 4870, 118), (4871, 4879, 117), (4880, 4888, 116), (4889, 4897, 115), (4898, 4907, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c916
