-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c878.Data21
import Solutions.SharpCertFast.P06P0r12c878.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c878
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d21_0_okE : (d21_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5374, 5376, 157), (5377, 5380, 156), (5381, 5383, 155), (5384, 5387, 154), (5388, 5390, 153), (5391, 5394, 152), (5395, 5398, 151), (5399, 5401, 150), (5402, 5405, 149), (5406, 5409, 148)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_0_k : d21_0.map (·.k) = List.range' 5376 32 := by decide +kernel
theorem d21_1_okE : (d21_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5406, 5409, 148), (5410, 5413, 147), (5414, 5417, 146), (5418, 5421, 145), (5422, 5425, 144), (5426, 5430, 143), (5431, 5434, 142), (5435, 5438, 141), (5439, 5443, 140)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_1_k : d21_1.map (·.k) = List.range' 5408 32 := by decide +kernel
theorem d21_2_okE : (d21_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5439, 5443, 140), (5444, 5447, 139), (5448, 5452, 138), (5453, 5457, 137), (5458, 5462, 136), (5463, 5467, 135), (5468, 5472, 134)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_2_k : d21_2.map (·.k) = List.range' 5440 32 := by decide +kernel
theorem d21_3_okE : (d21_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5468, 5472, 134), (5473, 5477, 133), (5478, 5482, 132), (5483, 5488, 131), (5489, 5493, 130), (5494, 5499, 129), (5500, 5505, 128)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_3_k : d21_3.map (·.k) = List.range' 5472 32 := by decide +kernel
theorem d21_4_okE : (d21_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5500, 5505, 128), (5506, 5510, 127), (5511, 5516, 126), (5517, 5522, 125), (5523, 5529, 124), (5530, 5535, 123)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_4_k : d21_4.map (·.k) = List.range' 5504 32 := by decide +kernel
theorem d21_5_okE : (d21_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5536, 5541, 122), (5542, 5548, 121), (5549, 5555, 120), (5556, 5562, 119), (5563, 5569, 118)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_5_k : d21_5.map (·.k) = List.range' 5536 32 := by decide +kernel
theorem d21_6_okE : (d21_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5563, 5569, 118), (5570, 5576, 117), (5577, 5583, 116), (5584, 5591, 115), (5592, 5599, 114)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_6_k : d21_6.map (·.k) = List.range' 5568 32 := by decide +kernel
theorem d21_7_okE : (d21_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(5600, 5607, 113), (5608, 5615, 112), (5616, 5623, 111), (5624, 5631, 110)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d21_7_k : d21_7.map (·.k) = List.range' 5600 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c878
