-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c873.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c873
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP3 : List (ℕ × ℕ × ℕ) := [(6576, 6580, 135), (6581, 6585, 134), (6586, 6590, 133), (6591, 6596, 132), (6597, 6601, 131), (6602, 6606, 130), (6607, 6612, 129), (6613, 6617, 128), (6618, 6623, 127), (6624, 6629, 126), (6630, 6634, 125), (6635, 6640, 124), (6641, 6647, 123), (6648, 6653, 122), (6654, 6659, 121), (6660, 6666, 120), (6667, 6672, 119), (6673, 6679, 118), (6680, 6686, 117), (6687, 6693, 116), (6694, 6700, 115), (6701, 6707, 114)]
theorem envP3_ok : envP3.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c873
