-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c68.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c68
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(5195, 5196, 179), (5197, 5198, 178), (5199, 5201, 177), (5202, 5203, 176), (5204, 5205, 175), (5206, 5207, 174), (5208, 5210, 173), (5211, 5212, 172), (5213, 5215, 171), (5216, 5217, 170), (5218, 5220, 169), (5221, 5222, 168), (5223, 5225, 167), (5226, 5227, 166), (5228, 5230, 165), (5231, 5233, 164), (5234, 5236, 163), (5237, 5238, 162), (5239, 5241, 161), (5242, 5244, 160), (5245, 5247, 159), (5248, 5250, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c68
