-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c750.Data36
import Solutions.SharpCertFast.P06P0r12c750.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c750
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d36_0_okE : (d36_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9210, 9223, 154), (9224, 9238, 153), (9239, 9252, 152)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_0_k : d36_0.map (·.k) = List.range' 9216 32 := by decide +kernel
theorem d36_1_okE : (d36_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9239, 9252, 152), (9253, 9267, 151), (9268, 9282, 150)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_1_k : d36_1.map (·.k) = List.range' 9248 32 := by decide +kernel
theorem d36_2_okE : (d36_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9268, 9282, 150), (9283, 9298, 149), (9299, 9313, 148)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_2_k : d36_2.map (·.k) = List.range' 9280 32 := by decide +kernel
theorem d36_3_okE : (d36_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9299, 9313, 148), (9314, 9329, 147), (9330, 9345, 146)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_3_k : d36_3.map (·.k) = List.range' 9312 32 := by decide +kernel
theorem d36_4_okE : (d36_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9330, 9345, 146), (9346, 9362, 145), (9363, 9378, 144)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_4_k : d36_4.map (·.k) = List.range' 9344 32 := by decide +kernel
theorem d36_5_okE : (d36_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9363, 9378, 144), (9379, 9395, 143), (9396, 9412, 142)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_5_k : d36_5.map (·.k) = List.range' 9376 32 := by decide +kernel
theorem d36_6_okE : (d36_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9396, 9412, 142), (9413, 9430, 141), (9431, 9448, 140)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_6_k : d36_6.map (·.k) = List.range' 9408 32 := by decide +kernel
theorem d36_7_okE : (d36_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(9431, 9448, 140), (9449, 9466, 139), (9467, 9484, 138)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d36_7_k : d36_7.map (·.k) = List.range' 9440 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c750
