-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c92.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c92
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(1811, 1822, 179), (1823, 1834, 178), (1835, 1847, 177), (1848, 1859, 176), (1860, 1872, 175), (1873, 1885, 174), (1886, 1899, 173), (1900, 1912, 172), (1913, 1925, 171), (1926, 1939, 170), (1940, 1953, 169), (1954, 1967, 168), (1968, 1981, 167), (1982, 1996, 166), (1997, 2010, 165), (2011, 2025, 164), (2026, 2040, 163), (2041, 2056, 162), (2057, 2071, 161), (2072, 2087, 160), (2088, 2103, 159), (2104, 2119, 158)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c92
