-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c789.Data18
import Solutions.SharpCertFast.P06P0r12c789.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c789
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d18_0_okE : (d18_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4607, 4613, 142), (4614, 4620, 141), (4621, 4627, 140), (4628, 4634, 139), (4635, 4642, 138)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_0_k : d18_0.map (·.k) = List.range' 4608 32 := by decide +kernel
theorem d18_1_okE : (d18_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4635, 4642, 138), (4643, 4649, 137), (4650, 4657, 136), (4658, 4665, 135), (4666, 4673, 134)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_1_k : d18_1.map (·.k) = List.range' 4640 32 := by decide +kernel
theorem d18_2_okE : (d18_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4666, 4673, 134), (4674, 4681, 133), (4682, 4690, 132), (4691, 4698, 131), (4699, 4707, 130)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_2_k : d18_2.map (·.k) = List.range' 4672 32 := by decide +kernel
theorem d18_3_okE : (d18_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4699, 4707, 130), (4708, 4716, 129), (4717, 4725, 128), (4726, 4734, 127), (4735, 4743, 126)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_3_k : d18_3.map (·.k) = List.range' 4704 32 := by decide +kernel
theorem d18_4_okE : (d18_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4735, 4743, 126), (4744, 4753, 125), (4754, 4763, 124), (4764, 4773, 123)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_4_k : d18_4.map (·.k) = List.range' 4736 32 := by decide +kernel
theorem d18_5_okE : (d18_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4764, 4773, 123), (4774, 4783, 122), (4784, 4793, 121), (4794, 4804, 120)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_5_k : d18_5.map (·.k) = List.range' 4768 32 := by decide +kernel
theorem d18_6_okE : (d18_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4794, 4804, 120), (4805, 4815, 119), (4816, 4826, 118), (4827, 4837, 117)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_6_k : d18_6.map (·.k) = List.range' 4800 32 := by decide +kernel
theorem d18_7_okE : (d18_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(4827, 4837, 117), (4838, 4848, 116), (4849, 4860, 115), (4861, 4872, 114)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d18_7_k : d18_7.map (·.k) = List.range' 4832 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c789
