-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c866.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c866
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP1 : List (ℕ × ℕ × ℕ) := [(5432, 5434, 162), (5435, 5437, 161), (5438, 5440, 160), (5441, 5443, 159), (5444, 5446, 158), (5447, 5449, 157), (5450, 5453, 156), (5454, 5456, 155), (5457, 5459, 154), (5460, 5463, 153), (5464, 5466, 152), (5467, 5470, 151), (5471, 5473, 150), (5474, 5477, 149), (5478, 5481, 148), (5482, 5484, 147), (5485, 5488, 146), (5489, 5492, 145), (5493, 5496, 144), (5497, 5500, 143), (5501, 5504, 142), (5505, 5509, 141)]
theorem envP1_ok : envP1.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c866
