-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c122.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c122
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP2 : List (ℕ × ℕ × ℕ) := [(3064, 3076, 157), (3077, 3090, 156), (3091, 3103, 155), (3104, 3117, 154), (3118, 3131, 153), (3132, 3145, 152), (3146, 3159, 151), (3160, 3174, 150), (3175, 3189, 149), (3190, 3204, 148), (3205, 3219, 147), (3220, 3235, 146), (3236, 3250, 145), (3251, 3266, 144), (3267, 3282, 143), (3283, 3299, 142), (3300, 3315, 141), (3316, 3332, 140), (3333, 3349, 139), (3350, 3367, 138), (3368, 3384, 137), (3385, 3402, 136)]
theorem envP2_ok : envP2.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c122
