-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c210.Data10
import Solutions.SharpCertFast.P06P0r12c210.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c210
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d10_0_okE : (d10_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2560, 2568, 169), (2569, 2578, 168), (2579, 2588, 167), (2589, 2598, 166)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_0_k : d10_0.map (·.k) = List.range' 2560 32 := by decide +kernel
theorem d10_1_okE : (d10_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2589, 2598, 166), (2599, 2609, 165), (2610, 2619, 164), (2620, 2630, 163)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_1_k : d10_1.map (·.k) = List.range' 2592 32 := by decide +kernel
theorem d10_2_okE : (d10_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2620, 2630, 163), (2631, 2640, 162), (2641, 2651, 161), (2652, 2663, 160)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_2_k : d10_2.map (·.k) = List.range' 2624 32 := by decide +kernel
theorem d10_3_okE : (d10_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2652, 2663, 160), (2664, 2674, 159), (2675, 2685, 158), (2686, 2697, 157)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_3_k : d10_3.map (·.k) = List.range' 2656 32 := by decide +kernel
theorem d10_4_okE : (d10_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2686, 2697, 157), (2698, 2709, 156), (2710, 2721, 155)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_4_k : d10_4.map (·.k) = List.range' 2688 32 := by decide +kernel
theorem d10_5_okE : (d10_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2710, 2721, 155), (2722, 2733, 154), (2734, 2745, 153), (2746, 2758, 152)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_5_k : d10_5.map (·.k) = List.range' 2720 32 := by decide +kernel
theorem d10_6_okE : (d10_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2746, 2758, 152), (2759, 2770, 151), (2771, 2783, 150)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_6_k : d10_6.map (·.k) = List.range' 2752 32 := by decide +kernel
theorem d10_7_okE : (d10_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2784, 2796, 149), (2797, 2810, 148), (2811, 2823, 147)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d10_7_k : d10_7.map (·.k) = List.range' 2784 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c210
