-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c528.Data13
import Solutions.SharpCertFast.P06P0r12c528.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c528
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d13_0_okE : (d13_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3521, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_0_k : d13_0.map (·.k) = List.range' 3328 32 := by decide +kernel
theorem d13_1_okE : (d13_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3521, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_1_k : d13_1.map (·.k) = List.range' 3360 32 := by decide +kernel
theorem d13_2_okE : (d13_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3521, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_2_k : d13_2.map (·.k) = List.range' 3392 32 := by decide +kernel
theorem d13_3_okE : (d13_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3521, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_3_k : d13_3.map (·.k) = List.range' 3424 32 := by decide +kernel
theorem d13_4_okE : (d13_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3521, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_4_k : d13_4.map (·.k) = List.range' 3456 32 := by decide +kernel
theorem d13_5_okE : (d13_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3521, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_5_k : d13_5.map (·.k) = List.range' 3488 32 := by decide +kernel
theorem d13_6_okE : (d13_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3521, 201), (3522, 3525, 200), (3526, 3530, 199), (3531, 3534, 198), (3535, 3539, 197), (3540, 3543, 196), (3544, 3548, 195), (3549, 3552, 194)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_6_k : d13_6.map (·.k) = List.range' 3520 32 := by decide +kernel
theorem d13_7_okE : (d13_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3549, 3552, 194), (3553, 3557, 193), (3558, 3562, 192), (3563, 3567, 191), (3568, 3572, 190), (3573, 3577, 189), (3578, 3582, 188), (3583, 3587, 187)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d13_7_k : d13_7.map (·.k) = List.range' 3552 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c528
