-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c528.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c528
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP6 : List (ℕ × ℕ × ℕ) := [(5586, 5632, 69), (5633, 5680, 68), (5681, 5730, 67), (5731, 5780, 66), (5781, 5832, 65), (5833, 5885, 64), (5886, 5939, 63), (5940, 5995, 62), (5996, 6052, 61), (6053, 6110, 60), (6111, 6170, 59), (6171, 6231, 58), (6232, 6293, 57), (6294, 6357, 56), (6358, 6423, 55), (6424, 6489, 54), (6490, 6558, 53), (6559, 6627, 52), (6628, 6698, 51), (6699, 6771, 50), (6772, 6845, 49), (6846, 6921, 48)]
theorem envP6_ok : envP6.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c528
