-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c267.Data9
import Solutions.SharpCertFast.P06P0r12c267.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c267
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d9_0_okE : (d9_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2380, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_0_k : d9_0.map (·.k) = List.range' 2304 32 := by decide +kernel
theorem d9_1_okE : (d9_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2380, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_1_k : d9_1.map (·.k) = List.range' 2336 32 := by decide +kernel
theorem d9_2_okE : (d9_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 2380, 201), (2381, 2386, 200), (2387, 2393, 199), (2394, 2399, 198)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_2_k : d9_2.map (·.k) = List.range' 2368 32 := by decide +kernel
theorem d9_3_okE : (d9_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2400, 2406, 197), (2407, 2412, 196), (2413, 2419, 195), (2420, 2426, 194), (2427, 2432, 193)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_3_k : d9_3.map (·.k) = List.range' 2400 32 := by decide +kernel
theorem d9_4_okE : (d9_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2427, 2432, 193), (2433, 2439, 192), (2440, 2446, 191), (2447, 2453, 190), (2454, 2461, 189), (2462, 2468, 188)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_4_k : d9_4.map (·.k) = List.range' 2432 32 := by decide +kernel
theorem d9_5_okE : (d9_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2462, 2468, 188), (2469, 2475, 187), (2476, 2483, 186), (2484, 2490, 185), (2491, 2498, 184)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_5_k : d9_5.map (·.k) = List.range' 2464 32 := by decide +kernel
theorem d9_6_okE : (d9_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2491, 2498, 184), (2499, 2506, 183), (2507, 2514, 182), (2515, 2522, 181), (2523, 2530, 180)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_6_k : d9_6.map (·.k) = List.range' 2496 32 := by decide +kernel
theorem d9_7_okE : (d9_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(2523, 2530, 180), (2531, 2538, 179), (2539, 2546, 178), (2547, 2555, 177), (2556, 2563, 176)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d9_7_k : d9_7.map (·.k) = List.range' 2528 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c267
