-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c518.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c518
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(4452, 4483, 91), (4484, 4516, 90), (4517, 4549, 89), (4550, 4583, 88), (4584, 4618, 87), (4619, 4653, 86), (4654, 4690, 85), (4691, 4727, 84), (4728, 4765, 83), (4766, 4804, 82), (4805, 4844, 81), (4845, 4884, 80), (4885, 4926, 79), (4927, 4969, 78), (4970, 5012, 77), (5013, 5057, 76), (5058, 5103, 75), (5104, 5150, 74), (5151, 5198, 73), (5199, 5247, 72), (5248, 5297, 71), (5298, 5348, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c518
