-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c594.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c594
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(5381, 5398, 91), (5399, 5416, 90), (5417, 5435, 89), (5436, 5454, 88), (5455, 5474, 87), (5475, 5494, 86), (5495, 5514, 85), (5515, 5536, 84), (5537, 5557, 83), (5558, 5580, 82), (5581, 5603, 81), (5604, 5626, 80), (5627, 5651, 79), (5652, 5676, 78), (5677, 5701, 77), (5702, 5728, 76), (5729, 5755, 75), (5756, 5783, 74), (5784, 5811, 73), (5812, 5841, 72), (5842, 5871, 71), (5872, 5902, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c594
