-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c749.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c749
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP0 : List (ℕ × ℕ × ℕ) := [(0, 6351, 201), (6352, 6352, 173), (6353, 6408, 154), (6409, 6487, 153), (6488, 6489, 152), (6490, 6490, 151), (6491, 6492, 150), (6493, 6494, 149), (6495, 6496, 148), (6497, 6498, 147), (6499, 6499, 146), (6500, 6501, 145), (6502, 6503, 144), (6504, 6505, 143), (6506, 6507, 142), (6508, 6510, 141), (6511, 6512, 140), (6513, 6514, 139), (6515, 6516, 138), (6517, 6518, 137), (6519, 6521, 136), (6522, 6523, 135)]
theorem envP0_ok : envP0.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c749
