-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c825.Base
import Solutions.SharpCertFast.BlockI
namespace DiagRamsey.SharpCert.P06P0r12c825
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
def envP5 : List (ℕ × ℕ × ℕ) := [(5166, 5185, 91), (5186, 5205, 90), (5206, 5225, 89), (5226, 5246, 88), (5247, 5268, 87), (5269, 5290, 86), (5291, 5313, 85), (5314, 5336, 84), (5337, 5360, 83), (5361, 5384, 82), (5385, 5409, 81), (5410, 5435, 80), (5436, 5462, 79), (5463, 5489, 78), (5490, 5517, 77), (5518, 5545, 76), (5546, 5575, 75), (5576, 5605, 74), (5606, 5636, 73), (5637, 5668, 72), (5669, 5701, 71), (5702, 5735, 70)]
theorem envP5_ok : envP5.all (IExp.segOk g K pts) = true := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c825
