-- Generated by research/isidore-the-farmer/p06/gen_fast.py; do not edit.
import Solutions.SharpCertFast.P06P0r12c537.Data14
import Solutions.SharpCertFast.P06P0r12c537.Env
import Solutions.SharpCertFast.CertAny
namespace DiagRamsey.SharpCert.P06P0r12c537
open DiagRamsey.SharpCert
set_option maxRecDepth 100000
theorem d14_0_okE : (d14_0.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3682, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_0_k : d14_0.map (·.k) = List.range' 3584 32 := by decide +kernel
theorem d14_1_okE : (d14_1.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3682, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_1_k : d14_1.map (·.k) = List.range' 3616 32 := by decide +kernel
theorem d14_2_okE : (d14_2.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3682, 201)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_2_k : d14_2.map (·.k) = List.range' 3648 32 := by decide +kernel
theorem d14_3_okE : (d14_3.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(0, 3682, 201), (3683, 3686, 200), (3687, 3690, 199), (3691, 3695, 198), (3696, 3699, 197), (3700, 3703, 196), (3704, 3707, 195), (3708, 3711, 194)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_3_k : d14_3.map (·.k) = List.range' 3680 32 := by decide +kernel
theorem d14_4_okE : (d14_4.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3712, 3716, 193), (3717, 3720, 192), (3721, 3725, 191), (3726, 3729, 190), (3730, 3734, 189), (3735, 3738, 188), (3739, 3743, 187)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_4_k : d14_4.map (·.k) = List.range' 3712 32 := by decide +kernel
theorem d14_5_okE : (d14_5.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3744, 3748, 186), (3749, 3753, 185), (3754, 3758, 184), (3759, 3763, 183), (3764, 3768, 182), (3769, 3773, 181), (3774, 3778, 180)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_5_k : d14_5.map (·.k) = List.range' 3744 32 := by decide +kernel
theorem d14_6_okE : (d14_6.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3774, 3778, 180), (3779, 3783, 179), (3784, 3789, 178), (3790, 3794, 177), (3795, 3800, 176), (3801, 3805, 175), (3806, 3811, 174)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_6_k : d14_6.map (·.k) = List.range' 3776 32 := by decide +kernel
theorem d14_7_okE : (d14_7.map (mkCellD g K)).all (IExp.cellFullAny g pts) = true := by
  first
  | exact IExp.all_any_of_fullI (IExp.full_of_env env_ok (es := [(3806, 3811, 174), (3812, 3817, 173), (3818, 3823, 172), (3824, 3829, 171), (3830, 3835, 170), (3836, 3841, 169)]) (by decide +kernel))
  | exact IExp.all_any_of_full (by decide +kernel)
theorem d14_7_k : d14_7.map (·.k) = List.range' 3808 32 := by decide +kernel
end DiagRamsey.SharpCert.P06P0r12c537
